### ISSUE TITLE
Enhance email body with test result summary

### ISSUE THREAD

**Issue by mariusandreifilip** [mozilla/iris#1012]
High level overview on how will look:

 Run Status:
------------------------------------------------------------------------------------------------------------------------
Platform: win, Firefox Version: 61.0.2, Firefox Build: 20180807170231
Passed: 1, Failed: 0, Skipped: 0, Errors: 0 -- Total: 1                                      Total time: 33.97 second(s)
------------------------------------------------------------------------------------------------------------------------

Email module should also renamed to email_reporting or something similar because generates conflicts with native python dist.py when runned from pycharm

**Comment by mwobensmith** [comment]
What branch does this run on? It might be nice to include branch data in this summary, unless we all understand that it is running on latest `master` or `dev`. I think I'd prefer `dev`.

If you want to add branch data - not required,  but desirable - see `__main__.py`, lines 203-207. 

When we see errors, it would be nice to know if these are current errors or have already been fixed, and the only way to know that is to see branch name and revision.

**Comment by mwobensmith** [comment]
Done!
