### ISSUE TITLE
Develop test case: Pin a thumbnail.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#106]
https://testrail.stage.mozaws.net/index.php?/cases/view/33454

**Comment by ashughes1** [comment]
I am going to try taking this as my first testcase.

**Comment by ashughes1** [comment]
@tracywalker does https://testrail.stage.mozaws.net/index.php?/suites/view/922&group_by=cases:section_id&group_order=asc mean that the new tab page testcases are deprecated, ie. that they are no longer run and not needed for automation?

**Comment by tracywalker** [comment]
Anthony,  this is due to the way the test case repository is managed.  Instead of reusing test cases  (keeping the ID), they simple deprecate a test group,  create a new one and copy tests over (creating new ID's).  In this case, though, it is not clear where this group of test cases went.  It is probably covered, in one way or another in the Activity Stream test group.  I won't be triaging that group for a while since Activity Stream was group 4 of 4 in beta 62.  Anyway, it doesn't hurt anything to automate these tests.  We'll find where they belong later.

**Comment by ashughes1** [comment]
Thank you @tracywalker, I just wanted to make sure my effort wasn't being wasted. I'll start working on this now.
