### ISSUE TITLE
Create helper to deal with the Close multiple tabs dialog

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1086]
Most of the time we'll avoid this with turning off the associated prefs in our set of profiles.  However, some tests need to use LIKE_NEW and those test will have to deal with the dialog as a cleanup step at the end of the test; a call to something like close_tabs_warning()

Let's create that helper.

**Comment by mwobensmith** [comment]
`LIKE_NEW` shouldn't need this, as we've modified its preferences so that this dialog won't come up. However, if a test uses `BRAND_NEW`, they may want to use a helper at the very end of the test.

I think the helper could look something like:
```
def close_multiple_tabs():
    close_tabs_dialog_pattern = Pattern('close_tabs_dialog.png')
    try:
        wait(close_tabs_dialog_pattern, 5)
        type(Key.ENTER)
    except FindError:
        pass
```

**Comment by AndreiH** [comment]
This is ready for review on branch "issue_1086".
Thanks !

**Comment by silviuFlorin** [comment]
@AndreiH : Please replace 
```            
if current.profile == 'brand_new':
                confirm_close_multiple_tabs()
```
With:
```            
if current.profile == Profile.BRAND_NEW:
                confirm_close_multiple_tabs()
```

The rest of the code looks OK

**Comment by AndreiH** [comment]
Update done ! Thanks !

**Comment by silviuFlorin** [comment]
Code approved

**Comment by tracywalker** [comment]
This is not fixed on Linux.  
Iris reports:
[iris.api.helpers.general] Couldn't find the "Close all tabs" warning popup.

As such, we don't get to type(Key.ENTER) to dismiss the dialog.

**Comment by tracywalker** [comment]
This image for close_all_tabs_dialog is quite large.  We can probably make this smaller. Also, we have experienced issues on Linux with image captures that of text not matching at default similarity. Reducing the similarity to say .5 or .6 usually solves the problem.

**Comment by AndreiH** [comment]
I re-tested this on Linux and it works perfectly.
However, as you said before I, made the pictures smaller, capturing only the "Close tabs" button.
The changes are in branch "issue_1086". Please review. Thanks !

**Comment by tracywalker** [comment]
Excellent,  now this works on my Linux machine.

code approved.
