### ISSUE TITLE
Update url_bar_default_zoom_level.png. 

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1088]
When we switched to beta as default this image is no longer valid as is.  The Pocket icon has changed from dark background with white chevron to white background with dark chevron.  Update the pattern, then the zoom indicator tests should be good to go.

**Comment by icrisan** [comment]
fixed added in branch "issue_1088". please review.
P.S: also updated all the failing tests from zoom_indicator section.

**Comment by tracywalker** [comment]
code approved
