### ISSUE TITLE
Fix the failing 'awesomebar' tests

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#1096]
The following tests did not pass:
bookmark_a_highlighted_link
delete_history_from_url_bar_completion_list
disable_one_off_searches_from_awesomebar
disable_search_suggestions
focus_settings_gear_and_click_a_search_result
mouse_position_does_not_affect_a_search
perform_a_search_using_an_one_off
add_links_keyboard_shortcuts
awesomebar_search_after_user_input
search_in_new_tab_using_one_off_context_menu
drag_and_drop_within_awesomebar

**Comment by tracywalker** [comment]
code approved
