### ISSUE TITLE
Fix web_console_controls test case

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1098]
toolbars_window_controls/web_console_controls consistently fails for me on all platforms.  Please investigate and fix this test case failure.

**Comment by icrisan** [comment]
this issue will be fixed in #1111. Closing issue.

**Comment by tracywalker** [comment]
This is still failing for me on Linux.  Iris is not finding the responsive design mode message (it's not on screen for iris to find).

reopening this issue for further investigation.

**Comment by tracywalker** [comment]
code approved
