### ISSUE TITLE
Fix amazon_bookmarks test case

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1103]
experiments/amazon_bookmarks is failing consistently on Windows. Please investigate and fix this failing test.

**Comment by mariusandreifilip** [comment]
Initial test logs
2018-09-04 17:25:53,700 [INFO] [iris.test_runner] Executing: 55 - [amazon_bookmarks]: This is a test for adding a website in the bookmarks section
2018-09-04 17:26:02,073 [ERROR] [iris.api.helpers.results] Error encountered in test, outcome: >>> ERROR <<< 

-----------------------------------------------------------------------------------------------------------
» Traceback (most recent call last):                                                                      «
»   File "c:\iriscron2\iris\iris\test_runner.py", line 73, in run                                         «
»     current.run()                                                                                       «
»   File "c:\iriscron2\iris\iris\tests\experiments\amazon_bookmarks.py", line 24, in run                  «
»     expected_1 = exists(amazon_image_pattern, 10)                                                       «
»   File "c:\iriscron2\iris\iris\api\core\region.py", line 599, in exists                                 «
»     wait(pattern, timeout, in_region)                                                                   «
»   File "c:\iriscron2\iris\iris\api\core\region.py", line 566, in wait                                   «
»     image_found = positive_image_search(image_name, timeout, region)                                    «
»   File "c:\iriscron2\iris\iris\api\core\util\image_search.py", line 270, in positive_image_search       «
»     return _positive_image_search_loop(pattern, timeout, region)                                        «
»   File "c:\iriscron2\iris\iris\api\core\util\image_search.py", line 259, in _positive_image_search_loop «
»     pos = image_search(pattern, region)                                                                 «
»   File "c:\iriscron2\iris\iris\api\core\util\image_search.py", line 183, in image_search                «
»     location = _match_template(pattern, stack_image)                                                    «
»   File "c:\iriscron2\iris\iris\api\core\util\image_search.py", line 163, in _match_template             «
»     position = iris_image_match_template(needle, haystack, precision, None)                             «
»   File "c:\iriscron2\iris\iris\api\core\util\image_search.py", line 77, in iris_image_match_template    «
»     min_val, max_val, min_loc, max_loc = cv2.minMaxLoc(res)                                             «
» TypeError: src is not a numpy array, neither a scalar                                                   «
-----------------------------------------------------------------------------------------------------------

Amazon.png pattern had a duplicate in the bookmark suite  and the removal of it resolved the problem

**Comment by mariusandreifilip** [comment]
Tested on 3 windows machines and test pass.
