### ISSUE TITLE
Investigate and fix test failures on history test suite

### ISSUE THREAD

**Issue by mariusandreifilip** [mozilla/iris#1108]

**Comment by tracywalker** [comment]
Please check the existing issues before filing new ones.  This issue had already been filed #1095. I'll dupe that one and let you work on this. Thanks

**Comment by mariusandreifilip** [comment]
Sorry about this but I didn't saw the ticket initially and that's why I created this one.

**Comment by mariusandreifilip** [comment]
A few highlights of the test changes:
-clear_history dialog box was changed and needed new patterns and test changes an all platforms
-navigate through tabs logic with Ctrl+Tab  changed  and and cycles through tabs in recently used order
-'most_visited' is no longer available in LIKE_NEW profile so I changed it to BRAND_NEW in tests were there is no need to us is
-changed some dialog box patterns due to some style changes on all platforms

Branch  **issue_1108** is up to date and ready for review.

Ran against all platforms and here are a high level results:

Platform: linux, Firefox Version: 63.0, Firefox Build: 20180913141435
Passed: 39, Failed: 0, Skipped: 0, Errors: 0 -- Total: 39                                  Total time: 1150.64 second(s)

Platform: windows, Firefox Version: 63.0, Firefox Build: 20180913141435
Passed: 39, Failed: 0, Skipped: 0, Errors: 0 -- Total: 39                                  Total time: 1099.619 second(s)

Platform: osx, Firefox Version: 63.0, Firefox Build: 20180913141435
Passed: 39, Failed: 0, Skipped: 0, Errors: 0 -- Total: 39                                  Total time: 1170.12 second(s)

**Comment by silviuFlorin** [comment]
Code approved

**Comment by tracywalker** [comment]
There are a few test case that are are not working correctly on my non-retina mac.  Specifically any of the test cases attempting to clear history.  I am investigating it now.  I's probably a simple fix.  I'll create a new branch once I have figured out the solution here.
