### ISSUE TITLE
Fix the failing 'toolbars_window_controls' tests

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#1111]
The following tests did not pass:
about_firefox_controls
web_console_controls
web_developer_menu
drag_space
save_image_controls
browser_controls_upper_corner
sidebar_controls

**Comment by icrisan** [comment]
@tracywalker, fix can be found in branch "issue_1111". please review.
P.S: Had to disable the 'web_developer_menu.py' test case since the 'Developer Toolbar' has been removed from Firefox 62. See more details here https://developer.mozilla.org/en-US/docs/Tools/GCLI. Though I think that we can use it for versions smaller than 62. Please let me know your thoughts! Thank you!

**Comment by tracywalker** [comment]
This looks good except issue #1098. It is still failing on Linux.  I reopened that issue.

But code to fix the rest is good.
