### ISSUE TITLE
Fix click_auxiliary_window_control() function for non-retina MAC display

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1118]
There is a problem with click on the close button for non-retina display. 

This failure is intermittent because the function clicks every time on the first found button that appears on the screen. I think we can change the similarity for this type of pattern or i can create a region with that 3 control buttons and pick one based on the area in which they are.

**Comment by IonutBudeanu** [comment]
#808

**Comment by IonutBudeanu** [comment]
Related to #808

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1118.

Please review.

Thank You

**Comment by tracywalker** [comment]
code approved with some additional changes.
