### ISSUE TITLE
Enhance update tests

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1124]
These issues are not blocking basic update tests, but we should do them. These would be nice to have by Iris 1.0, but they may have to wait until later.

* On Linux only, two patterns were not found. I took new ones that seem to work.
```
background_restart_to_update_button
manual_restart_to_update_button.png
```
I kept the old ones in the repo, and renamed them with the suffix "_". We need to examine these images and find out what's different. I would take the new images above, crop them and see if that fixes the problem. Also, change the similarity for the pattern search. 

* There is a lot of noise in the stdout now, both from `mozdownload` and from Firefox itself while it is downloading the updates. Can this be suppressed?

* Should we disable these tests by default, in order to prevent people from running them accidentally? If so, we could just set `self.exclude = Platform.ALL` in each one, and then in our documentation, instruct people to use the `-o` flag when they run them.

* We need to write basic documentation on how to use update tests. This should provide sample command-line parameters, mention the rules in the config.ini file, and give a few scenarios for both beta and release.

**Comment by silviuFlorin** [comment]
@mwobensmith The noise in stdout is because of `self.set_profile_pref('app.update.log;true')`. Removing that will fix the problem. There is also some noise from mozversion library but didn't found a way to suppress that yet. I will further investigate the issue

We could exclude update tests if -t parameter is NOT provided (all tests are executed). We should assume that adding update tests names using -t or -d arguments is something the user wants and update tests should run in this situation. What do you think Matt?

**Comment by mwobensmith** [comment]
I would be OK with the Firefox noise in stdout if the user has set a debug level such as `-i DEBUG`. So perhaps we only set that pref if `app.args.info == 'DEBUG'` ? 

The rest of the output from `mozdownload` we may have to accept for now, unless you find a solution.

As far as disabling update tests, the workflow that makes sense to me is to
- Disable both tests.
- Specify `-o` when running them from the command line:

`iris -t manual_update -f 55.0b3 -o`

I would rather do that then add more logic to examine the `-t` or `-d` arguments. Seems easier, yes?

**Comment by silviuFlorin** [comment]
@mwobensmith OK regarding disabling tests and running them with -o argument. 
After a bit more investigation I realized that the culprit for the noise in stdout is the way our firefox subprocess is called. we should redirect the stdout and stderror to DEV NULL

**Comment by silviuFlorin** [comment]
@mwobensmith Branch issue_1124a is ready for review

**Comment by mwobensmith** [comment]
Everything here has been addressed and fixed. The only outstanding issue is documentation, which we will track in a separate issue.
