### ISSUE TITLE
Investigate update tests on different locales

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1128]
Along with #1124, there are things we need to do to improve the current update tests. We anticipate problems with localized builds due to various international keyboards, shortcuts, etc. and we will need to use this ticket to test and track what we find.

**Comment by silviuFlorin** [comment]
@mwobensmith Please review branch issue_1128_1208_1236_1237_1250
I was unable to set up the LINUX environment. I will create a new task just for LINUX.
