### ISSUE TITLE
Win7: bootstrap script hangs on launch

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#113]
When invoking the bootstrap.sh script, a new terminal window is spawned and the script starts to run. However, it displays the message about installing Scoop, and never progresses.

**Comment by mwobensmith** [comment]
This happens for me on Iris 1.0 as well, so I don't know if it's a real issue or just my Win 7 config.

**Comment by pavelciapa** [comment]
I have same issue on my win7 PC on Iris 1.0. Installing scoop, endlessly hangs

**Comment by rrobotin** [comment]
The error might be cause by an unsupported version of PoweShell. Please check the version ($PSVersionTable.PSVersion) . It should be "5"

**Comment by pavelciapa** [comment]
> 
> 
> The error might be cause by an unsupported version of PoweShell. Please check the version ($PSVersionTable.PSVersion) . It should be "5"

Tryed to update my home Win7 to $PSVersionTable.PSVersion: 5 (there was 2). It didn't succeeded. Will have to upgrade my laptop before using Iris at home :)
