### ISSUE TITLE
Provide support in update tests for developer edition

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1130]
Related to #1124, it appears that we've been asked to support Firefox Developer Edition for update tests. I don't know if we can do this already or if we need more work, but filing this Git issue to investigate.

**Comment by silviuFlorin** [comment]
@mwobensmith Using `FactoryScraper('daily', ...)` in our code will trigger the latest nightly build download with minimal code changes. Getting a specific nightly version based on date will imply some additional work. Do we want that as well?

**Comment by mwobensmith** [comment]
If the work for Nightly isn't too hard, then sure, let's do it. The main requirement for now is developer edition. It's based on beta, but I haven't investigated how different it is from the beta with regards to the download URL, channel name, etc.

**Comment by silviuFlorin** [comment]
@mwobensmith Currently mozdownload does not support dev edition. I have raised an issue on github and a PR has already been created: https://github.com/mozilla/mozdownload/pull/505
Hopefully we will have it merged soon

**Comment by silviuFlorin** [comment]
@mwobensmith In the mean time I could work on the implementation. The only think I need is a standard we should use for dev edition versions. Right now dev edition and beta have the same version format. 
We could use [version-dev] format. Is that OK with you?

**Comment by mwobensmith** [comment]
@silviuFlorin That sounds great.

**Comment by silviuFlorin** [comment]
@mwobensmith Branch issue_1130 is ready for review. For the update tests to pass for dev edition, additional patterns have to be taken as the themes are totally different. I will raise a new issue for that

**Comment by mwobensmith** [comment]
Code was checked in. @silviuFlorin will file a new issue to document `Pattern` creation for developer edition.
