### ISSUE TITLE
Fix one_off_searches_in_private_window test for Windows in order to fix the cron job

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1133]
For this test a private window is required and after the test is performed the private window is closing but the main firefox window remains in the background. 

That's why the teardown is not performed correctly, and Iris throws 'Firefox still around, aborting' error.

Please notice that this issue is reproducible 10 out of 10 times just on Windows platform.

**Comment by IonutBudeanu** [comment]
FIxed in branch issue_1133.

The actual problem was that Firefox does not close as expected. That's why I used the quit_firefox() function as a retry inside of confirm_firefox_quit() method. 

Putting the method inside the general confirm_firefox_quit() function was a good suggestion from Silviu. 

Please review.

Thank You

**Comment by tracywalker** [comment]
code approved with additional change to click the home button to improve chances a second attempt at quit will work.  

This also address issue #589.  

We have other issues open for further checks to address various dialogs that may appear at the end of a test case.
