### ISSUE TITLE
Add support to run Iris with different RTL builds

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#1164]
We need to add support to run Iris with different RTL builds in order to automate the following scenario https://testrail.stage.mozaws.net/index.php?/cases/view/117531 or any other similar scenarios.

**Comment by icrisan** [comment]
I think that we can automate these tests now but we cannot run them in the same run with the full suite(English). These tests should be run separated like the updates tests.

**Comment by tracywalker** [comment]
Yes, that is correct.  RTL builds are not generally compatible with Iris at this time. A separate test suite, much like we had to create for update tests would have to be created and only RTL specific tests run in it. Another solution is wait for Iris 2.0 and allow RTL Firefox tests to be developed as a distinct product.  We'll have to have this discussion at some point soon.

**Comment by mwobensmith** [comment]
Iris does support RTL builds. If there are specific areas where we need to adjust for text, alignment, placement, etc. we will file issues for each.
