### ISSUE TITLE
Investigate use of mozrunner

### ISSUE THREAD

**Issue by silviuFlorin** [mozilla/iris#1176]
Mozrunner provides an API to manage a gecko-based application. Mozrunner uses mozprocess to manage the underlying gecko process and handle output. It also handles the crash reporter.

We don't have to touch a lot of code and should be relatively easy to integrate it into Iris

More info here:
https://firefox-source-docs.mozilla.org/mozbase/mozrunner.html

@mwobensmith Do you think we should invest time in this?

**Comment by mwobensmith** [comment]
Absolutely! Thank you for finding this.

**Comment by silviuFlorin** [comment]
@mwobensmith I have a working example that needs some polish. I will have something for you to review as soon as possible

**Comment by silviuFlorin** [comment]
@mwobensmith Please review branch issue_1176. Running the entire suite with 2 monitors I found out that all tests fail. This is because of `_screenshot = mss.mss().grab(mss.mss().monitors[0])` from Platform module.
I figured out what the problem is and I will raise an issue to fix it. Also, this is the best moment to implement Screen Class. Do you agree with this?
