### ISSUE TITLE
OSX Bootstrap script needs to install virtualenv

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#1187]
After running osx_bootstrap.sh the instructions indicate running `virtualenv .` however on a fresh MacOS install this is not already installed. Running `sudo easy_install virtualenv` solves this. Not sure if this should be taken care of by bootstrap or as a documented dependency.

**Comment by AndreiH** [comment]
This is now resolved by https://github.com/mozilla/iris/issues/858.
We now use Pipenv to install all dependencies and requirements which uses also virtualenv. 
Thanks for opening this !
