### ISSUE TITLE
Investigate and fixes a few failing toolbars_window_controls tests cases on Mac non-retina 

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1191]
On non-retina MAC the following tests are failing due to the same error 'Can't find the "hamburger menu" in the page':

- drag_space

- title_bar_activation

- hamburger_menu_customize

- browser_controls_upper_corner

**Comment by tracywalker** [comment]
hmmm.  I was certain I fixed these last week.  But I don't see any record.  Anyway, the fix for this is to reduce the similarity in the wait call in general.py:

def click_hamburger_menu_option(option):
    hamburger_menu_pattern = NavBar.HAMBURGER_MENU
    try:
wait(hamburger_menu_pattern, 10)
