### ISSUE TITLE
[LINUX] Fix the "browser_controls_upper_corner" test case

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#1196]
The "browser_controls_upper_corner" test case still fails on LINUX.

**Comment by mwobensmith** [comment]
I see it failing on Windows as well.

**Comment by icrisan** [comment]
fix can be found in branch 'issue_1196'. @tracywalker please review.

**Comment by tracywalker** [comment]
sorry, this slipped off my radar.

code approved
