### ISSUE TITLE
Mac: Test export_bookmarks_to_html opens save dialog and never finishes

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1199]
The "save file" dialog remains open, and because the dialog (and bookmarks window) are covering the home button, the test fails but the browser never quits.

**Comment by tracywalker** [comment]
This works for me on Mac.  Why did the save dialog remain open? Did Iris not find the Pattern('save_button.png')?

**Comment by mwobensmith** [comment]
It does not find the "Save" button, and the assert fails. However, since the dialog is open, it can't quit. 

A few things:
* Enhancements to `confirm_firefox_quit` (#1172) would help here, by getting rid of the dialog and allowing it to quit, and proceed with the run. For example, if Iris pressed `Key.ESC` at the end, it would dismiss this dialog and give it another chance to quit.
* If I decrease the similarity of the `save` image to `.7`, it finds the button and the test passes.

**Comment by mwobensmith** [comment]
This is working now, closing issue.
