### ISSUE TITLE
Adjust locale support for all test cases

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1204]
We have authored test cases for Firefox `en-US` by default. However, a full run on another locale, such as `de`, will produce many failures due to pattern mismatch. We will also have issues with various keyboards specific to some locales.

The default set of locales that Iris supports is specified in `BaseTest`, within `test_case.py`. All tests  inherit from this class and have this list of locales to support:

`en-US, zh-CN, es-ES, de, fr, ru, ar, ko, pt-PT, vi, pl, tr, ro, ja`

If a test case does NOT work on a specific locale above, because it has not been authored to do so, that locale should be removed from the test case so that it never runs there.

Some potential ways to address:
* In each test case, within its init method, set the locale list to `en-US` only:
`self.locales = ['en-US']`
Then, run each test case with a different locale to see if the test works. If it does, add its locale to this list.

* Another option instead: do a full run of Iris as-is, on another locale, and record the failures. Make sure you run once more against `en-US` for a baseline. Diff the results to find out which tests are failing because of the locale, and compare against a list of all tests in Iris. Then, update only the successful tests to include the locale that you just ran.

I'm sure you can come up with other ways to do this, but you get the picture.

**Comment by mwobensmith** [comment]
We've decided option #1 - edit all test cases and add this line to the init method:

`self.locales = ['en-US']`

**Comment by IonutBudeanu** [comment]
In the awesomebar suite we have 4 tests that works with almost every locale that we have without any change. Please take a look at the issue_1204_awesomebar branch.

On the bookmark suite side the tests passes only on 'en-US' locale. We need to adjust the patterns for each locale that we have. For more details you can take a look over the issue_1204_bookmark branch.

Thank You

**Comment by tracywalker** [comment]
This issue is now simply about adding the self.locales = ['en-US'] line to all test cases.  In the future, we can add support for other locales on a case by case basis as requests come in.

**Comment by tracywalker** [comment]
ja-JP-mac should be taken care of by iris such that "ja" in test case will work.  Matt knows this isn't quite the case currently.  However he will fix it.  So I am going fix the test cases where you have Mac specific code around ja-JP-mac then check-in each of your branches completed thus far.
