### ISSUE TITLE
Update Iris documentation

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1222]
This is a meta issue to capture our documentation needs before launch.

* Readme (issue #1223)
* Welcome page for new contributors (issue #1224)

* Installation (issue #1225)
	* Platform setup
	* Setting up PyCharm IDE
	* Installing and using Sikuli (optional)
	* Debugging a failed Iris install

* Running Iris (issue #1226)
	* Control center
	* Viewing the results of your run
	* Runtime argument list (update)
	* How to run update tests

* Creating your first test (issue #1227)
	* Choosing a test
	* Developer requirements (platforms, etc.)
	* Creating images and Patterns (capture, tools, format, location)
	* Iris test case APIs (overview, core, helper) (issue #1228)

* Code style guide (issue #1229)
	* file names
	* URLs should have protocol
	* PEP 8
	* Other conventions

* [Workflow](https://github.com/mozilla/iris/wiki/Iris-Git-workflow) (issue #1230)
	* commit messages, branch names
	* The revision process (pending rewrite)
	* Communicating with the Iris team

* Code submission guidelines (issue #1231)
* Merge process and Sheriff process (review for accuracy) (issue #1232)

**Comment by tracywalker** [comment]
We've done everything here we're going to do for 1.0.  Documentation will be an ongoing team wide task from now on.
