### ISSUE TITLE
Create improved documentation for running Iris.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1226]
With Control Center coming on line and with a plethora of command line arguments available, we need better documentation outlining the various methods and differences for running Iris. From how to use the Control center, viewing the results of your run, run time argument list to how to run update tests.

**Comment by mwobensmith** [comment]
I am covering all of this except update tests.

@silviuFlorin I'd like you to write the instructions for update tests, including how to edit the config file, what parameters to use, etc. I can edit this and put into the final wiki.

**Comment by silviuFlorin** [comment]
@mwobensmith I sent you an invitation for the [update tests doc](https://docs.google.com/document/d/1j6m0BzUxy0dsb_4PgfX9vC_ewOJK5cX79WTKl6C4UBI/edit)

**Comment by mwobensmith** [comment]
@silviuFlorin This is great! I edited it a bit to match the style of the other docs on our wiki, and it is now [live](https://github.com/mozilla/iris/wiki/Update-Tests). Please take a look and let me know if there are any issues.
