### ISSUE TITLE
Document our API's

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1228]
We should develop and implement good inline and external documentation of our test case helper functions.  

Determine if PEP8 comment practices are compatible with code scrappers that can create external documentation.

**Comment by tracywalker** [comment]
Discussed this, at length with Matt. We decided this issue should represent only work needed to document our test case facing API's. That is anything that can be called by a test case should be covered.  Code that is used only by Iris core is not to be addressed by this issue.  

Matt made an effort to make sure  pure "core" functions are prefixed with an "_" So that should help in the distinction.

**Comment by icrisan** [comment]
Branch 'issue_1228" is ready for review. @mwobensmith and/or @tracywalker please review. Thank you!

**Comment by tracywalker** [comment]
Ioana, I decided on Doxygen.  It has a good GUI that generates nice documentation.  I've noticed though that it correctly ignores comments after '#'  Triple quote block comments are picked up and presented nicely by Doxygen.

I think you may want to go back through your work and check to make sure anything commented with # really is something you don't want to be picked up for public documentation.  Basically, # comment blocks are meant to be developer notes.

**Comment by icrisan** [comment]
I replaced all the # comment blocks with """ comment blocks for:
- helper descriptions
- parameters definition.
If needed I can update also helper's internal # comments.

**Comment by tracywalker** [comment]
The # comments are meant for developer notes and such.  If the comment isn't basic information about how to use the fucntion/class etc.  then leave them as #, dev comments
