### ISSUE TITLE
Update to Tesseract 4 when stable version is available

### ISSUE THREAD

**Issue by AndreiH** [mozilla/iris#1243]
Releases: https://github.com/tesseract-ocr/tesseract/releases

Tesseract 4 adds a new OCR engine based on LSTM neural networks. The new version is faster and more accurate than version 3. The drawback is that it is still beta-level software.

These slides explain the changes in more detail: https://github.com/tesseract-ocr/docs/blob/master/das_tutorial2016/6ModernizationEfforts.pdf

**Comment by AndreiH** [comment]
We are going to wait for a more stable version @wizofe . It's currently in Release Candidate 4 :+1:

**Comment by wizofe** [comment]
It totally makes sense you want the stable to come out @AndreiH 🆗

**Comment by AndreiH** [comment]
Tesseract 4.0 Stable version is out: https://github.com/tesseract-ocr/tesseract/releases

**Comment by mwobensmith** [comment]
For the short-term, we can probably just get the latest library into our project. For the longer-term, we will enhance our APIs to take better advantage of what Tesseract offers.

**Comment by AndreiH** [comment]
@mwobensmith This is ready for review in PR https://github.com/mozilla/iris/pull/1456
I have tested on Tesseract v4 on all environments and it's working fine. Test suite passed without fails.
@tracywalker can you also give it another try on Win 10 ? 
Thanks !

**Comment by tracywalker** [comment]
Looks fine on Win 10.
