### ISSUE TITLE
Enhance email report system to include title for non-retina OSX and Windows 7

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1251]
At this moment the email report title describes only on which platform Iris was run without details like which type of MAC `Retina or non-retina display` or which type of `Windows` `7 or 10`. 

For example right now we're receiving the results from a `Windows` run like this:

`[Firefox 63.0][Win]Iris Test Report 2018-10-02`

Now we need to know on which `Windows` the tests were run like in the above example:

`[Firefox 63.0][Win7]Iris Test Report 2018-10-02` or `[Firefox 63.0][Win10]Iris Test Report 2018-10-02`

On `osx` platform we are receiving this title `[Firefox 63.0][Osx]Iris Test Report 2018-10-04` but we need to add support in order to receive a specific title for non-retina MAC display like that: 

`[Firefox 63.0][Osx-Non-Retina]Iris Test Report 2018-10-04`

**Comment by mariusandreifilip** [comment]
Issue fixed by Ionut Budeanu and merged in dev
Email Example:
[Firefox 64.0][Osx_non_retina]Iris Test Report 2018-10-29
[Firefox 64.0][Win7]Iris Test Report 2018-10-29

Closing ticket as done.
