### ISSUE TITLE
Unwanted output for 'which' command

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1285]
I think this was fallout from #1244 and some new logic in `__main__.py` to check for Tesseract. We should diagnose the problem and prevent this extra debug output.

Mac:
`usage: which [-as] program ...`

Windows:
`"which" is not recognized as an internal or external command`

**Comment by AndreiH** [comment]
Thanks for catching this ! It seems this was only happening on Mac.
I now changed the way we search for tesseract, we no longer have hard-coded paths, except for Windows if the user installs tesseract manually.
If the user install tesseract by Scoop -Windows, Brew- Mac, apt-get - Linux, then the `which command` is very helpful.

**Comment by AndreiH** [comment]
This is ready for review on branch `issue_1285` https://github.com/mozilla/iris/commit/fe9ee23df0743385549cefebc5577a507e5b2e7e
