### ISSUE TITLE
Declare BaseTest class variables inside __init__

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1292]
In order to help our API documentation process in #1228, we should clean up `test_case.py` and its `BaseTest` class by a) declaring variables in its `__init__` method, and b) removing the call to `reset_variables` if it's no longer needed.

**Comment by silviuFlorin** [comment]
@mwobensmith Please review branch issue_1292.

**Comment by mwobensmith** [comment]
Needs to be rebased, but otherwise approved.
