### ISSUE TITLE
Pipenv fails to run on Win7

### ISSUE THREAD

**Issue by AndreiH** [mozilla/iris#1305]
Recently we are testing Iris on Win7, and we have experienced some issues, where Iris cannot run.
It fails to find and load the `cv2` library, even though it is installed and present in the Virtual Env.
We tested this on different clean Machines with Win7.

An issue will be opened on Pipenv side also. 
Until that gets fixed, we need to reintroduce the previous solution where we are installing all the requirements. We will have both solutions.

That means we have to repopulate `setup.py` with project requirements.

**Comment by AndreiH** [comment]
The issue:  https://github.com/skvark/opencv-python/issues/114

**Comment by nufina** [comment]
Hi, @AndreiH

I have cloned iris but I have a problem with 'sh'. Can you help me?

"sh" is not recognized as an internal or external command, operable program or batch file.

What I should do to solve this problem?

**Comment by nufina** [comment]
What does that mean? Can you explain? What's wrong with this instruction [https://github.com/mozilla/iris/wiki/Setup](url) ?

**Comment by nufina** [comment]
I have solved the 'sh' problem using Git Bash and corrected '\' with '/' in 'sh bootstrap\bootstrap.sh'. But I don't know it is correct way or not.

**Comment by mwobensmith** [comment]
@nufina This issue is being used to track a specific bug. 

If you have support questions, please follow the [instructions on the wiki for setup](https://github.com/mozilla/iris/wiki/Setup). If you are still having problems after that, get in touch with us on our [IRC channel](https://kiwiirc.com/client/irc.mozilla.org:6697/iris).

**Comment by ffelder** [comment]
Hello .  I have managed to  launch iris   on window 7   by using the link from AndreiH  by  installing pip install opencv-python==3.4.1.15  as suggested in the link , but in the installation instructions the last command is iris and I had to use  pipenv run iris to launch iris instead of just iris. Thanks.

**Comment by mwobensmith** [comment]
Hi @ffelder Glad you got it installed. The commands `pipenv install` and `pipenv shell` should have been enough. At that point, you would be in the shell environment and you should be able to just type `iris`. Are you saying that, even after you typed those two commands, the simple `iris` command didn't work?

**Comment by ffelder** [comment]
Hi @mwobensmith  . The  iris  command alone did not work , although I think I was using git bash terminal  and not the command prompt (   I don't know if that could make a difference) .

**Comment by mwobensmith** [comment]
@ffeider Thanks for the info, interesting. In our instructions, we just mention "terminal" but perhaps we should be more precise, if it ends up making a difference.

**Comment by ffelder** [comment]
Thanks . I  may try later on again with windows 7 . I'm running iris on Linux  now where is fast and smooth ,  on windows 7  previously when interacting , clicking one of the test and  the button go  sometimes   it was very slow to get going and sometimes getting stuck  , maybe I didn't install iris properly  as it was before the updated  wiki instructions.

**Comment by mwobensmith** [comment]
Fixed in latest master.
