### ISSUE TITLE
Check for default Firefox install before launching the control center

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1308]
We open the control center without ever verifying that the user has installed Firefox. We should have a check to make sure that we find a local Firefox install, and exit with a meaningful error message if we can't find it.

**Comment by wizofe** [comment]
@mwobensmith would you think that as part of the `bootstrap` process or the Control Center pre-launch?

**Comment by mwobensmith** [comment]
@wizofe Ideally it is handled in the bootstrap script. In fact, we do this on Linux. However, the current code assumes a local Firefox install already exists, which is not correct. I am going to check that the paths exist before trying to open Firefox, at the very least. 

I am also thinking that the current logic only checks for Firefox release version. The other versions of Firefox like Nightly, etc. may have different paths and I should probably check those also.

**Comment by wizofe** [comment]
I can confirm that Developers has a different path and that was the reason in my case that the script didn't execute.

If you want I can develop a PR for the `bootstrap` script ;)

**Comment by mwobensmith** [comment]
@wizofe I would rather handle it myself and not put it in the bootstrap. I don't want to force users to use a specific version of Firefox, because we can support release, beta or Nightly. The Firefox instance used for the control center is not the same Firefox build that is used to run the Iris tests.
