### ISSUE TITLE
Document our core classes

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#1322]
The following core files should have their APIs documented.

api/core/util/color.py
api/core/environment.py
api/core/key.py
api/core/local_web.py
api/core/location.py
api/core/match.py
api/core/mouse.py
api/core/pattern.py
api/core/platform.py
api/core/region.py
api/core/screen.py

api/core/profile.py
The private class "_IrisProfile" is used to create the public class "Profile". Therefore, we should document the properties declared in "_IrisProfile" as if they were part of "Profile". This includes BRAND_NEW, LIKE_NEW, TEN_BOOKMARKS and DEFAULT. Everything else here is to be considered internal and not documented.

api/core/settings.py
As above, the private class "_IrisSettings" is used to create public class "Settings". We should document the static properties and methods of this class as part of Settings, e.g. Settings.wait_scan_rate, Settings.LOCALES, Settings.is_windows(), etc.

**Comment by icrisan** [comment]
Finished documenting our core classes pointed in this issue(except api/core/util/color.py API). @mwobensmith please review branch 'issue_1322'. Thank you!

**Comment by mwobensmith** [comment]
> Talked with Silviu and he told me that api/core/util/color.py API will be no longer applicable after issue #1125 gets implemented. @mwobensmith it is ok if I'll not document this API? Thank you.

I'll go with what @silviuFlorin says. :D
