### ISSUE TITLE
Pyobjc package introduces more packages `pyobjc-framework-*`, when running `pipenv` from Windows

### ISSUE THREAD

**Issue by AndreiH** [mozilla/iris#1325]
If you check the `Pipfle`, you will see that we have specified some "Platform dependencies" packages, `pyobjc` and `xlib` at the beginning.
When using `pipenv install` the packages specified in `Pipfile` may add in `Pipfile.lock` other packages that they may depend on. For example in `Pipfile` we have only specified `mozrunner`, but `mozrunner` also depends on `mozprofile`, and it is automatically installed and put in `Pipenv.lock` as a dependency to `mozrunner`.
So, `pyobjc` and `pyobjc-core`, does the same, they bring other dependencies with them : https://github.com/mozilla/iris/blob/master/Pipfile

So, because they are Platform dependency, which means we want to install that only on OSX, `Pipenv` does not know to add `platform_system = "== 'Darwin'"` to other packages that are automatically added to Pipfile.lock because `pyobjc` and `pyobjc-core` depend on them. And we forcefully add them manually in `Pipfile` to let pipenv know that they only should be installed on OSX.

Another thing is that the list keeps getting bigger and bigger, and it slows down the `pipenv install` process.

I would like to open an issue on Pipenv side, and also maybe we can move the OSX Platform dependencies `pyobjc` and `pyobjc-core` back to OSX bootstrap.

**Comment by AndreiH** [comment]
@mwobensmith let me know what are your thoughts on this issue. Thanks!

**Comment by AndreiH** [comment]
Opened an issue on their side: https://github.com/pypa/pipenv/issues/3063

**Comment by AndreiH** [comment]
I opened an issue on their side: https://github.com/pypa/pipenv/issues/3063

**Comment by mwobensmith** [comment]
@AndreiH I'm trying to understand the risk/reward here.

The issue now is that we install libraries that are not intended for that platform, and it is making the installation slower. Is that correct?

If that is so, this appears to be a fairly minor issue. If there is a functional problem, or a risk of a regression, that would concern me more.

**Comment by AndreiH** [comment]
I guess we can also close this as we no longer have `Pyobjc` library in our Pipefile (Related to: https://github.com/mozilla/iris/issues/1320)
I will also keep an eye out when this `pipenv` BUG is fixed.
