### ISSUE TITLE
Investigate and fixes a few failing tests on all the platforms

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1326]
I ran all the tests on issue_1309 branch which includes all the fixes for windows but it seems that on Linux we have different problems.

The following tests did not pass:

- change_search_engine_positions
- key_navigation_high_contrast_theme
- one_off_searches_in_private_window
- remove_checks_from_search_engines
- search_in_new_tab_using_one_off_context_menu
- bookmarks_toolbar_sorted_by_name
- remove_tags_from_a_bookmark
- history_menu
- history_sidebar
- history_sidebar_delete_site_verify_if_remembered
- history_sidebar_dismiss_search
- history_sidebar_forget_site_verify_if_remembered
- history_sidebar_open_all_in_tabs
- history_sidebar_sort_by_date
- history_sidebar_sort_by_last_visited
- history_sidebar_sort_by_most_visited
- history_sidebar_sort_by_site
- open_site_in_private_window
- confirm_close_multiple_tabs_controls
- firefox_build_apis

**Comment by tracywalker** [comment]
The following are all fixed as part of issue #1309
- change_search_engine_positions
- key_navigation_high_contrast_theme
- one_off_searches_in_private_window
- remove_checks_from_search_engines
- search_in_new_tab_using_one_off_context_menu

**Comment by IonutBudeanu** [comment]
These tests are part of another issue and will be fixed on a separate branch:

- history_menu
- history_sidebar
- history_sidebar_delete_site_verify_if_remembered
- history_sidebar_dismiss_search
- history_sidebar_forget_site_verify_if_remembered
- history_sidebar_open_all_in_tabs
- history_sidebar_sort_by_date
- history_sidebar_sort_by_last_visited
- history_sidebar_sort_by_most_visited
- history_sidebar_sort_by_site
