### ISSUE TITLE
Develop test case: The removal of a bookmarks folder can be undone.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#133]
https://testrail.stage.mozaws.net/index.php?/cases/view/4157

**Comment by IonutBudeanu** [comment]
Fixed in issue_133 branch.

The test will be disabled due to [https://bugzilla.mozilla.org/show_bug.cgi?id=1385754](url)

Please review.

Thank You

**Comment by tracywalker** [comment]
code approved

note: I  will remove the delay before the drag_drop() call.  I fixed that directly in drag_drop() via issue #1031
