### ISSUE TITLE
Fix remaining failures for all the platforms 

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1358]
After a general fix integrated with branch issue_1326 we can notice that we still have some failures.

Some of these failures are expected and i'll fix them right away but we have some weird failures on MAC. I'll investigate and i'll try to fix all of them.

The following tests did not pass:

MAC:

- bookmarks_toolbar_open_all_in_tabs
- history_sidebar_delete_site_verify_if_remembered
- history_sidebar_forget_site
- history_sidebar_forget_site_verify_if_remembered
- history_sidebar_open_site
- history_sidebar_open_site_context_menu
- history_sidebar_open_site_in_new_tab
- history_sidebar_open_site_in_new_window
- history_sidebar_open_site_in_private_window 

Linux:

- telemetry_data_collected_for_one_offs_from_new_tab
- bookmark_link_via_context_menu

Windows 10:

- search_engine_can_be_added
- search_using_one_offs_while_maximizing_or_minimizing_window
- telemetry_data_collected_for_one_offs_from_new_tab
- bookmark_link_via_context_menu
- remove_tags_from_a_bookmark
- clear_recent_history_predefined_time_range
- browser_controls_upper_corner
- drag_space
- sidebar_controls
- zoom_controls_on_toolbar

Windows 7:

- search_engine_can_be_added
- telemetry_data_collected_for_one_offs_from_new_tab
- bookmark_link_via_context_menu
- export_bookmarks_to_html
- clear_all_history
- clear_recent_history_no_selections
- clear_recent_history_predefined_time_range
- clear_recent_history_window
- history_sidebar_dismiss_search
- history_sidebar_search_available_site
- history_sidebar_search_unavailable_site
- sidebar_controls

Please consider that on Win 7 the following failures are expected and the cause is known as a keyboard shortcut issue that will be fixed in a separate branch:

- clear_all_history
- clear_recent_history_no_selections
- clear_recent_history_predefined_time_range
- clear_recent_history_window

**Comment by IonutBudeanu** [comment]
Fixed tests for MAC, Linux and Win 10.

In progress on Win 7.

For MAC, Linux and Win 10 we have a full pass.

**Comment by IonutBudeanu** [comment]
Fixed Win 7 tests and also fix a fake error from click_auxiliary_window_control() function. 

Basically I changed an else statement into an elif statement because initially we enforced the block to be executed and even Windows was not part of the logic we received `'Can\'t find the auxiliary window controls, aborting.'` instead of `Unable to find image...` error from `click(close_button_pattern).` It seems that including an `if` statement inside of a final `else` statement is a bad practice in Python.

So instead of this block of code:

    else:
         if Settings.get_os() == Platform.LINUX:
             hover(Location(80, 0))

from now on we are using this form:

    elif Settings.get_os() == Platform.LINUX:
             hover(Location(80, 0))

**Comment by IonutBudeanu** [comment]
Please review.

Thank You

**Comment by tracywalker** [comment]
Added an additional fix for add_links_keyboard_shortcuts.py

code approved

**Comment by tracywalker** [comment]
If there are any lingering test cases failing. We'll address those in new post 1.0 issues.
