### ISSUE TITLE
Duplicate cd command in Wiki's Setup page

### ISSUE THREAD

**Issue by romanrodriguez** [mozilla/iris#1362]
There is a duplicate command one after the other between steps 2 and 3 in Mac Instructions. `cd iris` and `cd ~/iris`. To streamline instructions across systems, I would delete the `cd ~/iris` and add `cd  ~` at the beginning before `git clone`, as in the Linux instructions.

**Comment by mwobensmith** [comment]
@romanrodriguez Thanks! Fixed now. Much appreciated.
