### ISSUE TITLE
Test runs no longer maximize Firefox window for each test on OSX

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1368]
At least on my macMini with large non-retina screen,  Firefox is not being maximized prior to running each test case.  Currently, the browser opens a quit large size, actually filling screen vertically.  but there are a few inches on the right side of the screen which allow the desktop to be in view.  This behavior isn't causing tests to fail, as far as I can tell. However,  Iris should be performing maximize as expected for each test.

**Comment by tracywalker** [comment]
This bug is causing web_console_controls to fail because pattern match is looking at a tooltip over a background (desktop) instead of white background (browser)

**Comment by mwobensmith** [comment]
Seems OK for me on latest dev, Mac Retina. I wonder if this affects other platforms.

**Comment by tracywalker** [comment]
This is still broken for me on dev with non-retina Mac.  Works as expected on Linux.  Investigation in DEBUG mode shows that the pattern for maximized_browser.png IS found.  So I looked up what that image is.  It's just a screen shot of the controls in relation to the Apple icon and Firefox menu item.  In my case, the browser is opening with upper left corner of the  window all the way to upper left corner of the screen but not as a full window.  This is tricking Iris into thinking the browser is full screen.

We need to make this check robust enough to tell if the browser is full screen or not no matter where the window opens at startup.  I'll investigate further and provide a fix here.

**Comment by mwobensmith** [comment]
One thing that might help is to use the Iris logo in the test page to determine maximum horizontal/vertical position. I believe that's the reason we decided to put that logo in the lower right corner in the first place.

**Comment by tracywalker** [comment]
Yeah, there is no way to reliably check window max using the Mac window controls.  How would one compare the location of the Iris logo with actual screen size?

**Comment by tracywalker** [comment]
I'm going to resize the window on Mac then call maximize_window().  This will reliably ensure Fx window is max screen size no matter where the window appears on launch or where it is in any test case.
