### ISSUE TITLE
UI mock-up contribution for outreachy contribution

### ISSUE THREAD

**Issue by ffelder** [mozilla/iris#1370]
This contribution is due Tomorrow . I have already sent an email  to the mentor with a pdf of the mock up but it seems I have to contribute here to be able to get a link for the application . I will try to attach the pdf here  too. It has been fun to participate in this project.
[Iris mock.pdf](https://github.com/mozilla/iris/files/2525277/Iris.mock.pdf)

**Comment by mwobensmith** [comment]
I received your email, thank you. Closing this git issue.
