### ISSUE TITLE
pipenv fails with ImportError on Win10

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1384]
At the end of running bootstrap.sh I get the following:

 --->  installing/upgrading pipenv

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\pipenv.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\pipenv\__init__.py", line 23, in <module>
    from .cli import cli
  File "c:\python27\lib\site-packages\pipenv\cli.py", line 26, in <module>
    from .utils import is_valid_url
  File "c:\python27\lib\site-packages\pipenv\utils.py", line 59, in <module>
    from .vendor.requirementslib import Requirement
  File "c:\python27\lib\site-packages\pipenv\vendor\requirementslib\__init__.py", line 6, in <module>
    from .models import Requirement, Lockfile, Pipfile
  File "c:\python27\lib\site-packages\pipenv\vendor\requirementslib\models\__init__.py", line 8, in <module>
    from .requirements import Requirement
  File "c:\python27\lib\site-packages\pipenv\vendor\requirementslib\models\requirements.py", line 15, in <module>
    from .markers import PipenvMarkers
  File "c:\python27\lib\site-packages\pipenv\vendor\requirementslib\models\markers.py", line 6, in <module>
    from .utils import validate_markers, filter_none
  File "c:\python27\lib\site-packages\pipenv\vendor\requirementslib\models\utils.py", line 9, in <module>
    from .._compat import Link
  File "c:\python27\lib\site-packages\pipenv\vendor\requirementslib\_compat.py", line 55, in <module>
    Command = do_import("basecommand", "Command")
  File "c:\python27\lib\site-packages\pipenv\vendor\requirementslib\_compat.py", line 35, in do_import
    _tmp = importlib.import_module(pip9)
  File "c:\python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named basecommand
Requirement already satisfied: pipenv in c:\python27\lib\site-packages (2018.6.25)
Requirement already satisfied: setuptools>=36.2.1 in c:\python27\lib\site-packages (from pipenv) (40.4.3)
Requirement already satisfied: certifi in c:\python27\lib\site-packages (from pipenv) (2018.8.24)
Requirement already satisfied: virtualenv in c:\python27\lib\site-packages (from pipenv) (15.1.0)
Requirement already satisfied: pip>=9.0.1 in c:\python27\lib\site-packages (from pipenv) (18.1)
Requirement already satisfied: virtualenv-clone>=0.2.5 in c:\python27\lib\site-packages (from pipenv) (0.3.0)

The traceback above also occurs trying to run pipenv install

**Comment by AndreiH** [comment]
From the looks of it the bootstrap did not run correctly from the beginning. The setup was not done as it should, because your default Python PATH is still `C:\python27`. The bootstrap should overwrite that path and change it to `C:\Users\AH\scoop\shims\python.EXE`

I just tested on on Win10 VM with Python manually installed in `C:\python27` and then run the bootstrap and it installed scoop correctly and overwritten the PATH.

In order to figure out what is wrong here I need more details of the steps you did so I can replicate this.

But, for now I suggest making sure that the Bootstrap finished and installed everything correctly. 
Please run the bootstrap again, try even "Run as administrator" when opening the terminal in which you run it, maybe you had something blocking the change of PATH.

**Comment by AndreiH** [comment]
Another thing that you should definitely do, is to Manually uninstall Python from the Apps in your Win10.
And the run the Bootstrap again.
That should leave only one version of Python on your system and it should solve this problem.

**Comment by tracywalker** [comment]
I uninstalled Win10 python.  Still didn't work.  uninstalled scoop python then ran the bootstrap and all seemed to go well.  However,  when I try pipenv install I get:
Fatal error in launcher: Unable to create process using '"c:\python\python.exe" " C:\Python27\Scripts\pipenv.exe" install

which python: 
/c/Users/Lenovo L520/scoop/shims/python

**Comment by AndreiH** [comment]
I want to make it clear that the bootstrap script is not a script to resolve the errors/conflicts on our Platforms, it only installs all dependencies needed to run Iris.

It seems that it still recognizes Python as being in `C:\Python` and `C:\Python\Scripts`.
Please make sure that these paths are also not present in the System Variables:
`My Computer > Properties > Advanced System Settings > Environment Variables`
Make sure they are not in both Paths from `User variables` or `System variables`.

**Comment by tracywalker** [comment]
I cleaned up the paths and then just ran into more issues.  I need to repurpose this machine for Win7.  So I bought a new Win10 machine. Then did a fresh install of Iris following the wiki instructions. The following is what I ran into:  

1) git is not there.  It must be installed. So I went to (https://gitforwindows.org) and follow defaults during install process.

2) each time the bootstrap.sh asks you to restart the terminal…wait for it to quit first, then shut down the Command Prompt as well.  Start Command Prompt up to run the bootstrap again.   

I was running from Command Prompt. which opens a gitbash shell.  I think you have to shutdown the command prompt between each bootstrap run too. Somewhere in there I lost track of restarts required because if you don't restart the CP, bootstrap.sh appears to just repeat what it did before.

Anyway, eventually restarting the Command Prompt and running .\bootstrap.sh (3 times?) worked.  pipenv install worked and all is good.  Except tesseract failure in test case that calls for text search. (see issue #1398).

**Comment by AndreiH** [comment]
@tracywalker Good that this works now.
Please see aslo my comment here: https://github.com/mozilla/iris/issues/1395#issuecomment-435286724
Maybe you run in in the same issues.

**Comment by tracywalker** [comment]
Well, it *mostly* works.  Any test case that tries to do a text search (tesseract ocr) fails.
