### ISSUE TITLE
bootstrap.sh on Windows 10 does not install pipenv

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#1395]
Following the steps on a Windows 10 setup, bootstrap.sh is failing to install pip.

Here is the output from running the bootstrap.sh script:
```---> Installing Python 2.7 #####
---> Skipping Python 2.7 install. Already installed.
---> installing/upgrading pipenv
C:\Users\antho\iris\bootstrap.sh/win_bootstrap.sh: line 57: pipenv: command not found
pip : The term 'pip' is not recognized as the name of the cmdlet, function, script file, 
or operating program. Check the spelling of the name, or if a path was included, verify 
that the path is correct and try again.
At line:1 char:1
+ pip install pipenv
+ ~~~~
     + CategoryInfo          : ObjectNotFound (pip:String) [], CommandNotFoundException
     + FullyQualifiedErrorId : CommandNotFoundException
```
The terminal window closes at this point.

**Comment by mwobensmith** [comment]
I think it's actually not installing `pip`, but I'll leave it to @AndreiH to figure out.

**Comment by AndreiH** [comment]
I have again tested the bootstrap and the Setup steps on a clean Win 10 VM. And I have successfully managed to install the project.
Terminal needs to be restarted twice when prompted:
1st: After Scoop package management is installed - so the scoop commands to be recognized.
2nd: After Python is installed - so pip and python commands to be recognized.

I have managed to reproduce the exact same error by not restarting the terminal the second time:
![screenshot from 2018-11-01 10-16-48](https://user-images.githubusercontent.com/2787766/47841073-1248fd00-ddc1-11e8-89cb-1fccd00a484e.png)

@ashughes1 have you restarted the terminal from where you ran the bootstrap twice as prompted ?

Also, just for my information, did you had Python manually installed before running the bootstrap ? And also the PATH setup with: `C:\python27` and `C:\python27\scripts` ?

**Comment by ashughes1** [comment]
Yes this works now. I had not restarted the terminal a second time although I don't recall being prompted to restart it like the first time. It would be great if the script could just do this on its own or if not, making the prompting a bit more prominent.

Closing since this is more or less resolved. Let me know if you want me to open a UX bug on the bootstrap process.

**Comment by AndreiH** [comment]
@ashughes1, I want to explain this more thoroughly.
As this is a bash script, it requires to have Git Bash installed, and as we execute the script from another terminal, like CMD or Powershell, the Git bash terminal will separately open and run the script.

It indeed does exactly that, it prompts the user in red text that `Scoop package management installed. You need to restart the terminal and run the bootstrap.sh again.` the first time, waits 20 seconds and then restarts the Git Bash. And the same happens with Python the second time.

And you have to restart also the terminal in which you run the bootstrap (CMD or Powershell)
This has a small issue, that if you don't look at the screen in those 20 seconds you don't know about this.

@mwobensmith , Indeed I would suggest that we have in the setup instructions a small requirement, that the script is better to be run directly with Git Bash. The good part of this, is that the user can also go to `iris/bootstrap` and double click on the script. It will automatically run with Git Bash.

**Comment by mwobensmith** [comment]
@AndreiH thanks for the explanation. I think our instructions are missing a crucial step with regards to Git bash, so I will have them updated to explain this. 

> And you have to restart also the terminal in which you run the bootstrap (CMD or Powershell)
> This has a small issue, that if you don't look at the screen in those 20 seconds you don't know about this.

This could easily happen for people, so this is why we will need to explicitly give instructions that are 100% foolproof.

**Comment by ashughes1** [comment]
Just following up to confirm that this is now fixed on my end. Thank you very much @AndreiH!
