### ISSUE TITLE
Remove OCR search from an awesomebar test and add an pattern search

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1398]
The search_using_one_offs_while_maximizing_or_minimizing_window() fails especially on linux because the last assertion contains an OCR search.

Please replace the OCR search with a Pattern search.

**Comment by IonutBudeanu** [comment]
Fixed in branch_1398.

Please review.

Thank You

**Comment by silviuFlorin** [comment]
Code approved

**Comment by tracywalker** [comment]
Line 69 still has a text search. This breaks iris test run if it runs this test (search_using_one_offs_while_maximizing_or_minimizing_window())

On a fresh install of Windows10 and Iris I am seeing errors in Tesseract. 
failed adding ‘eng’
Could not load any languages! 
Could not initialize tesseract.
