### ISSUE TITLE
Fix intermittent failure on Win for drag_space test

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1401]
At some point inside the test the window is minimised and for that on Windows is necessarily that minimize_window() to be executed twice due to fact that first time the window is shrink and second time is minimised inside the taskbar.

Between these 2 actions we need to have a time sleep because inside of a full iris run everything happens very fast and the second minimize_window() has no time to be performed.

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1401

Please review.

Thank You

**Comment by tracywalker** [comment]
code approved
