### ISSUE TITLE
Fix key_navigation_high_contrast_theme and clear_recent_history_predefined_time_range tests

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1407]
On `key_navigation_high_contrast_theme` test I need to change a pattern due to some UI changes and for `clear_recent_history_predefined_time_range` I need to change a pattern in order to be more general and in this way we can avoid future problems regarding time elapsing.

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1407

Please review.

Thank You

**Comment by silviuFlorin** [comment]
Code approved
