### ISSUE TITLE
Develop test case: The Bookmarks Toolbar can be enabled from the Bookmarks Menu.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#141]
https://testrail.stage.mozaws.net/index.php?/cases/view/4089

**Comment by tracywalker** [comment]
Ionut, please put a PR request to dev for branch ionut/bookmarks_#141-143-145-147-149-152.

Also in your PR request description please put "fixes #141, fixes #143, fixes #145, fixes #147, fixes #149 and fixes #152"

Thank you

**Comment by IonutBudeanu** [comment]
Ok, thanks for the info Tracy.
