### ISSUE TITLE
libpng warning on Linux and Mac

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1416]
On start of Iris:

`libpng warning: sBIT: invalid`

Doesn't seem to affect Iris, but let's debug further.

**Comment by mwobensmith** [comment]
Also, seems like a regression from this past week, not present in previous master.

**Comment by wizofe** [comment]
May that be: https://stackoverflow.com/questions/36855143/how-to-resolve-this-error-in-android-studio ?

**Comment by mwobensmith** [comment]
I think this is an indication of some bad PNGs in our code base. Some sleuthing would turn up which ones are the problem. I suspect that one person's image processing tool(s) are producing PNGs that don't play well with `libpng`.

**Comment by mwobensmith** [comment]
That's odd that this would go away when converting the hi-res images via `-z`. 

If you run with `-i DEBUG`, you can see which PNGs are causing the error. On Mac, for me, none of the problem images contain `@2x` in their name.

Sample output:
```
2018-12-19 09:40:01 [DEBUG] [iris.api.core.pattern] Module sidebar.py requests image close_arrow.png
2018-12-19 09:40:01 [DEBUG] [iris.api.core.pattern] Found /Users/mwobensmith/PycharmProjects/iris/iris/api/core/firefox_ui/images/osx/close_arrow.png
libpng warning: iCCP: extra compressed data
```

Here's the list of files that seem to be a problem on Mac. Obviously these are not loaded on Linux, but I imagine we'd get the list of files there using the same method.
```
/iris/api/core/firefox_ui/images/osx/close_arrow.png
/iris/api/core/firefox_ui/images/osx/open_arrow.png
/iris/api/core/firefox_ui/images/osx/history_yesterday.png
/iris/api/core/firefox_ui/images/osx/history_yesterday.png
/iris/api/core/firefox_ui/images/osx/history_august.png
/iris/api/core/firefox_ui/images/osx/history_september.png
/iris/api/core/firefox_ui/images/osx/history_october.png
/iris/api/core/firefox_ui/images/osx/history_november.png
/iris/api/helpers/images/osx/5MB.png
/iris/api/helpers/images/osx/10MB.png
/iris/api/helpers/images/osx/20MB.png
/iris/api/helpers/images/osx/about.png
```

**Comment by tracywalker** [comment]
hmmm yeah, is odd. Also, there are way more @2x.pngs in our libraries than the number of warnings I see at run time.

**Comment by mwobensmith** [comment]
It seems to be happening when we create the `Pattern`, which then loads the image data from disk and creates an `Image` object by calling `Image.fromarray(byte_array)`. In the conversion, `libpng` - which I assume is used within the `Image` class - complains that there's extra data in this byte array that is not needed. I believe it discards that data, but the problem of the error message remains. 

I don't see a way from our code to suppress this warning. However, we can always fix the images themselves.

**Comment by tracywalker** [comment]
I spoke with Roxana about this. I believe we determined the general cause.  She recently ( a time frame that coincides with when the  first started occurring) switched from checking in png's on each platform machine to sending the png's via email to a central machine for one check-in.  Something in that process seems likely to be the culprit.

**Comment by tracywalker** [comment]
Roxana, do you still have the original images on each machine?  If so, can you re-use them to fix this?  Otherwise, please recapture the offending images and swap them in for the ones that are causing this warning on Linux and Mac.

**Comment by tracywalker** [comment]
code approved
