### ISSUE TITLE
Enhance click_auxiliary_window_control(button) function to support both main and auxiliary window controls

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1422]
Right now we use `minimize_window()` and `maximize_window()` functions as keyboard shortcuts.

As we already know these are not always the best solution to do things because are not stable. Currently we have `click_auxiliary_window_control(button) ` function with which we can handle the auxiliary window controls(minimize, maximize and close).

We can enhance this method to support both type of windows: `auxiliary` and `main`. For that we can update the `click_auxiliary_window_controls()` function in order to support one more parameter called window_type and we could rename the function into `click_window_controls(button, window_type)`and we can add some extra controls patterns for main window.

For that we can create a new firefox_ui object called `WindowControls` that contains all the patterns used by window controls function. Then we can create extra logic inside of it for those patterns depending the window_type parameter. Also we can adjust any type of logic that we currently have inside the  `click_auxiliary_window_control(button)`.

**Comment by IonutBudeanu** [comment]
First version of this implementation can be found in issue_1422 branch.

For now works fine on MAC. Further i'll test it on the other platforms.

Thank You

**Comment by silviuFlorin** [comment]
Code approved
