### ISSUE TITLE
Fix test_suite_id's

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1424]
There have been a few test cases checked in lately that have test_suite_id's matching the iris github issue number.  This field is to match the test suite ID number in Testrail.  In each case, this should be 2000 for the history test suite.

history_menu_recent_history.py
history_menu_forget_page.py
delete_history_from_library_context_menu.py

Please change them to read 

self.test_suite_id = '2000'

**Comment by alinrus** [comment]
Fix done in branch 'issue_1424'. @tracywalker please review.

**Comment by tracywalker** [comment]
code approved
