### ISSUE TITLE
Fix search_engine_can_be_added() test case

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1523]
Due to some changes that occurred in the new Firefox version this test requires a little bit of refactor: one new pattern and some flow adjustments.

Notice that these changes are applicable for all the supported platforms.

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1523.

Please review.

Thank You

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: "Find add-ons field is present on the page. - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:

>> Traceback (most recent call last):
>> File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in
>> load_entry_point('iris', 'console_scripts', 'iris')()
>> File "c:\iris\iris\__main__.py", line 38, in main
>> run_iris()
>> File "c:\iris\iris\__main__.py", line 108, in run_iris
>> run(master_test_list, tests, browser)
>> File "c:\iris\iris\test_runner.py", line 69, in run
>> current.run()
>> File "c:\iris\iris\tests\awesomebar\search_engine_can_be_added.py", line 140, in run
>> assert_true(self, find_add_ons, 'Find add-ons field is present on the page.')
>> File "c:\iris\iris\asserts.py", line 78, in assert_true
>> assert_equal(test_case, actual, True, message)
>> File "c:\iris\iris\asserts.py", line 32, in assert_equal
>> Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))
