### ISSUE TITLE
Improve OCR support in Iris 1.0

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1530]
As per discussions with @AndreiH, we can make improvements to our current OCR support, and then port that work to Iris 2 when we are ready.

1. Update architecture in Iris to install any new components for Tesseract 4 that will improve the implementation.
2. Improve existing Iris text search algorithms as proposed to be simpler, less noisy, and more accurate.
3. Expand the existing unit test to cover a wider array of scenarios to verify that we have a reliable implementation.
    * Use various text formatting, point size, fonts, color, etc.
    * Use the `Region.text()` API to extract text for examination.
4. (stretch goal) Make sure all core APIs that search for `Patterns` (`wait`, `exists`, etc.) can also perform text search.

**Comment by AndreiH** [comment]
Hello @mwobensmith .
All that could to be done for now, was done. If we want to add more improvements to the methods that use and will use OCR, we would have to rewrite the methods and all the code that uses Pattern and Text search.

This is ready for review ! Thanks !

**Comment by mwobensmith** [comment]
\o/
