### ISSUE TITLE
Develop test case: Searching for bookmarks from the Bookmarks Sidebar works properly.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#156]
https://testrail.stage.mozaws.net/index.php?/cases/view/4104

**Comment by IonutBudeanu** [comment]
This functionality is already covered in some bookmark tests like: add_open_delete_bookmarks.py or bookmarks_menu_and_toolbar.py. 

@tracywalker if you agree with that please close this issue as resolved.

Thank You

**Comment by tracywalker** [comment]
The test case (and issue name) are a bit misleading. The test is that you can search the sidebar for a bookmark by a tag name.
 
The instructions in the test case, step 4 "Search for a bookmark by tag, using the search bar available in the sidebar."   You'll have to create a tagged bookmark, first.

**Comment by IonutBudeanu** [comment]
This test case is 100% covered in add_bookmark_tags_via_bookmark_sidebar.py test.

@tracywalker do you think that is necessary to develop a new test case for this issue or is fine just to close it as resolved due to test mentioned above?

Thank You

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_156.

Please review.

Thank You.

**Comment by tracywalker** [comment]
code approved
