### ISSUE TITLE
Support download/test of more channels

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#1641]
As requested by Release QA, can we download Firefox from the following channels?

`beta-cdntest, aurora-cdntest, aurora, release-localtest, release-cdntest, esr-localtest, esr-cdntest`

**Comment by ashughes1** [comment]
I've double checked and verified that the way this is controlled is by editing a js file in the Firefox install folder.

Eg. Testing Firefox Beta updates on the ```beta-cdntest``` channel on Windows:
1. Edit C:/Program Files/Mozilla Firefox/defaults/pref/channel-prefs.js 
2. Change the line ```pref("app.update.channel", "beta");``` to ```pref("app.update.channel", "beta-cdntest");
3. Start Firefox and check for updates

Firefox will check for updates on the ```beta-cdntest``` channel. To revert simply pave-over install or edit the file back ```pref("app.update.channel", "beta");```.

@mwobensmith as mentioned in our meeting today I'd be happy to take this on so it can be implemented in Iris 1.0 to speed up deployment to Release QA. Let me know if this is okay with you and I'll assign this to myself.

**Comment by mwobensmith** [comment]
@ashughes1 Sounds good!

**Comment by mwobensmith** [comment]
We need something akin to an API that does a step between downloading Firefox and running it. It could be called `set_update_channel`, which would take one of the channel names above and add it to the default JS file within the Firefox app install. 

@silviuFlorin Can you give this a look?

**Comment by silviuFlorin** [comment]
@mwobensmith please review branch issue_1641
I created a new argument: -u (update channel). If the argument is set and valid the 'app.update.channel' profile preference is set.

**Comment by mwobensmith** [comment]
Looks great, thanks for doing this @silviuFlorin !

**Comment by tracywalker** [comment]
Changing app.update.channel in the profile doesn't correctly update the actual channel.  I just tried it with 'release' channel.  `iris -o -u release -f 64.0b3 -t manual_update`
The test shows as PASSED by updating to 66.0b13 on the 'beta' channel. 

You have to make the change to app.update.channel pref in the channel-prefs.js file in <application directory>/defaults/pref/channel-prefs.js in order for Firefox to know which channel it is supposed to be using.

**Comment by mwobensmith** [comment]
I guess if we need to change this for what Tracy mentions above, we could write a simpler solution that does not involve the `config.ini` file.

We could just look for the value of the `-u` argument, and if it exists, write it to the pref inside `/defaults/pref/channel-prefs.js`.  No need to check against a list of supported channel names; this can be the responsibility of the person who runs the test. I'd prefer to limit the config file to something that stores user-specific data when possible. 

What do you think, @silviuFlorin ?
