### ISSUE TITLE
Find Toolbar tests refactoring

### ISSUE THREAD

**Issue by paulprokhorovmoz** [mozilla/iris#1655]
Scope of work:

- Replace existing pattern images of Firefox interface with attributes of UI Classes
- Move shared pattern images to the local_web folder

**Comment by tracywalker** [comment]
Scope of work is:

- Replace existing pattern images of Firefox interface with attributes of UI Classes  (Find Toolbar and other classes where applicable)
- Create a list of pattern declarations for global use under /iris/api/core/local_web.py > Soap Wiki Test Site.  This should be done for basically all of the captured patterns of anything that Soap wiki page.  Please rename this section to Soap Wiki Test Site and SOAP_WIKI_TEST_SITE to be more specific.  Someone else may come along and want to use a different wiki test site page.  We should make the distinction now.

**Comment by tracywalker** [comment]
code approved
