### ISSUE TITLE
Investigate Refresh Firefox not appearing in about:support

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1662]
This feature is present when you run Firefox manually. It is not present when you Firefox via Iris.  I've checked with LIKE_NEW and BRAND_NEW profiles.  The latter with all preferences in profile.py disabled.  In each case the feature isn't available in about:support.  

Please investigate why this is happening and provide a solution or workaround.

1) go to about:support
2) look at upper right of content
3) there should be an option to Refresh Firefox and another to try in safe mode

In Firefox the option for Refresh is there. The option is not there when Firefox is run via Iris per above.

**Comment by tracywalker** [comment]
Silviu, please take a look at this.  it's blocking development of several new test cases  Thank you.

**Comment by pavelciapa** [comment]
Did some research on this topic.

4 years ago there were opened issue: "Refresh Firefox button is missing using a new profile different from dev-edition default profile"[https://bugzilla.mozilla.org/show_bug.cgi?id=1100334](https://bugzilla.mozilla.org/show_bug.cgi?id=1100334)

Would like to point that in our case, Refresh Firefox not appearing in about:support ONLY running from Iris

Opened thread at [support.mozilla.org/en-US/questions/1244991](support.mozilla.org/en-US/questions/1244991)
According to comments from this thread, in module:
[https://dxr.mozilla.org/mozilla-beta/source/toolkit/modules/ResetProfile.jsm](https://dxr.mozilla.org/mozilla-beta/source/toolkit/modules/ResetProfile.jsm)
(lines 12-15)
```
var ResetProfile = {
   * Check if reset is supported for the currently running profile.
   * @return boolean whether reset is supported.
```

Perhaps, current Iris Firefox runs profile that doesn't support reset functionality.

**Comment by tracywalker** [comment]
It seems that a profile has to be set as "default"  in order for the button to appear.  I've asked in the bugzilla bug if there is any setting in the profile we can alter as a workaround

**Comment by tracywalker** [comment]
our BRAND_NEW profile should work. However, mozrunner still sets many preferences that makes BRAND_NEW profile not really act like brand new.  I haven't been able to figure out which pref that is either set or not set by mozrunner that is creating this issue of missing Refresh Firefox button on about:support.

**Comment by tracywalker** [comment]
The way Iris handles profiles does not play well with the way Firefox handles profiles in this situation of identifying default profile location.  There are mochitests which hook into Fx code get this functionality to work.  But we're not able to do that. As such, it is likely impossible for Iris to automate the test cases around the Refresh Firefox feature.

I will close the test case development issues involving Firefox Refresh.
