### ISSUE TITLE
self.blocked_by issue skips running the test on all platforms 

### ISSUE THREAD

**Issue by alinrus** [mozilla/iris#1664]
self.blocked_by issue should not influence excluding Platform rules already specified. Test should run on the platform we expect to instead having skipped on all Platforms.

**Comment by tracywalker** [comment]
I made a change to general.py that correctly alphabetized the imports.  Doing so created a conflict with this branch that is showing in PR #1665. Please resolve the conflict by taking the alphabetized import list. Thank you.

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1664.

Thanks.
