### ISSUE TITLE
Investigate and fix content blocking pop issue

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1679]
Since Firefox beta 65 has been landed content blocking pop up is no longer controllable using this preference `browser.contentblocking.enabled`. 

According to this [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1488826) the only way to disable that pop up for the moment is to set the `marionette.enabled` preference to `True`, but, inside of a Iriis run this is not possible, the preference remaining unchanged and appears to be some how protected.

Please notice that due to this issue some test cases are failing.

Examples of failing tests:

- add_links_keyboard_shortcuts 

- perform_a_search_by_keyboard_only

This particularities drives me to think that this problem requires attention from the core side.

**Comment by tracywalker** [comment]
There doesn't seem to be a viable background solution here.  Discussed this with Ionut and we decide to create a UI class and function to identify and close the offending dialog. Also add code, in each test case affected, to call the function as needed when we identify tests affected by the dialog.

**Comment by tracywalker** [comment]
code approved
