### ISSUE TITLE
Fix zoom_controls_on_toolbar test case

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1680]
Due to some improvements for image search `zoom_controls_on_toolbar` test fails because the focus remains on the `zoom_out_button` and the pattern is no longer seen. Adding a `reset_mouse` statement upon finding the pattern will fix this issue moving the cursor into a neutral position.

Please notice that this issue is reproducible for Win 10 and Win 7

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1680.

Thank You

**Comment by icrisan** [comment]
code approved.
