### ISSUE TITLE
Fix wrong declaration for the Platform.ALL inside the self.blocked_by

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1698]
Right now we have this form `self.blocked_by = {'id': 'issue_1628', 'platform': [Platform.ALL]}` and because the `Platform.ALL` is declared as a list when it's already a list causes problems because the tests start running when it's supposed to be skipped.

The fix for this problem is just to declare self.blocked_by like this:

`self.blocked_by = {'id': 'issue_1628', 'platform': Platform.ALL}`

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1698.

Thanks

**Comment by icrisan** [comment]
code approved.
