### ISSUE TITLE
Enhance close_content_blocking_pop_up() to use region

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1742]
On Mac non-retina some tests failed due to a incorrect click action performed on a tab close button instead of content blocking pop up close button. 

Creating a region where actions will be performed more precisely will increase the efficiency of the function.

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1742.

Thank You

**Comment by tracywalker** [comment]
code approved
