### ISSUE TITLE
Fix history_not_remembered and history_remembered tests for osx platform

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#1744]
`history_not_remembered` and `history_remembered` tests are failing on the `osx` platform due to an incorrect scale of the pattern. Changing the `firefox_logo_dock` pattern will fix the problem.

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1744.

Thanks

**Comment by tracywalker** [comment]
code approved
