### ISSUE TITLE
[Control Center][object Object] is displayed in test case details, 'blocked_by' field, for tests that are skipped from running on a specific OS

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#1761]
After fixing issue #1664(PR #1673) Control Center displays [object Object] in test case details for 'blocked_by' field.

**Comment by mwobensmith** [comment]
@IonutBudeanu When you enhanced the `blocked_by` property, you forgot to change the part of the code that generates the data for the control center.

In `api/core/util/json_utils.py`, see line 179:
```
            test_object['blocked_by'] = current_test.blocked_by
```
Now that `blocked_by` is a dict object in Python - and not a string - we will need to extract the original bug ID to display in the control center web page.

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_1761.

Thank You
