### ISSUE TITLE
Test case: Scrolling works properly on long web pages.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1783]
https://testrail.stage.mozaws.net/index.php?/cases/view/4660

**Comment by nevdokimov** [comment]
This test case requires to login to the facebook page and use the same scrolling methods that we did in previous test cases(it has not difference from usual scrolling of any web page).

**Comment by tracywalker** [comment]
yes,  no need to do this test at face book.  We just want to be sure scrolling works well at a long page  the will ensure content is still loading while scrolling.
