### ISSUE TITLE
Update Win bootstrap.sh to always install `which` library as it is used in Iris to check for Tesseract

### ISSUE THREAD

**Issue by AndreiH** [mozilla/iris#1799]
This issue was found recently while running bootstrap on Windows 10.
`Which` library needs to be always installed, no need for checks if installed before.

**Comment by mwobensmith** [comment]
@poush That would be great. Use the guidelines [here](https://github.com/mozilla/iris/wiki/Developer-workflow) when you are working on the issue. 

When you are finished, @AndreiH will review your PR and we'll take it from there. 

Thanks for your enthusiasm. 😁

**Comment by mwobensmith** [comment]
@poush Hi there! Any update on this? Let us know if you need help.

**Comment by AndreiH** [comment]
@mwobensmith , I would like to work on this, since Manual QA team already is affected by this. Thanks !

**Comment by poush** [comment]
@AndreiH @mwobensmith Deeply apologize, I didn't realize that I never created PR of my commit that I created long ago and somehow missed last notifications. I'm sending the PR right now, feel free to discard it if it is not correct or the work has been done. Thanks!

**Comment by AndreiH** [comment]
@poush it's ok.
Thank you for contributing on this.
I am going to take a look over the changes. Thank you again !

**Comment by AndreiH** [comment]
PR https://github.com/mozilla/iris/pull/2070 was merged and this is now fixed.
I am closing this issue. 
Thanks guys !

**Comment by poush** [comment]
Thanks @AndreiH :)
