### ISSUE TITLE
Test case: Drop image data in demopage.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1836]
https://testrail.stage.mozaws.net/index.php?/cases/view/165086

**Comment by pavelciapa** [comment]
When select 'drop-image-data' on demo page[https://mystor.github.io/dragndrop/#], and actually dropping/pasting to page, it says NOT MATCHING (1328984) but should say MATCHING

Leads to bug -> https://bugzilla.mozilla.org/show_bug.cgi?id=1328984

**Comment by tracywalker** [comment]
Finish the test case and set blocked by bug 1328964

**Comment by pavelciapa** [comment]
ok
