### ISSUE TITLE
Test case: Drop image data in demopage opened in Private Window.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#1837]
https://testrail.stage.mozaws.net/index.php?/cases/view/165087

**Comment by pavelciapa** [comment]
Leads to bug -> https://bugzilla.mozilla.org/show_bug.cgi?id=1328984

**Comment by tracywalker** [comment]
Finish the test case and set blocked by bug 1328964

**Comment by pavelciapa** [comment]
ok
