### ISSUE TITLE
Create scroll_until_pattern_found function

### ISSUE THREAD

**Issue by paulprokhorovmoz** [mozilla/iris#1925]
Create scroll_until_pattern_found function, which will accept different scroll functions and image pattern to search

**Comment by tracywalker** [comment]
While you're doing this, please place them in general.py in function alphabetical order.  Also move repeat_key_up_until_image_found() and repeat_key_down_until_image_found() to their correct place alphabetically.  Thanks

**Comment by paulprokhorovmoz** [comment]
Done
