### ISSUE TITLE
Develop test case: Perform a search using an one-off.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#195]
https://testrail.stage.mozaws.net/index.php?/cases/view/108249

**Comment by icrisan** [comment]
coverage added in branch "issue_195". please review.

**Comment by tracywalker** [comment]
It looks good on Windows and Linux. However you're missing an image for search_suggestion_bookmarked_tab.png on OSX.  Please add that image.

Also, going forward with the case development, please make all of your image declarations patterns.
for instance:
page_bookmarked = 'page_bookmarked.png'
should be converted to:
page_bookmarked = Pattern('page_bookmarked.png')

make those changes and code is approved for merge.
