### ISSUE TITLE
Develop test case: "Set as Default Search Engine" using the one-off button's context menu.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#197]
https://testrail.stage.mozaws.net/index.php?/cases/view/108251

**Comment by icrisan** [comment]
added coverage in branch issue_194_196_197. please review.

**Comment by silviuFlorin** [comment]
At one point we are checking that Google logo is present. We should search for another pattern as the Google logo is changing very often and is hard to maintain

**Comment by icrisan** [comment]
updated test. please review.

**Comment by silviuFlorin** [comment]
Code approved
