### ISSUE TITLE
Develop test case: Search using one-offs while maximizing/minimizing the browser's window.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#198]
https://testrail.stage.mozaws.net/index.php?/cases/view/108252

**Comment by icrisan** [comment]
created branch "issue_198" for this issue. please review.

**Comment by silviuFlorin** [comment]
For Mac please use ALT + click maximize button to minimize browser window. Please update test

**Comment by icrisan** [comment]
updated test. please review.

**Comment by tracywalker** [comment]
this is failing to find the image, on Windows at least, in lines 87-88

**Comment by icrisan** [comment]
I am not able to reproduce this issue. Test passes for me on all the platforms.  I asked Paul to run the test and it passed for him also.

**Comment by tracywalker** [comment]
code approved pending one minor change Ioana is making. please merge to dev when that is complete.

**Comment by icrisan** [comment]
barnch updated.
