### ISSUE TITLE
Iris cannot convert image pattern in the Presentation mode on Retina

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris#1995]
Iris cannot convert image pattern of pdf in the Presentation mode created with Sikuli on Retina to 1920x10180 Mac resolution and vice versa (1920x1080 Mac / Sikuli -> Retina)
affected tests: pdf_viewer #1786

**Comment by dbakaev** [comment]
@tracywalker this issue blocks one of content scroll tests.

**Comment by tracywalker** [comment]
What do you mean can't convert pattern? Which pattern is this failing in?  

This test fails for me after it has scrolled back to top of the pdf in Presentation mode.  The pattern the test is using in the scroll function doesn't exist on screen.

**Comment by tracywalker** [comment]
>  The pattern the test is using in the scroll function doesn't exist on screen.

Sorry I was looking at wrong pattern.  investigating further.

**Comment by nevdokimov** [comment]
It cannot find the pattern on the screen for various screen resolution.
If we have Retina display on MacBook it's fine,  but it can't get this pattern for other resolutions for osx.

**Comment by tracywalker** [comment]
I reduced similarity and the test now works.  Make following change to line 24:

presentation_mode_content_pattern = Pattern('presentation_mode_content.ping').similar(0.6)

**Comment by tracywalker** [comment]
I am running it on non-retina.  The test was failing.  However, with the pattern similarity changed, the test works.

**Comment by tracywalker** [comment]
I do see the content size changing notably between the two modes. Another solution would be to make a new capture and new pattern from presentation mode distinct from the pattern used during normal mode.

**Comment by tracywalker** [comment]
Maybe try a pattern capture of something other than text.  Iris does have quirkiness with text captured as patterns.

**Comment by nevdokimov** [comment]
I was capturing different patterns for different modes.

**Comment by tracywalker** [comment]
WE may have to mark this test case unsuitable as each machine can present the image in a different resolution than Iris is looking for.
