### ISSUE TITLE
Fix change_bookmark_location test case

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#2004]
`change_bookmark_location` is failing because the content blocking pop up hides one of the searched patterns. Adding the close_content_blocking_pop_up function before the pattern search will fix the test.

**Comment by pavelciapa** [comment]
Strange behaviour for tesseract:

![image](https://user-images.githubusercontent.com/45387203/63759731-84895180-c8ad-11e9-9d9f-2fda8916c3ea.png)
