### ISSUE TITLE
Remove utils.py from tests/content_scroll

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2009]
Helper functions should not be put in test directories.  The function in tests/content_scroll/utils.py, def check_preference(pref_name, value) should be put in iris/api/helpers/general.py. Please clean this up.

**Comment by nevdokimov** [comment]
I got it.
Pull request: https://github.com/mozilla/iris/pull/2196

**Comment by tracywalker** [comment]
code approved
