### ISSUE TITLE
Create a bash script for running the 'search code' tests

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#2016]
We need a bash script to run our 'search code' tests(3 arguments are needed here the **channel**, the **locale** and the **region**).

**Comment by tracywalker** [comment]
We need Iris to run these search code tests as part of general test run.  A batch script to run them is not what we're looking for.  Channel is no involved with these tests.  It's build type, Beta/Release vs ESR.  Locale determines region.  We can detect both pieces of data; build and locale from with in the test.  Therefore this is invalid.
