### ISSUE TITLE
Highlighting only works when an image is found

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#2024]
If you invoke Iris with `-b` to get the runtime highlighting, you can see the red border that is drawn on patterns and regions. However, if the pattern is not found, we don't draw the border on anything.

I think we should change this behavior to always draw the border on the region when a search API is called. When you are debugging a test, you want to see where Iris is searching, even if it's in the wrong location. 

The code change would be minimal, but I'd like to understand if there's any reason for us to keep it the way it is now.

**Comment by silviuFlorin** [comment]
@mwobensmith There is no particular reason for not showing the region. It's an use case that we missed when we implemented this feature.
