### ISSUE TITLE
Develop test case:  Check One-off searches bar and Settings gear after remove checks for search engines in Search Settings (Bug 1298047).

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#205]
https://testrail.stage.mozaws.net/index.php?/cases/view/108259

**Comment by icrisan** [comment]
added coverage in branch "issue_205". please review.

**Comment by tracywalker** [comment]
This is failing on Windows and Mac in the last iteration checks at element position 1.

2018-08-17 09:54:35 [SUCCESS] [iris.api.helpers.results] Step: Element found at position 0 in the list not found., outcome: >>> PASSED <<<
2018-08-17 09:54:35 [WARNING] [iris.api.helpers.results] Step: None, outcome: >>> FAILED <<<

---------------------------------------------------------------------------------------------------------------
ª Traceback (most recent call last):                                                                          ´
ª   File "c:\users\lenovo~1\iris\iris\test_runner.py", line 73, in run                                        ´
ª     current.run()                                                                                           ´
ª   File "c:\users\lenovo~1\iris\iris\tests\awesomebar\remove_checks_from_search_engines.py", line 92, in run ´
ª     raise FindError('Element found at position ' + i.__str__() + ' in the list found.')                     ´
ª FindError: Element found at position 1 in the list found.                                                   ´
---------------------------------------------------------------------------------------------------------------

**Comment by tracywalker** [comment]
The test is failing to set focus to the content.  

Ioana, I am afraid looking for, then click on "Keyword" will also fail for me on my Windows machine, as that element is off screen. I don't like it, but TAB 4 times then SPACE works to get to the One-Click widget.

**Comment by tracywalker** [comment]
code approved
