### ISSUE TITLE
Fix blocked by in drop_image_data test.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2059]
The test is using the old method to block/exclude a test. This is causing test runs to think the test case is not a valid test file.

The proper method to use for block/exclude should be implemented.
Replace the two lines (17 and 18), self.blocked_by and self.exclude, with one line as follows:

```self.blocked_by = {'id' = '1328964', Platform.ALL}```

Please use this format going forward.  

Thank you.

**Comment by pavelciapa** [comment]
self.blocked_by = {'id' = '1328964', Platform.ALL}  -> this line gives sintax error. 
Correct would be ->  self.blocked_by = {'id': '1328964', 'platform': Platform.ALL}

Replaced ;)
