### ISSUE TITLE
Test case: Open Library from Bookmarks menu

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2061]
https://testrail.stage.mozaws.net/index.php?/cases/view/163193

**Comment by hathibelagal-dev** [comment]
@tracywalker Can I take this?

**Comment by tracywalker** [comment]
Yes, a simple one ;)


  | Step | Expected Result
-- | -- | --
1 | Launch Firefox. | Firefox is successfully launched.
2 | Open the Firefox menu and click on the Show All Bookmarks button from the Bookmarks section. | The Library is opened.

**Comment by hathibelagal-dev** [comment]
@tracywalker Looks like this is done already.

**Comment by tracywalker** [comment]
ok, yes, pick another one, if you would like to.
