### ISSUE TITLE
Test case: "Create" a new folder using star-shaped button

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2067]
https://testrail.stage.mozaws.net/index.php?/cases/view/163404

**Comment by hathibelagal-dev** [comment]
@tracywalker I'd like to work on this case. Thanks.

**Comment by tracywalker** [comment]
| Step | Expected Result
-- | -- | --
1 | Launch Firefox. | Firefox is successfully launched.
2 | Open a website that's currently not in your Bookmarks list. | The website is properly loaded.
3 | Click the star-shaped button from toolbar. | Edit This Bookmark panel is displayed under the star-shaped button.
4 | From the Folder select Choose...option. | Edit This Bookmark panel is displayed with all the destination folders.
5 | Select Bookmarks Toolbar from the list and after click on New Folder. | New Folder is opened under the Bookmarks Toolbar.
6 | Name the folder already created and press Done. | The folder is correctly saved  and displayed  in Bookmarks Menu.

**Comment by tracywalker** [comment]
Good luck, hathibelagal.  Please don't hesitate to ask for help or suggestions.

**Comment by hathibelagal-dev** [comment]
Thank you, tracywalker.
