### ISSUE TITLE
Test case: Open a bookmark using 'Open' option from the contextual menu

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2127]
https://testrail.stage.mozaws.net/index.php?/cases/view/165437

**Comment by spronoza** [comment]
@tracywalker It is not possible to open contextual menu from Firefox menu > Bookmarks > Mozilla Firefox > Right click on the bookmark. We are going to exclude such tests for OSX platform.

**Comment by tracywalker** [comment]
Yes, that is correct to exclude OSX.

**Comment by spronoza** [comment]
Ok, thanks
