### ISSUE TITLE
Develop test case: Key navigation in the URL drop-down in high contrast theme [bug 1363692].

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#215]
https://testrail.stage.mozaws.net/index.php?/cases/view/120136

**Comment by icrisan** [comment]
coverage added in branch "issue_215". please review.

**Comment by tracywalker** [comment]
This test case is failing on all three platforms randomly at the end of the repeated scroll_down(). It needs a UI_DELAY to let the suggests list to populate full before attempting to scroll through.  I'll add that and merge to dev.
