### ISSUE TITLE
Test case: Cut a bookmark from the Recently Bookmarked section

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2153]
https://testrail.stage.mozaws.net/index.php?/cases/view/165489

**Comment by nevdokimov** [comment]
Cannot reproduce this test case according to the next bug:
https://bugzilla.mozilla.org/show_bug.cgi?id=1533339

**Comment by tracywalker** [comment]
Nikita, If you cannot reliably develop this test case, you can move it into a blocked section in the project. If you can still create the test case in Iris, but it will be a known failure, label the test case blocked_by the bug you referenced.  Thanks.

**Comment by nevdokimov** [comment]
I'm sorry I meant that this test which I reproduced in Iris fails because of this bug.

**Comment by tracywalker** [comment]
The bug you mentioned is a recent regression.  So mark the Iris test case with blocked_by.  I've added [iris] to the bug QA whiteboard.
