### ISSUE TITLE
Test case: Open a bookmark in a New Window

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2159]
https://testrail.stage.mozaws.net/index.php?/cases/view/164365

**Comment by hathibelagal-dev** [comment]
@tracywalker Hello. I'd like to work on this test case. I've already read the test case creation guide. If no one else is working on this already, can I get started?

**Comment by tracywalker** [comment]
hathibelagal, I have a team working on various bookmark tests. This one is already in progress.  We'll find another test case for you to work on that isn't already in progress.

**Comment by tracywalker** [comment]
hathibelaga,  please select a test from the project https://github.com/mozilla/iris/projects/21.  Any of these, besides the ones with Bug XXXXXX in the title should be fine to work on.  Let me know, in the other issue, which one look interesting to you Then I'll add the test case steps to the issue for you.
