### ISSUE TITLE
Develop test case: More search engines can be added and are well displayed on one-off searches bar.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#217]
https://testrail.stage.mozaws.net/index.php?/cases/view/108261

**Comment by icrisan** [comment]
coverage added in branch "issue_217". please review.

**Comment by tracywalker** [comment]
code approved.  

Note: this does fail on my small resolution Windows machine.  if I scroll down where it fails, it passes.  So not holding up for the resolution problem, that I am going to have to fix.
