### ISSUE TITLE
Test case: Bookmark a page by drag&drop in Library

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2180]
https://testrail.stage.mozaws.net/index.php?/cases/view/169274

**Comment by spronoza** [comment]
@tracywalker 
It seems that expected result in 4th step have not enough information 
"Click on the opened tab and drag&drop it into an available section from Library->Bookmarks.        
           E: The page is correctly bookmarked and no errors are thrown in Browser Console."
Is it possible to don't check error absence in Browser Console?
Otherwise, please specify what errors expected.

**Comment by tracywalker** [comment]
Don't do the error check in the browser console. Just confirm the bookmark is created correctly.

**Comment by spronoza** [comment]
Ok, thanks
