### ISSUE TITLE
Develop test case: One-off search is well rendered while using a high contrast theme.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#221]
https://testrail.stage.mozaws.net/index.php?/cases/view/108266

**Comment by icrisan** [comment]
@tracywalker should we consider this test case already implemented by key_navigation_high_contrast_theme.py? Please let me know your thoughts. Thank you!

**Comment by tracywalker** [comment]
Yes, the other test already mostly covers this. There is no need to write it again.
