### ISSUE TITLE
Drag and drop demopage don't work as expected

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2244]
16 test_cases from "Drag and drop (test_suite_id=102)" test suite are blocked by drag-and-drop demo page functionality. 
When CTRL+V a file to the demo page, it says NOT MATCHING, regardless of file type. 

demo page -> https://mystor.github.io/dragndrop/

**Comment by pavelciapa** [comment]
affected test_case ids:

1. 165078
2. 165079
3. 165080
4. 165081
5. 165082
6. 165083
7. 165084
8. 165085
9. 165090
10. 165091
11. 165092
12. 165093
13. 165094
14. 165095
15. 165096
16. 165097

**Comment by tracywalker** [comment]
As per our meeting, please automate these tests cases.  Then block_by each test case with the bugzilla issue tracking the problem.

**Comment by pavelciapa** [comment]
Test case is automated
