### ISSUE TITLE
Unable to install on Windows 10

### ISSUE THREAD

**Issue by chartjes** [mozilla/iris#2263]
I have been trying to install Iris on a Windows 10 laptop. The step where I use pipenv to install the virtual environment is failing. 

C:\Users\chartjes\mozilla\iris>pipenv install
Creating a virtualenv for this project...
Pipfile: C:\Users\chartjes\mozilla\iris\Pipfile
Using C:/Users/chartjes/scoop/apps/python27/current/python.exe (2.7.15) to create virtualenv...
[=== ] Creating virtual environment...New python executable in C:\Users\chartjes\.virtualenvs\iris-MGQZYs-K\Scripts\python.exe
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter C:/Users/chartjes/scoop/apps/python27/current/python.exe

Successfully created virtual environment!
Virtualenv location: C:\Users\chartjes\.virtualenvs\iris-MGQZYs-K
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Locking Failed!
[pipenv.exceptions.ResolutionFailure]:   File "c:/python27/lib/site-packages/pipenv/resolver.py", line 69, in resolve
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "c:\python27\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "c:\python27\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "c:\python27\lib\site-packages\pipenv\utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       ResolutionFailure: ERROR: ERROR: Could not find a version that matches mozlog==3.*,>=3.0,~=4.0
[pipenv.exceptions.ResolutionFailure]:       Tried: 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.2.1, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 2.10, 2.11, 3.0, 3.1, 3.2, 3.2, 3.3, 3.3, 3.4, 3.4, 3.5, 3.5, 3.6, 3.6, 3.7, 3.7, 3.8, 3.8, 3.9, 3.9, 3.9, 3.10, 3.10, 4.0, 4.0
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches mozlog==3.*,>=3.0,~=4.0
Tried: 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.2.1, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 2.10, 2.11, 3.0, 3.1, 3.2, 3.2, 3.3, 3.3, 3.4, 3.4, 3.5, 3.5, 3.6, 3.6, 3.7, 3.7, 3.8, 3.8, 3.9, 3.9, 3.9, 3.10, 3.10, 4.0, 4.0
There are incompatible versions in the resolved dependencies.
[pipenv.exceptions.ResolutionFailure]:       req_dir=requirements_dir
[pipenv.exceptions.ResolutionFailure]:   File "c:\python27\lib\site-packages\pipenv\utils.py", line 726, in resolve_deps
[pipenv.exceptions.ResolutionFailure]:       req_dir=req_dir,
[pipenv.exceptions.ResolutionFailure]:   File "c:\python27\lib\site-packages\pipenv\utils.py", line 480, in actually_resolve_deps
[pipenv.exceptions.ResolutionFailure]:       resolved_tree = resolver.resolve()
[pipenv.exceptions.ResolutionFailure]:   File "c:\python27\lib\site-packages\pipenv\utils.py", line 395, in resolve
[pipenv.exceptions.ResolutionFailure]:       raise ResolutionFailure(message=str(e))
[pipenv.exceptions.ResolutionFailure]:       ResolutionFailure: ERROR: ERROR: Could not find a version that matches mozlog==3.*,>=3.0,~=4.0
[pipenv.exceptions.ResolutionFailure]:       Tried: 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.2.1, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 2.10, 2.11, 3.0, 3.1, 3.2, 3.2, 3.3, 3.3, 3.4, 3.4, 3.5, 3.5, 3.6, 3.6, 3.7, 3.7, 3.8, 3.8, 3.9, 3.9, 3.9, 3.10, 3.10, 4.0, 4.0
[pipenv.exceptions.ResolutionFailure]: Warning: Your dependencies could not be resolved. You likely have a mismatch in your sub-dependencies.
  First try clearing your dependency cache with $ pipenv lock --clear, then try the original command again.
 Alternatively, you can use $ pipenv install --skip-lock to bypass this mechanism, then run $ pipenv graph to inspect the situation.
  Hint: try $ pipenv lock --pre if it is a pre-release dependency.
ERROR: ERROR: Could not find a version that matches mozlog==3.*,>=3.0,~=4.0
Tried: 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2.0, 2.1, 2.2, 2.2.1, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 2.10, 2.11, 3.0, 3.1, 3.2, 3.2, 3.3, 3.3, 3.4, 3.4, 3.5, 3.5, 3.6, 3.6, 3.7, 3.7, 3.8, 3.8, 3.9, 3.9, 3.9, 3.10, 3.10, 4.0, 4.0
There are incompatible versions in the resolved dependencies.

Removing and recreating the virtual environment does not make the issue go away.
Running 'pipenv lock --clear' generates the same error message

**Comment by tracywalker** [comment]
I have run into this recently too.  Workaround for me was to run ```pipenv install --skip-lock```

Andrei, please take a look.

**Comment by AndreiH** [comment]
Thank you for posting this issue.
This happened because of all the libraries updates from Mozbase with Python 3.
Some libraries versions were already updated, bumping them to a new version which supports Python 3, others still only support Python 2.
This happened with Mozrunner's dependencies.

I have created a PR in which I currently update only the Mozrunner version, which fixes the issue.
Thanks !

**Comment by AndreiH** [comment]
Being the fact that @silviuFlorin is out.
@icrisan will merge this, since it's a very small change.

**Comment by AndreiH** [comment]
Issue now resolved on `dev` branch! 
Thanks @chartjes  !
