### ISSUE TITLE
Same error repeated in every test

### ISSUE THREAD

**Issue by chartjes** [mozilla/iris#2264]
I am seeing the same error being reported in every single test I run on Windows 10, no matter what version of Firefox I use:

2019-02-13 17:27:12 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test

--------------------------------------------------------------------------------------------------------------
>> Traceback (most recent call last):                                                                       <<
>>   File "c:\users\chartjes\mozilla\iris\iris\test_runner.py", line 66, in run                             <<
>>     confirm_firefox_launch()                                                                             <<
>>   File "c:\users\chartjes\mozilla\iris\iris\api\helpers\general.py", line 292, in confirm_firefox_launch <<
>>     raise APIHelperError('Can\'t launch Firefox - aborting test run.')                                   <<
>> APIHelperError: Can't launch Firefox - aborting test run.                                                <<
--------------------------------------------------------------------------------------------------------------

**Comment by tracywalker** [comment]
Does Firefox open for several seconds the close?  

My first guess is your screen resolution. Iris expects default screen resolution of 1920 x 1080.

**Comment by pavelciapa** [comment]
Method ` confirm_firefox_launch()` expects Iris logo on screen.
It may fail because Firefox browser page loads not in default position or behind your terminal, and Iris logo appears blocked and can't be found by Iris

**Comment by chartjes** [comment]
After changing the resolution for my screen to 1980 x 1020 the tests no longer display that error message.

Perhaps this is something to add to the wiki?

**Comment by tracywalker** [comment]
Indeed,  I updated the System requirements section of our setup wiki page to indicate the recommended screen resolution.
