### ISSUE TITLE
Fix for test case firefox_hijacking_default_search

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2266]
Fix for Issue #1972

**Comment by tracywalker** [comment]
Why isn't this simply being tracked in #1776?  We don't need to create issue B to fix issue A. It's redundant.

**Comment by spronoza** [comment]
Sorry, It is just misprinting. It is fix for issue 1972 actually. I reopened it, if you don't mind.

**Comment by tracywalker** [comment]
Ah, please reference the test case that is broken, instead.
