### ISSUE TITLE
Fix for tls_authentication and tls_websites

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2276]
Changing one pattern in tls_authentication and tls_websites tests

**Comment by tracywalker** [comment]
Please stop referencing issue numbers of resolved test case development issues. What are the names of the affected test cases?  Those test case names are what the issue should referencing.

**Comment by spronoza** [comment]
Ok. I get it, sorry. It tls_authentication and tls_websites

**Comment by tracywalker** [comment]
Perfect! Thank you.
