### ISSUE TITLE
Develop test case: Up/Down Keys - in the Awesome Bar.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#229]
https://testrail.stage.mozaws.net/index.php?/cases/view/108276

**Comment by icrisan** [comment]
@tracywalker should we consider this test case as already implemented by test cases  like(navigate_through_one_off_searches_using_keyboard_keys.py,  perform_a_search_by_keyboard_only.py, etc)? Please let me know your thoughts. Thank you!

**Comment by tracywalker** [comment]
Yes,  this looks basically like a dupe.  There is no need to write it again.
