### ISSUE TITLE
Fix blocked by statement in drop_image_data_in_private_window.py

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2385]
The old exclude format causes Iris to show a warning in yellow "[drop_image_data_in_private_window] not a test file.  Skipping..."

The correct format is:

```self.blocked_by = {'id': '1328964', 'platform': Platform.ALL}```

**Comment by poush** [comment]
@dbakaev this issue seems not completely clear to me but is this (`self.blocked_by = {'id': '1328964', 'platform': Platform.ALL}`) the only line to modified? If yes, can I take this up? (only if it doesn't produce any delay or blockage in the development of the project)

**Comment by tracywalker** [comment]
lines 17 and 18 in the test should be replaced with 
```self.blocked_by = {'id': '1328964', 'platform': Platform.ALL}```

Nothing else to it.  I assigned it to @dbakaev so he and his team may learn the correct way to do this going forward.

However if you want to submit a patch, @poush.  Go ahead.  :)
