### ISSUE TITLE
Fix search_bar_options_work_properly

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2478]
I'm seeing this failing regularly on a slow Windows machine.  Timeouts are needed after getting the contents of the clipboard.

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: "The 'about:preferences#search' page opened. - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>          
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                         
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                              
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                      
>>   File "c:\iris\iris\tests\search\search_bar_options_work_properly.py", line 54, in run                
>>     assert_true(self, expected, 'The \'about:preferences#search\' page opened.')                       
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))
