### ISSUE TITLE
Fix saved_cc_available_in_private_session

### ISSUE THREAD

**Issue by dbakaev** [mozilla/iris#2484]
Fix saved_cc_available_in_private_session (fails on Ubuntu)

**Comment by dbakaev** [comment]
Unable to fix due to a bug https://bugzilla.mozilla.org/show_bug.cgi?id=1534947

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: "Credit card was successfully saved - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>          
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                         
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                              
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                      
>>   File "c:\iris\iris\tests\privacy\saved_cc_available_in_private_session.py", line 173, in run         
>>     assert_true(self, credit_card_successfully_saved, 'Credit card was successfully saved')            
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))
