### ISSUE TITLE
Fix PyAutoGUI dependency issue (PyScreeze)

### ISSUE THREAD

**Issue by yeyartsev** [mozilla/iris#2499]
Last PyScreeze version (0.1.20, released on March, 8-th) doesn't work properly with Iris (SyntaxError exception occured). This problem may be fixed by uninstalling PyScreeze and following installation pyscreeze version 0.1.19. It might be prevented by adding pyscreeze = "==0.1.19" to Pipfile.

**Comment by AndreiH** [comment]
This was already fixed in https://github.com/mozilla/iris/issues/2477
The change is in Dev but currently not in Master branch.

**Comment by AndreiH** [comment]
Closing this issue since it was fixed. Thanks !
