### ISSUE TITLE
Tests are not skipped based on locale when -o is used

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#2520]
My understanding of the logic from the default search code tests is that they should automagically be skipped based on the locale. For example, if the locale is not zh-CN the Baidu test is skipped, if the locale is not RU the Yandex test is skipped.

So when I run the following command, my expectation is that manual_update will run, default_search_code_baidu will be skipped, default_search_code_google will run, and finally default_search_code_yandex will be skipped. 
`iris -l fr -f 64.0b10 -u beta -t manual_update,default_search_code_baidu,default_search_code_google,default_search_code_yandex -o`

However in the above simulation all four tests are run with the Baidu and Yandex tests failing.

@mwobensmith do you know why this is happening? Is it intended?

**Comment by mwobensmith** [comment]
The `-o` flag overrides any logic to exclude a test, so that's why the locale is not being considered. We mark some tests as excluded - such as update tests - to keep them out of the larger runs. I don't know enough about the search code tests to comment on what's intended there, but I suspect it's the same. Is this a problem?

**Comment by tracywalker** [comment]
Ah -o, yeah, that's what causing this. 

We're going to have to rethink how we get the search code tests chained to the update test.

**Comment by tracywalker** [comment]
I have an idea for a solution; Can we make -o enable tests with a self.exclude or self.blocked_by declaration in __init__ instead of just running everything no matter what?

**Comment by tracywalker** [comment]
code approved
