### ISSUE TITLE
Fix cnn_heavy_content

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2542]
cnn_heavy_content - "CNN" heavy content website is properly loaded and works as intended                                 By: Serhii Pronoza
--
1 | 5:57:12 AM | A new private window is successfully opened
2 | 5:57:26 AM | The specified website is successfully loaded.
3 | 5:58:08 AM | The video is playing and the speaker icon is displayed - [Actual]: False [Expected]: True

**Comment by spronoza** [comment]
Fixed by set proper configuration of Virtual Machine
