### ISSUE TITLE
Fix nasa_tv_heavy_content

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2543]
nasa_tv_heavy_content - "NASA TV" heavy content website is properly loaded and works as intended                                 By: Serhii Pronoza
--
1 | 5:58:46 AM | A new private window is successfully opened
2 | 5:58:52 AM | The specified website is successfully loaded.
3 | 5:59:34 AM | The video is playing and the speaker icon is displayed - [Actual]: False [Expected]: True

**Comment by spronoza** [comment]
Fixed by set proper configuration of Virtual Machine
