### ISSUE TITLE
Support running multiple subsequent tests after update in run_update_suite.sh

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#2583]
Currently run_update_suite.sh only runs the manual and background update tests. The Firefox team requires that search_code tests are run following an update.

I have a patch that will add the search_code tests to the execution of the manual and background update tests by default.

Assuming that the Firefox team (or an individual tester for that matter) may want to run more tests following the update and search_code tests, I have included in this patch the addition of a parameter (-t | --tests) that will provide this functionality.

**Comment by tracywalker** [comment]
Anthony, how are the search code tests getting run by default? You added a constant for the search code tests. This constant is not used in the run command as part of -t.
