### ISSUE TITLE
Fix saved_cc_available_in_private_session

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2587]
Fix saved_cc_available_in_private_session test case
 LINUX

saved_cc_available_in_private_session  - Credit Card form inputs that were previously saved in a normal  session are remembered in Private Browsing session                                  By: Pavel
--
1 | 9:10:11 PM | Preferences page is opened
2 | 9:10:12 PM | 'Saved addresses' button is displayed on the Preferences page
3 | 9:10:14 PM | 'Add' button is displayed on the 'Saved addresses' popup
4 | 9:10:16 PM | 'First Name' field is displayed on the 'Add new address' popup
5 | 9:10:18 PM | 'Save' button is displayed on the 'Add new address' popup
6 | 9:10:24 PM | Address list popup dissapeared.
7 | 9:10:25 PM | 'Saved credit cards' button is displayed on the Preferences page
8 | 9:10:27 PM | 'Add' button is displayed on the 'Saved credit cards' popup
9 | 9:10:29 PM | 'Card type' dropdown is displayed on the 'Edit Credit Card' popup
10 | 9:10:31 PM | 'Visa' option is available on the 'Card type' dropdown
11 | 9:10:33 PM | 'Card Number' field is displayed on the 'Edit Credit Card' popup
12 | 9:10:35 PM | 'Name on card' field is displayed on the 'Edit Credit Card' popup
13 | 9:10:38 PM | 'Expiration month' dropdown is displayed on the 'Edit Credit Card' popup
14 | 9:10:40 PM | '05 - May' option is displayed on the dropdown 'Expiration month'
15 | 9:10:41 PM | 'Expiration year' dropdown is displayed on the 'Edit Credit Card' popup
16 | 9:10:43 PM | '2029' option is available on the 'Expiration year' dropdown
17 | 9:10:45 PM | 'Billing address' dropdown is displayed on the 'Edit Credit Card' popup
18 | 9:10:47 PM | Previously saved address displayed on the 'Billing address' dropdown
19 | 9:10:48 PM | 'Save' button is displayed on the 'Edit Credit Card' popup
20 | 9:10:50 PM | Credit card was successfully saved
21 | 9:10:54 PM | Test page is opened.
22 | 9:10:55 PM | 'Card number' field is displayed on the page
23 | 9:11:11 PM | The Credit Card number from the saved profile is displayed in the dropdown - [Actual]: False [Expected]: True

**Comment by pavelciapa** [comment]
Fix saved_cc_available_in_private_session
WINDOWS

saved_cc_available_in_private_session  - Credit Card form inputs that were previously saved in a normal  session are remembered in Private Browsing session                                  By: Pavel
--
1 | 8:06:34 PM | Preferences page is opened
2 | 8:06:38 PM | 'Saved addresses' button is displayed on the Preferences page - [Actual]: False [Expected]: True

**Comment by pavelciapa** [comment]
Added fix for OSX and LINUX
Win interface changed, can't add fix

**Comment by pavelciapa** [comment]
![image](https://user-images.githubusercontent.com/45387203/54689802-d96bb380-4b28-11e9-8931-9985072bdccc.png)

**Comment by pavelciapa** [comment]
Restart Firefox after changing preferences fixed problem 
        change_preference('browser.search.region', 'US')
        restart_firefox(self, self.browser.path, self.profile_path, LocalWeb.FIREFOX_TEST_SITE,
                        image=LocalWeb.FIREFOX_LOGO)

**Comment by tracywalker** [comment]
There is still a test failure on Linux ion this test.  When it occurs, the remainder of the tests in the test run fails/errors out.

**Comment by tracywalker** [comment]
I think the failure on may be the Linux portion here:        
 
```
if Settings.is_linux():
            mouse_move(card_number_field_pattern)
            double_click(card_number_field_pattern)
else:
```

I believe there may be a sleep needed between the mouse_move and the double_click

**Comment by pavelciapa** [comment]
We fixed this yesterday. Changed double_click to click and added timeout

**Comment by pavelciapa** [comment]
Already merged
https://github.com/mozilla/iris/pull/2599/files

**Comment by IonutBudeanu** [comment]
Hi guys, I think we found the problem.

Basically one dialog box representing a password field is not handled and iris is looking for a submit button which not exist on the page. For more details please consult the attached files.

```
>> Traceback (most recent call last):                                                                                <<
>>   File "/home/svuser/.local/share/virtualenvs/iris-zpGrSWP0/bin/iris", line 11, in <module>                       <<
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                         <<
>>   File "/home/svuser/iriscron/iris/iris/__main__.py", line 38, in main                                            <<
>>     run_iris()                                                                                                    <<
>>   File "/home/svuser/iriscron/iris/iris/__main__.py", line 108, in run_iris                                       <<
>>     run(master_test_list, tests, browser)                                                                         <<
>>   File "/home/svuser/iriscron/iris/iris/test_runner.py", line 69, in run                                          <<
>>     current.run()                                                                                                 <<
>>   File "/home/svuser/iriscron/iris/iris/tests/privacy/saved_cc_available_in_private_session.py", line 178, in run <<
>>     assert_true(self, page_opened, 'Test page is opened.')                                                        <<
>>   File "/home/svuser/iriscron/iris/iris/asserts.py", line 78, in assert_true                                      <<
>>     assert_equal(test_case, actual, True, message)                                                                <<
>>   File "/home/svuser/iriscron/iris/iris/asserts.py", line 32, in assert_equal                                     <<
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))          
```

![linux_failure](https://user-images.githubusercontent.com/29912164/55074996-78992980-509a-11e9-8881-fbca0ea42354.jpg)

**Comment by pavelciapa** [comment]
This is Linux system menu for Keyring, which offers to save passwords, needs to be filled in manually once, or from time to time. It can be switched off in system settings, and requires your local machine password. 

Pressing Cancel will not let you save credentials required to pass a test. 

As it was not appearing earlier, started week ago, it could be caused by update of Mozilla, may be update of Linux but less possible

**Comment by pavelciapa** [comment]
So to solve this issue, you have to turn Keyring setting off in Linux system with your user password. This is the only possible way

**Comment by tracywalker** [comment]
Search your system for Startup Applications. Open the dialog then disable the Gnome Keyring.

**Comment by pavelciapa** [comment]
Here is good guide:
http://ask.xmodulo.com/disable-entering-password-unlock-default-keyring.html

**Comment by pavelciapa** [comment]
Added correspondent configuration on github wiki:
https://github.com/mozilla/iris/wiki/Setup
