### ISSUE TITLE
Fix downloads_button_works_properly_positioned_in_the_tabs_bar

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2590]
LINUX

library_open_all_in_tabs - Open all the history from a history time range.                                 By: IonutBudeanu
--
1 | 8:56:02 PM | Mozilla page loaded successfully.
2 | 8:56:20 PM | Iris page is displayed in the History menu list.
3 | 8:56:22 PM | Today history option is available.
4 | 8:56:32 PM | 019-03-19 20:56:32,462 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test

**Comment by yeyartsev** [comment]
Can not reproduce failure before first step: 
"Error encountered in test" for Win 7 with the following stacktrace:
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                                       
>>     current.run()                                                                                                           
>>   File "c:\iris\iris\tests\download_manager\downloads_button_works_properly_positioned_in_the_tabs_bar.py", line 36, in run 
>>     click_hamburger_menu_option('Customize...')                                                                             
>>   File "c:\iris\iris\api\helpers\general.py", line 184, in click_hamburger_menu_option                                      
>>     'Can\'t find the option in the page, aborting test.')                                                                   
>> APIHelperError: Can't find the option in the page, aborting test.
