### ISSUE TITLE
Fix for firefox_hijacking_default_search

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2596]
There are difference  that wasn't described in description between the Default Search Engines list in Firefox that was running by Iris and Firefox that we running manually. When Firefox running via Iris there is Ebay Search engine in the list. When it running manually there is no Ebay Search engine.
Test will be reworked with adding Ebay Search engine.

**Comment by tracywalker** [comment]
This happens because the Iris profile was created and used in USA.  You can make your local manual Firefox run the same by changing the about config for browser.search.region to 'US'

**Comment by spronoza** [comment]
Thanks, we did it already.
