### ISSUE TITLE
Modify run_update_suite.sh to take a combined version/locale parameter

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#2597]
`run_update_suite.sh` currently takes a locales and versions as separate parameters, then pairs them in the order specified. Eg. `--locales=de,fr,ro --versions=65.0,66.0,67.0` will test 65.0 de, 66.0 fr, and 67.0 ro.

To simplify and provide more flexibility in the script I propose we combine the version/locale into a build parameter using *version_locale* notation, eg. 64.0b10_en-US. The script can then generate commands specific to that version/locale combination.

Doing it this way will also allow us to support generating commands from a manifest of version/locale coverage for Release QA more easily in the future.

I have a patch forthcoming.

**Comment by tracywalker** [comment]
code approved
