### ISSUE TITLE
Local solution for the Download manager tests test page

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2610]
Currently the download manager tests use https://www.thinkbroadband.com/download. Lately this has become unreliable with 404 responses.  

I'm filing this issue to investigate and propose solutions that will be under our control.

**Comment by pavelciapa** [comment]
This issue is very critical, because fails of download_manager tests can fail whole test run.

**Comment by tracywalker** [comment]
We should investigate why a 404 of this site causes full test run failure.  I have a feeling the 404 and full test run failures are separate issues.  Let's find out.

**Comment by pavelciapa** [comment]
Test run failed after test case downloads_button_works_properly_positioned_in_the_tabs_bar.  Single test fails on line 52: download_file() method

**Comment by icrisan** [comment]
@pavelciapa  please provide more details. A stack trace would help. On line 52 we have the following code: download_file(pattern, DownloadFiles.OK). Maybe the "OK" button is not found on your machine.

**Comment by pavelciapa** [comment]
Here is stack trace from Iris log file with two last tests:
Most of test in download_manager failed

-----------------------------
2019-03-27 21:22:16,645 [INFO] [iris.test_runner] Executing: 204 - [downloading_by_drag_and_drop]: Downloading by Drag & Drop.
2019-03-27 21:22:40,728 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Downloads button successfully activated in the nav bar.
2019-03-27 21:23:31,331 [WARNING] [iris.test_case] >>> FAILED <<< Step 2: The downloaded file name is properly displayed in the Downloads panel. - [Actual]: False [Expected]: True 

---------------------------------------------------------------------------------------------------------------
>> Traceback (most recent call last):                                                                        <<
>>   File "/Users/dev/.local/share/virtualenvs/iris-GK6srotc/bin/iris", line 11, in <module>                 <<
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                 <<
>>   File "/Users/dev/iris/iris/__main__.py", line 38, in main                                               <<
>>     run_iris()                                                                                            <<
>>   File "/Users/dev/iris/iris/__main__.py", line 108, in run_iris                                          <<
>>     run(master_test_list, tests, browser)                                                                 <<
>>   File "/Users/dev/iris/iris/test_runner.py", line 69, in run                                             <<
>>     current.run()                                                                                         <<
>>   File "/Users/dev/iris/iris/tests/download_manager/downloading_by_drag_and_drop.py", line 49, in run     <<
>>     assert_true(self, expected, 'The downloaded file name is properly displayed in the Downloads panel.') <<
>>   File "/Users/dev/iris/iris/asserts.py", line 78, in assert_true                                         <<
>>     assert_equal(test_case, actual, True, message)                                                        <<
>>   File "/Users/dev/iris/iris/asserts.py", line 32, in assert_equal                                        <<
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))    <<
---------------------------------------------------------------------------------------------------------------

2019-03-27 21:23:32,714 [INFO] [iris.api.helpers.results] [downloading_by_drag_and_drop] - >>> FAILED <<< (Finished in 74.69 second(s))

2019-03-27 21:23:32,721 [INFO] [iris.test_runner] 
------------------------------------------------------------------------------------------------------------------------
2019-03-27 21:23:32,723 [INFO] [iris.test_runner] Executing: 205 - [downloads_button_works_properly_positioned_in_the_tabs_bar]: The downloads button works properly positioned in the tabs bar.
2019-03-27 21:23:52,219 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 1: Download button is available.
2019-03-27 21:23:57,370 [SUCCESS] [iris.test_case] >>> PASSED <<< Step 2: Custom Download button is available in tabs bar.

**Comment by pavelciapa** [comment]
Stack trace ends suddenly because test run hung and I had to stop test run manually. 
When opened IDE it started printing some hotkey to console, as trying to close_window

And I stoped test run by pressing CTLR+C in console. 

This happened few times when test case from download_manager failed test run

![Screen Shot 2019-03-28 at 13 27 04](https://user-images.githubusercontent.com/45387203/55154341-3c7acd00-515d-11e9-85f0-65bdadc9b031.png)

Line 52 I mentioned above was error when I tried to run this test case single after I stopped this run

**Comment by icrisan** [comment]
@pavelciapa on which OS did you manage to reproduce this?

**Comment by icrisan** [comment]
@pavelciapa from the stack trace that you provided for test case "downloading_by_drag_and_drop" can be seen that it didn't fail with an ERROR so even though it fails on your side we should put it on hold a bit because it does not make the entire run to FAIL. The "downloads_button_works_properly_positioned_in_the_tabs_bar" test case should be indeed investigated more deeply because it ends with an ERROR. As you can see this test case ("downloads_button_works_properly_positioned_in_the_tabs_bar") failed today on our side on LINUX but it didn't end with an ERROR. Alin will provide more details about the failure from our side.

**Comment by alinrus** [comment]
Hi all,
**downloads_button_works_properly_positioned_in_the_tabs_bar** fails randomly only on Linux platform ,mostly on the machine test, all the time at:
_line 60, in run <<
>>     assert_true(self, expected, 'Download button turns back to default color.')_   

The reason behind is because the _downloads_library_ window is opened over the _Downloads_ button, that's why is not spotted.  This type of fail cannot influence the following tests results, we should not be concerned about this. Anyway, I will come up with the fix to have covered this unusual Linux behavior.

**Comment by pavelciapa** [comment]
>
>
> As you can see this test case ("downloads_button_works_properly_positioned_in_the_tabs_bar") failed today on our side on LINUX but it didn't end with an ERROR. 

@icrisan it's not about certain test but mostly about test cases from download_manager that can cause run to fail. 

Sorry for wrong reaction, I will add all full stack trace from failed run here.

**Comment by pavelciapa** [comment]
[iris_log.log](https://github.com/mozilla/iris/files/3018143/iris_log.log)

**Comment by icrisan** [comment]
Hmmm, seems that all the downloads test cases failed from the same cause like the below test case:
193 - [about_downloads_accurate_data]: "about:downloads" displays accurate data.
2019-03-27 21:15:34,154 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test 

------------------------------------------------------------------------------------------------------------
>> Traceback (most recent call last):                                                                     <<
>>   File "/Users/dev/iris/iris/test_runner.py", line 69, in run                                          <<
>>     current.run()                                                                                      <<
>>   File "/Users/dev/iris/iris/tests/download_manager/about_downloads_accurate_data.py", line 39, in run <<
>>     download_file(pattern, DownloadFiles.OK)                                                           <<
>>   File "/Users/dev/iris/iris/api/helpers/download_manager_utils.py", line 94, in download_file         <<
>>     raise APIHelperError('The \'Save file\' option is not present in the page, aborting.')             <<
>> APIHelperError: The 'Save file' option is not present in the page, aborting.                           <<
------------------------------------------------------------------------------------------------------------

**Comment by icrisan** [comment]
The SAVE_FILE pattern does not work for you. Could you please add the debug image where that pattern is searched to see if it exists and it just don't match our pattern or it does not exist at all. Thank you!

**Comment by pavelciapa** [comment]
Yes, you are right, often the reason is in save_file pattern but not always.

![2019_03_27_21_15_28_242538_about_downloads_accurate_data](https://user-images.githubusercontent.com/45387203/55164803-021d2a00-5175-11e9-8cb7-b7049a7b8920.jpg)
![2019_03_27_21_15_29_175788_about_downloads_accurate_data_not_found](https://user-images.githubusercontent.com/45387203/55164805-02b5c080-5175-11e9-8e9e-fa781cbe596a.jpg)
![2019_03_27_21_15_30_197434_about_downloads_accurate_data_not_found](https://user-images.githubusercontent.com/45387203/55164806-02b5c080-5175-11e9-90f9-9bd0d624098a.jpg)

**Comment by alinrus** [comment]
That's interesting! Seems that you're having connection issues during the scenario with downloading actions. I'm curious if it's happening only on your test machine or not and if you managed to reproduce this by doing manually this steps, would be a good point also. 
On our side, it isn't a familiar issue, I took a look on previous reports to see if there is a pattern for this failure, but it's not.

**Comment by pavelciapa** [comment]
Yes, webpage sometimes doesn't load. 
It is reproducable manually. External page doesn't load. I checked right now it has gives same error when I try to download file. But tommorow same time or in few hours it can work again.

**Comment by alinrus** [comment]
In this case, since you are able to reproduce it also manually, I'm wondering if you don't have some network limitations in downloading content from external pages. On our side, we never experienced this. 
@tracywalker have you experienced these connection issues by running these downloading scenarios?

**Comment by pavelciapa** [comment]
> In this case, since you are able to reproduce it also manually, I'm wondering if you don't have some network limitations in downloading content from external pages. 

We don't have extra limitations. Comment of @tracywalker would be helpful here

**Comment by tracywalker** [comment]
I have seen it, though very infrequently.  It may be the site getting overloaded at times.  In any case, we need to explore a local solution or Mozilla controlled solution for these tests. We could make a page that points to download files for various Mozilla products/files.

**Comment by tracywalker** [comment]
Iris 1 doesn't have robust enough server to be able to serve download files. So creating fake coy of the test site won't potentially work until Iris 2, if even then.  

I’d rather our team not have to rewrite the test cases to point to Mozilla assets, until we determine if Iris 2 will be able to do what we need or not.

Until then, we'll just have to live with intermittent failures.

As far as any of these test cases causing Iris to error/fail all remaining tests in a test run,  that would have to be investigated independently of creating a more reliable test page.  If that is the actual case, please open a separate issue.

Leaving this open so we don't miss it when we cut over to Iris 2.

**Comment by pavelciapa** [comment]
Maybe there is a possibility to enhance these tests, in order them not to fail whole run.
For example investigate if try...except block would change a situation with fail of whole run. Its just my theory

**Comment by tracywalker** [comment]
Please file another issue for that.  I want to see proof first that the test page loading failure is somehow causing entire test run failure.

**Comment by pavelciapa** [comment]
I described this situation above with screens and log, where test run stopped, and when opening IDE or terminal, it starts typing key combinaiton which is supposed to cancel run or quit Firefox to force browser restart

**Comment by tracywalker** [comment]
Ioana,  I just spoke with Matt. He believes our local server should work. File types and perhaps permissions on server side need to be talked about.  Please work with core team to figure this out. Then you can create a look-alike page for the tests.

**Comment by spronoza** [comment]
The failure is reproducible number_of_downloads_properly_truncated

**Comment by spronoza** [comment]
The failure is reproducible for user_is_prompted_when_trying_to_close_the_browser_while_downloading

**Comment by spronoza** [comment]
The failure is reproducible for user_is_prompted_when_trying_to_close_the_private_window_while_downloading

**Comment by spronoza** [comment]
The failure is reproducible for notifications_are_displayed_for_finished_or_new_downloads

**Comment by spronoza** [comment]
The failure is reproducible for dropmarker_in_rtl

**Comment by spronoza** [comment]
The failure is still reproducible for downloads_button_works_properly_positioned_in_the_tabs_bar

**Comment by spronoza** [comment]
The failure is reproducible for download_summary

**Comment by spronoza** [comment]
The failure is reproducible for download_links_can_be_copied_via_drag_and_drop_and_context_menu

**Comment by spronoza** [comment]
The failure is reproducible for clear_preview_panel_while_downloading on  Linux

**Comment by spronoza** [comment]
The failure is reproducible for clear_download_preview_panel on Linux

**Comment by spronoza** [comment]
The failure is reproducible for clear_download_history on Linux

**Comment by spronoza** [comment]
The failure is reproducible for about_downloads_accurate_data on Linux

**Comment by tracywalker** [comment]
Please stop posting reports about which of these tests is failing. It is not helpful in resolving the issue and is only spamming our email inboxes.

Ioana has a local server solution in place on her branch, However, the downloads now run so fast that many of the test fail, because they can't get to asserts fast enough (download completes too quickly). We're investigating ways to slow down the downloads either on the server side or in Firefox.

**Comment by spronoza** [comment]
Ок. Sorry. We will create separate issue to track tests that failing by that reason.

**Comment by tracywalker** [comment]
No,  if they are all failing for the same reason that is already covered here.  There is no need for even more spam.

**Comment by tracywalker** [comment]
Code approved with a known issue in Tesseract on Win7 and 1 or 2 failing tests. We'll have a hack to work around the Tesseract issue.  We can work on solving the failing tests in new issues for them.
