### ISSUE TITLE
Adjust test_case.py to deal with some annoying dialogs

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#2611]
We're seeing the content blocking dialog and a new dialog for extensions in private windows appearing quite often.  In many cases these dialogs aren't interfering with tests.  But in many others they are causing tests to fail.

I propose we, by default, in our pre-canned profiles, disable these dialogs by pref.

extensions.privatebrowsing.notification to true
and I think setting browser.contentblocking.introCount to 20 will stop the content blocking dialog. (that will have to be tested out)

Matt, if you could briefly explain how to make changes to the profile.  I'll attempt to fix this.

**Comment by mwobensmith** [comment]
Touching these profiles can cause other side effects that need to be tested. Let's chat face to face about that. The easiest workaround right now is to edit the base test case class in `test_case.py` and set these prefs in the `setup` method. There is already one dummy pref that we set there - just use that format to set the default prefs you desire for all tests.
```
self.set_profile_pref({'iris.enabled': True})
```

**Comment by tracywalker** [comment]
I'll give it a go with adding

```
self.set_profile_pref({'extensions.privatebrowsing.notification': False})
```
and
```
self.set_profile_pref({'browser.contentblocking.introCount': 20})
```

**Comment by tracywalker** [comment]
Setting the prefs in test_case.py works to block these dialogs.  If you have a test case that needs these dialog,  you'll have to override in BaseTest.setup(self) in the test case itself.
