### ISSUE TITLE
Method navigate() after new_tab/window causing test case fail

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2708]
Method navigate() not pasting url into address bar, or pasting and navigating space, with opening Google as default search engine. 

It is observed more often when navigate() follows new_private_window(), and less often after new_window()/new_tab()

This happens 1 of 5 runs on OSX machine, and other machins also

    
```
new_private_window()

private_browsing_tab_logo = exists(private_browsing_tab_logo_pattern, Settings.FIREFOX_TIMEOUT)
assert_true(self, private_browsing_tab_logo, 'A new private window is successfully loaded.')

navigate('about:preferences#privacy')

navigated_to_preferences = exists(preferences_privacy_find_field_pattern, Settings.FIREFOX_TIMEOUT)
assert_true(self, navigated_to_preferences, 'Preferences/privacy page successfully loaded.')
```

## Screens, founded new private tab, navigated empty line, and looking for pattern on awaited url

![image](https://user-images.githubusercontent.com/45387203/55488335-8de0fb80-5638-11e9-8eaf-40d50ff4299f.png)
![image](https://user-images.githubusercontent.com/45387203/55488358-9a655400-5638-11e9-8e79-b2ff5f7c7f26.png)

## Another case, pasting space, and opening Google as default search engine:

![image](https://user-images.githubusercontent.com/45387203/55488461-cc76b600-5638-11e9-9ecf-5bdb3bc7cf0c.png)
![image](https://user-images.githubusercontent.com/45387203/55488533-efa16580-5638-11e9-9e2f-70abfa7787b6.png)
![image](https://user-images.githubusercontent.com/45387203/55488566-f8923700-5638-11e9-93ee-93c29406f6de.png)

**Comment by tracywalker** [comment]
It is most likely that, intermittently, the paste(url) is happening before the location bar actually gets focus. In the navigate() helper, add a small time.sleep between the calls to select_location_bar() and paste().
```
    try:
        select_location_bar()
       ~~~ add time.sleep here ~~~
        paste(url)
type(Key.ENTER)
```

**Comment by tracywalker** [comment]
While you're doing that, add the same time.sleep to the next function in general.py,  navigate_slow()

**Comment by tracywalker** [comment]
Instead, change the time.sleep in the keyboard shortcut for select_location_bar() to something longer.
