### ISSUE TITLE
Fix "dropmarker_in_rtl" test case

### ISSUE THREAD

**Issue by alinrus** [mozilla/iris#2728]

**Comment by tracywalker** [comment]
code approved

**Comment by pavelciapa** [comment]
Change Firefox config by using method `change_preference()`, to minimize fails

**Comment by yeyartsev** [comment]
Cannot reproduce failure after step 12: "Error encountered in test" for Win 7 with the following stacktrace:
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                   
>>     current.run()                                                                       
>>   File "c:\iris\iris\tests\download_manager\dropmarker_in_rtl.py", line 81, in run      
>>     download_file(f, DownloadFiles.OK)                                                  
>>   File "c:\iris\iris\api\helpers\download_manager_utils.py", line 166, in download_file 
>>     raise APIHelperError('File to be downloaded not found.')                            
>> APIHelperError: File to be downloaded not found.
