### ISSUE TITLE
Fix saved_cc_available_in_private_session

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2736]
Seems that visa_logo.png looks different in win10 now. Will replace

old:
![image](https://user-images.githubusercontent.com/45387203/55717665-7cb23900-5a02-11e9-9354-3a8515f961dd.png)

new:
![image](https://user-images.githubusercontent.com/45387203/55717649-702de080-5a02-11e9-9289-d73a393a145a.png)

 saved_cc_available_in_private_session - Credit Card form inputs that were previously saved in a normal session are remembered in Private Browsing session
8:24:58 PM
Preferences page is opened
8:24:59 PM
'Saved addresses' button is displayed on the Preferences page
8:25:00 PM
'Add' button is displayed on the 'Saved addresses' popup
8:25:02 PM
'First Name' field is displayed on the 'Add new address' popup
8:25:05 PM
'Save' button is displayed on the 'Add new address' popup
8:25:09 PM
Address list popup dissapeared.
8:25:09 PM
'Saved credit cards' button is displayed on the Preferences page
8:25:11 PM
'Add' button is displayed on the 'Saved credit cards' popup
8:25:13 PM
'Card type' dropdown is displayed on the 'Edit Credit Card' popup
8:25:15 PM
'Visa' option is available on the 'Card type' dropdown
8:25:16 PM
'Card Number' field is displayed on the 'Edit Credit Card' popup
8:25:18 PM
'Name on card' field is displayed on the 'Edit Credit Card' popup
8:25:21 PM
'Expiration month' dropdown is displayed on the 'Edit Credit Card' popup
8:25:22 PM
'05 - May' option is displayed on the dropdown 'Expiration month'
8:25:24 PM
'Expiration year' dropdown is displayed on the 'Edit Credit Card' popup
8:25:25 PM
'2029' option is available on the 'Expiration year' dropdown
8:25:27 PM
'Billing address' dropdown is displayed on the 'Edit Credit Card' popup
8:25:28 PM
Previously saved address displayed on the 'Billing address' dropdown
8:25:30 PM
'Save' button is displayed on the 'Edit Credit Card' popup
8:25:41 PM
Credit card was successfully saved - [Actual]: False [Expected]: True

**Comment by pavelciapa** [comment]
Can not reproduce failure described at step: "Credit card was successfully saved - [Actual]: False [Expected]: True" for Win 10 with the following stacktrace:
--
>> Traceback (most recent call last):                                                                       
>>   File "C:\Users\svuser\.virtualenvs\iris-NcrgrEXF\Scripts\iris-script.py", line 11, in <module>         
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                
>>   File "c:\iriscron2\iris\iris\__main__.py", line 38, in main                                            
>>     run_iris()                                                                                           
>>   File "c:\iriscron2\iris\iris\__main__.py", line 108, in run_iris                                       
>>     run(master_test_list, tests, browser)                                                                
>>   File "c:\iriscron2\iris\iris\test_runner.py", line 69, in run                                          
>>     current.run()                                                                                        
>>   File "c:\iriscron2\iris\iris\tests\privacy\saved_cc_available_in_private_session.py", line 173, in run 
>>     assert_true(self, credit_card_successfully_saved, 'Credit card was successfully saved')              
>>   File "c:\iriscron2\iris\iris\asserts.py", line 78, in assert_true                                      
>>     assert_equal(test_case, actual, True, message)                                                       
>>   File "c:\iriscron2\iris\iris\asserts.py", line 32, in assert_equal                                     
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by pavelciapa** [comment]
Test showed a bug in markup. Filed in Bugzilla
![image](https://user-images.githubusercontent.com/45387203/61459397-28511a80-a95c-11e9-808d-fd7bbfa4d489.png)

https://testrail.stage.mozaws.net/index.php?/cases/view/294453

**Comment by tracywalker** [comment]
Please post that in issue #3445
