### ISSUE TITLE
Psutil library fails to initialize Subprocess.process PID on Win Os

### ISSUE THREAD

**Issue by mariusandreifilip** [mozilla/iris#275]
c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\psutil\__init__.py:446: in __init__
    self._init(pid)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = psutil.Process(pid=10992, status='terminated'), pid = 10992, _ignore_nsp = False

    def _init(self, pid, _ignore_nsp=False):
        if pid is None:
            pid = os.getpid()
        else:
            if not _PY3 and not isinstance(pid, (int, long)):
                raise TypeError('pid must be an integer (got %r)' % pid)
            if pid < 0:
                raise ValueError('pid must be a positive integer (got %s)'
                                 % pid)
        self._pid = pid
        self._name = None
        self._exe = None
        self._create_time = None
        self._gone = False
        self._hash = None
        self._lock = threading.RLock()
        # used for caching on Windows only (on POSIX ppid may change)
        self._ppid = None
        # platform-specific modules define an _psplatform.Process
        # implementation class
        self._proc = _psplatform.Process(pid)
        self._last_sys_cpu_times = None
        self._last_proc_cpu_times = None
        # cache creation time for later use in is_running() method
        try:
            self.create_time()
        except AccessDenied:
            # We should never get here as AFAIK we're able to get
            # process creation time on all platforms even as a
            # limited user.
            pass
        except ZombieProcess:
            # Zombies can still be queried by this class (although
            # not always) and pids() return them so just go on.
            pass
        except NoSuchProcess:
            if not _ignore_nsp:
                msg = 'no process found with pid %s' % pid
>               raise NoSuchProcess(pid, None, msg)
E               psutil.NoSuchProcess: psutil.NoSuchProcess no process found with pid 10992

c:\users\andrei.filip\.virtualenvs\iris2-icp0-hfb\lib\site-packages\psutil\__init__.py:486: NoSuchProcess

**Comment by mariusandreifilip** [comment]
Fixed in issue_275 by using a ctype approach for win os

**Comment by mwobensmith** [comment]
Fixed
