### ISSUE TITLE
Fix cnn_heavy_content test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2759]
The test fails at step: "None - [Actual]: None [Expected]: None" for OSX

**Comment by spronoza** [comment]
The failure is still reproducible for Linux

**Comment by spronoza** [comment]
Fixed in #2756

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: "Another video is displayed - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>          
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                         
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                              
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                      
>>   File "c:\iris\iris\tests\plugin_compatibility\cnn_heavy_content.py", line 54, in run                 
>>     assert_true(self, another_video_exists, 'Another video is displayed')                              
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))
