### ISSUE TITLE
Fix tls_authentication test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2763]
Can not reproduce failure described at step: "Cloudflare page is successfully downloaded - [Actual]: False [Expected]: True" for Linux with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/home/user/.local/share/virtualenvs/iris-s-cvVCBB/bin/iris", line 11, in <module>              
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/home/user/iris/iris/__main__.py", line 38, in main                                            
>>     run_iris()                                                                                         
>>   File "/home/user/iris/iris/__main__.py", line 108, in run_iris                                       
>>     run(master_test_list, tests, browser)                                                              
>>   File "/home/user/iris/iris/test_runner.py", line 69, in run                                          
>>     current.run()                                                                                      
>>   File "/home/user/iris/iris/tests/antivirus_interoperability/tls_authentication.py", line 105, in run 
>>     assert_true(self, cloudflare_logo_displayed, 'Cloudflare page is successfully downloaded')         
>>   File "/home/user/iris/iris/asserts.py", line 78, in assert_true                                      
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "/home/user/iris/iris/asserts.py", line 32, in assert_equal                                     
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: "TLS client certificate authentication mechanism will not be broken. No errors occur - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>                        
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                            
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                                  
>>     run_iris()                                                                                                       
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                                             
>>     run(master_test_list, tests, browser)                                                                            
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                                
>>     current.run()                                                                                                    
>>   File "c:\iris\iris\tests\antivirus_interoperability\tls_authentication.py", line 113, in run                       
>>     assert_true(self, cloudflare_support_page_displayed, 'TLS client certificate authentication mechanism will not ' 
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                                            
>>     assert_equal(test_case, actual, True, message)                                                                   
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                                           
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))
