### ISSUE TITLE
Fix reader_view_enabled test

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris#2773]
Can not reproduce failure described at step: "Scroll up and down using mouse wheel is successful. - [Actual]: False [Expected]: True" for OSX with the following stacktrace:
---
>> Traceback (most recent call last):                                                                        
>>   File "/Users/admin/.local/share/virtualenvs/iris-edWfnQv0/bin/iris", line 11, in <module>               
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                 
>>   File "/Users/admin/iris/iris/__main__.py", line 38, in main                                             
>>     run_iris()                                                                                            
>>   File "/Users/admin/iris/iris/__main__.py", line 108, in run_iris                                        
>>     run(master_test_list, tests, browser)                                                                 
>>   File "/Users/admin/iris/iris/test_runner.py", line 69, in run                                           
>>     current.run()                                                                                         
>>   File "/Users/admin/iris/iris/tests/content_scroll/reader_view_enabled.py", line 49, in run              
>>     assert_true(self, after_scroll_content_exists, 'Scroll up and down using mouse wheel is successful.') 
>>   File "/Users/admin/iris/iris/asserts.py", line 78, in assert_true                                       
>>     assert_equal(test_case, actual, True, message)                                                        
>>   File "/Users/admin/iris/iris/asserts.py", line 32, in assert_equal                                      
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: "The website is properly loaded in Reader View. - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>          
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                         
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                              
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                      
>>   File "c:\iris\iris\tests\content_scroll\reader_view_enabled.py", line 34, in run                     
>>     assert_true(self, reader_view_button_exists, 'The website is properly loaded in Reader View.')     
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by nevdokimov** [comment]
Cannot reproduce on the step 1 for OSX platform: The website is properly loaded. - [Actual]: False [Expected]: True
