### ISSUE TITLE
Fix search_using_one_offs_while_maximizing_or_minimizing_window test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2805]
Can not reproduce failure described at step: "Searched item is successfully found in the page opened by the default search engine. - [Actual]: False [Expected]: True" for Linux

**Comment by pavelciapa** [comment]
Using method exists() to search a String is not stable.
`        expected = region.exists('Moz', 10)`

Fix issue by selecting proper region or creating new patterns
