### ISSUE TITLE
Fix drop_txt_file test

### ISSUE THREAD

**Issue by nevdokimov** [mozilla/iris#2825]
Can not reproduce failure described at step: "TXT test file is available - [Actual]: False [Expected]: True" for Win 10 with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "C:\Users\evdokimov\.virtualenvs\iris-oX-b2_9c\Scripts\iris-script.py", line 11, in <module>    
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "d:\iris\iris\__main__.py", line 38, in main                                                    
>>     run_iris()                                                                                         
>>   File "d:\iris\iris\__main__.py", line 108, in run_iris                                               
>>     run(master_test_list, tests, browser)                                                              
>>   File "d:\iris\iris\test_runner.py", line 69, in run                                                  
>>     current.run()                                                                                      
>>   File "d:\iris\iris\tests\drag_and_drop\drop_txt_file.py", line 136, in run                           
>>     assert_true(self, test_file_txt, 'TXT test file is available')                                     
>>   File "d:\iris\iris\asserts.py", line 78, in assert_true                                              
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "d:\iris\iris\asserts.py", line 32, in assert_equal                                             
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by yeyartsev** [comment]
Test fails against Win 7 at step 2:
The drop-txt-file changed color to red which indicates that it has been selected. - [Actual]: False [Expected]: True

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: "Not Matching appears under the "Drop Stuff Here" area and expected result is different from result. - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>                      
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                          
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                                
>>     run_iris()                                                                                                     
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                                           
>>     run(master_test_list, tests, browser)                                                                          
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                              
>>     current.run()                                                                                                  
>>   File "c:\iris\iris\tests\drag_and_drop\drop_txt_file.py", line 153, in run                                       
>>     assert_true(self, not_matching_message_displayed, 'Not Matching appears under the "Drop Stuff Here" area and ' 
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                                          
>>     assert_equal(test_case, actual, True, message)                                                                 
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                                         
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))
