### ISSUE TITLE
Fix copy_site_from_library_paste_it_on_bookmark_toolbar test

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2850]
Can not reproduce failure described at step: "019-04-12 09:36:56,173 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test" for OSX

**Comment by yeyartsev** [comment]
Can not reproduce failure after first step described as: 
"Error encountered in test" for Win 7 with the following stacktrace:
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                       
>>     current.run()                                                                                           
>>   File "c:\iris\iris\tests\history\copy_site_from_library_paste_it_on_bookmark_toolbar.py", line 32, in run 
>>     open_library_menu('History')                                                                            
>>   File "c:\iris\iris\api\helpers\general.py", line 993, in open_library_menu                                
>>     'Can\'t find the option in the page, aborting test.')                                                   
>> APIHelperError: Can't find the option in the page, aborting test.
