### ISSUE TITLE
Fix drop_png_image test

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#2856]
Can not reproduce failure described at step: "The demo website loaded successfully - [Actual]: False [Expected]: True" for OSX with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/Users/admin/.local/share/virtualenvs/iris-edWfnQv0/bin/iris", line 11, in <module>            
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/Users/admin/iris/iris/__main__.py", line 38, in main                                          
>>     run_iris()                                                                                         
>>   File "/Users/admin/iris/iris/__main__.py", line 108, in run_iris                                     
>>     run(master_test_list, tests, browser)                                                              
>>   File "/Users/admin/iris/iris/test_runner.py", line 69, in run                                        
>>     current.run()                                                                                      
>>   File "/Users/admin/iris/iris/tests/drag_and_drop/drop_png_image.py", line 54, in run                 
>>     assert_true(self, drop_png_data_button_displayed, 'The demo website loaded successfully')          
>>   File "/Users/admin/iris/iris/asserts.py", line 78, in assert_true                                    
>>     assert_equal(test_case, actual, True, message)                                                     
>>   File "/Users/admin/iris/iris/asserts.py", line 32, in assert_equal                                   
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: "Matching appears under the "Drop Stuff Here" area and expected result is identical to result.  - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>                       
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                           
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                                 
>>     run_iris()                                                                                                      
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                                            
>>     run(master_test_list, tests, browser)                                                                           
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                               
>>     current.run()                                                                                                   
>>   File "c:\iris\iris\tests\drag_and_drop\drop_png_image.py", line 147, in run                                       
>>     assert_true(self, matching_message_displayed, 'Matching appears under the "Drop Stuff Here" area and expected ' 
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                                           
>>     assert_equal(test_case, actual, True, message)                                                                  
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                                          
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))
