### ISSUE TITLE
Fix copy_history_time_range_paste_it_bookmark_toolbar test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2898]
The test fails at step: "019-04-17 13:16:46,355 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test" for OSX

**Comment by tracywalker** [comment]
This was already filed as issue #2851.  Please check for existing duplicates before filing new issues. 

I am going to mark the original a duplicate of this. since that issue says it cannot reproduce and this one say the test fails.
