### ISSUE TITLE
Fix history_sidebar_forget_site test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2903]
The test fails at step: "019-04-18 00:30:53,183 [ERROR] [iris.test_case] >>> ERROR <<< Error encountered in test" for OSX

**Comment by tracywalker** [comment]
Why wasn't open_library_menu() made more stable instead of the workaround implemented in the test case.  We want to use helpers as much as possible so issue like this can be fixed in one place, instead of in individual test cases.

**Comment by spronoza** [comment]
We created issue to made  open_library_menu() more stable. Workaround it is a temporary solution.

**Comment by tracywalker** [comment]
I know there is an issue on file for open_library_menu.  Implementing workarounds to it in individual test cases will just have to be undone later.  Fix the underlying issue first. so you're not spending development time reworking test cases twice.
