### ISSUE TITLE
Fix default_search_code_google test

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#2916]
The test fails at step: "Client search code is correct for searches from search bar, region US. - [Actual]: https://www.google.com/webhp?client=firefox-b-1-d [Expected]: https://www.google.com/search?client=firefox-b-1-d&q=test" for Linux with the following stacktrace:

>> Traceback (most recent call last):                                                                     
>>   File "/home/user/.local/share/virtualenvs/iris-s-cvVCBB/bin/iris", line 11, in <module>              
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                              
>>   File "/home/user/iris/iris/__main__.py", line 38, in main                                            
>>     run_iris()                                                                                         
>>   File "/home/user/iris/iris/__main__.py", line 108, in run_iris                                       
>>     run(master_test_list, tests, browser)                                                              
>>   File "/home/user/iris/iris/test_runner.py", line 69, in run                                          
>>     current.run()                                                                                      
>>   File "/home/user/iris/iris/tests/search/default_search_code_google.py", line 100, in run             
>>     'Client search code is correct for searches from search bar, region ' + value + '.')               
>>   File "/home/user/iris/iris/asserts.py", line 32, in assert_equal                                     
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))

**Comment by tracywalker** [comment]
This was already filed in issue #2861.  Please check for existing duplicates before filing new issues.
