### ISSUE TITLE
Implement API: isLockOn() (Key method)

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#301]

**Comment by mwobensmith** [comment]
Probably do `Key.isLockOn()` at same time.

**Comment by silviuFlorin** [comment]
From Sikuli documentation: 

> The class Env is deprecated and should not be used anymore. The contained features are moved to other places and redirected from inside class Env to be downward compatibel.

Key.isLockOn() is the equivalent of the deprecated isLockOn() Env method. 
I created issue #416 to log errors when Env methods are called.

@mwobensmith can you please review this issue and close it if it's not needed anymore?

**Comment by mwobensmith** [comment]
Renaming issue to reflect correct API.

**Comment by mwobensmith** [comment]
This is working for me. Good job!

Here are some changes that you should make.

* The `Env` class is deprecated. Move this method out of the `Env` class and into the `Key` class. Make it a static method. In the `Env` class, put a `UnsupportedMethodError` if someone tries to use it there, just like the other methods in that class. 

* In the `Key.isLockDown` method, put the code from `is_button_pressed` instead of having it as a separate method outside the class.

* In `keyboard_shortcuts.py`, remove the logic that you put in the method `clear_recent_history`. In fact, this file should be reverted to the previous state that it is in the 'dev' branch. The work for this Git issue only covers the API. I will file a new issue to use the API in Iris to shut down the test suite if we detect any of these keys are locked. 

* I noticed that, on Mac, the XQuartz app is open and displayed in the dock. Is there any way to quit this app (via `subprocess` etc.) when we are done with it? I'd rather not leave it hanging around. Let me know what you can find out about this.

* In PyCharm, run _Code > Inspect Code..._ on `core.py` to flag all of the PEP 8 violations. Some of these are known and acceptable, but it will show you some whitespace violations in your code - mainly around operators. These should be fixed.

This will be a breaking change for current Iris developers on Mac, as they need to run the bootstrap script. They will also have to restart their computer to allow XQuartz to set up properly. I will send out an email, as well as update the wiki setup instructions.
