### ISSUE TITLE
Fix drop_png_image_in_private_window test

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#3063]
Fails intermittently on step 10 on Windows 7

**Comment by yeyartsev** [comment]
Can not reproduce failure described at step: "'Select a bookmark backup' window is available - [Actual]: False [Expected]: True" for Win 7 with the following stacktrace:
>>   File "C:\Users\dev\.virtualenvs\iris-LqBaZ-qX\Scripts\iris-script.py", line 11, in <module>              
>>     load_entry_point('iris', 'console_scripts', 'iris')()                                                  
>>   File "c:\iris\iris\__main__.py", line 38, in main                                                        
>>     run_iris()                                                                                             
>>   File "c:\iris\iris\__main__.py", line 108, in run_iris                                                   
>>     run(master_test_list, tests, browser)                                                                  
>>   File "c:\iris\iris\test_runner.py", line 69, in run                                                      
>>     current.run()                                                                                          
>>   File "c:\iris\iris\tests\drag_and_drop\drop_png_image_in_private_window.py", line 111, in run            
>>     assert_true(self, select_bookmark_popup_available, '\'Select a bookmark backup\' window is available') 
>>   File "c:\iris\iris\asserts.py", line 78, in assert_true                                                  
>>     assert_equal(test_case, actual, True, message)                                                         
>>   File "c:\iris\iris\asserts.py", line 32, in assert_equal                                                 
>>     Result('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))))
