### ISSUE TITLE
Create new profile with Saved Logins for test_case: 245730

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#3171]
(https://testrail.stage.mozaws.net/index.php?/cases/view/245730)
#2975 , Test_case: 245730 has preconditions:
>     Antivirus is installed.
>     Several logins (user/password) are saved for at least one website.

Create profile with pre-saved fake login(s) to twitter, wikipedia, etc. 

![image](https://user-images.githubusercontent.com/45387203/57281598-fe55bf00-70b3-11e9-95e8-768bea874a71.png)

**Comment by pavelciapa** [comment]
@mwobensmith what would you suggest about creating new profile? May be to expand existing profile with Saved Logins?

**Comment by tracywalker** [comment]
Matt said it would be best to create a profile for this. He suggests using one of the existing profiles by copying it, then make any additions and rename appropriately for Iris use.

**Comment by pavelciapa** [comment]
Saved logins for test on local assets htm pages, instead of creating a new profile
