### ISSUE TITLE
Latest PR throw the error "The command "pipenv run iris -j -n -d ci_tests" exited with 1."

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#3172]
Latest Pull Requests failed with:

 --->  installing/upgrading Leptonica #####
bootstrap/linux_bootstrap.sh: line 93: tesseract: command not found
\n\033[0;32m  --->  Downloading leptonica-1.76.0.tar.gz \033[0m\n
--2019-05-07 11:23:13--  http://www.leptonica.com/source/leptonica-1.76.0.tar.gz
Resolving www.leptonica.com (www.leptonica.com)... 74.125.70.121, 2607:f8b0:4001:c12::79
Connecting to www.leptonica.com (www.leptonica.com)|74.125.70.121|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://www.leptonica.org [following]
--2019-05-07 11:23:13--  http://www.leptonica.org/
Resolving www.leptonica.org (www.leptonica.org)... 208.67.207.65
Connecting to www.leptonica.org (www.leptonica.org)|208.67.207.65|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7145 (7.0K) [text/html]
Saving to: ‘leptonica-1.76.0.tar.gz’
leptonica-1.76.0.ta 100%[===================>]   6.98K  --.-KB/s    in 0.04s   
2019-05-07 11:23:13 (159 KB/s) - ‘leptonica-1.76.0.tar.gz’ saved [7145/7145]
**gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
\n\033[0;31m  --->  leptonica-1.76.0 directory not found! Maybe the extraction failed. \033[0m\n
install.2**
1.60s$ pip install pip==9.0.3
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Collecting pip==9.0.3
  Downloading https://files.pythonhosted.org/packages/ac/95/a05b56bb975efa78d3557efa36acaf9cf5d2fd0ee0062060493687432e03/pip-9.0.3-py2.py3-none-any.whl (1.4MB)
Installing collected packages: pip
  Found existing installation: pip 19.0.3
    Uninstalling pip-19.0.3:
      Successfully uninstalled pip-19.0.3
Successfully installed pip-18.1
install.3
0.42s$ pip install pipenv
Requirement already satisfied: pipenv in /home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages
Requirement already satisfied: enum34; python_version < "3" in /home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages (from pipenv)
Requirement already satisfied: virtualenv in /home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages (from pipenv)
Requirement already satisfied: certifi in /home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages (from pipenv)
Requirement already satisfied: pip>=9.0.1 in /home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages (from pipenv)
Requirement already satisfied: virtualenv-clone>=0.2.5 in /home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages (from pipenv)
Requirement already satisfied: typing; python_version < "3.5" in /home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages (from pipenv)
Requirement already satisfied: setuptools>=36.2.1 in /home/travis/virtualenv/python2.7.15/lib/python2.7/site-packages (from pipenv)
install.4
88.53s$ pipenv install
Pipfile.lock not found, creating...
Locking [dev-packages] dependencies...
Locking [packages] dependencies...
Updated Pipfile.lock (5b37d7)!
Installing dependencies from Pipfile.lock (5b37d7)...
     ================================ 53/53 — 00:00:34
before_script.1
0.00s$ export DISPLAY=:99.0
before_script.2
0.00s$ Xvfb :99 -screen 0 1920x1080x24+32 +extension GLX +extension RANDR > /dev/null 2>&1 &
before_script.3
3.00s$ sleep 3
2.75s$ pipenv run iris -j -n -d ci_tests
Courtesy Notice: Pipenv found itself running within a virtual environment, so it will automatically use that environment, instead of creating its own for any project. You can set PIPENV_IGNORE_VIRTUALENVS=1 to force pipenv to ignore that environment and create its own instead. You can set PIPENV_VERBOSITY=-1 to suppress this warning.
libpng warning: sBIT: invalid
**2019-05-07 11:24:50 [CRITICAL] [iris.api.core.util.core_helper] Unable to find Tesseract.**
2019-05-07 11:24:50 [CRITICAL] [iris.api.core.util.core_helper] Please consult wiki for complete setup instructions.
**The command "pipenv run iris -j -n -d ci_tests" exited with 1.**

**Comment by rrobotin** [comment]
Issues fix with commit id [1c559c1b7f5cde2f490d594a7fffe23f3ea483de](https://github.com/mozilla/iris/commit/1c559c1b7f5cde2f490d594a7fffe23f3ea483de)
