### ISSUE TITLE
Both background and manual update fail for 'tr' build (Ubuntu 18.04)

### ISSUE THREAD

**Issue by MarisBogdan** [mozilla/iris#3192]
Running update test for 67.0b19 from 63.0b8 will fail for both manual and background. You can find the logs and screenshots here: https://drive.google.com/drive/u/1/folders/1GKsjMokqI6IYgs8JZ_gApkV7rprgkvEQ

**Comment by tracywalker** [comment]
Ioana,  please take a look at this.

The pattern to match is obviously there.  This is an issue with pattern similarity.   I think reduce the pattern similarity and change the captured pattern to be a bit smaller.  It isn't necessary to pick up the entire menu button.
