### ISSUE TITLE
Both background and manual update fail for 'es-ES' build (Ubuntu 18.04)

### ISSUE THREAD

**Issue by MarisBogdan** [mozilla/iris#3193]
Running update test for 67.0b19 from 54.0b3 will fail for both manual and background. You can find the logs and screenshots here: https://drive.google.com/drive/u/1/folders/1BVXoyncyrmv6yAMJdVgUBOzLtCSfTupv

**Comment by tracywalker** [comment]
Ioana,  please take a look at this.

The pattern to match is obviously there.  This is an issue with pattern similarity.   I think reduce the pattern similarity and change the captured pattern to be a bit smaller.  It isn't necessary to pick up the entire menu button.

**Comment by tracywalker** [comment]
I'll take a look at this.

The pattern to match is obviously there.  This is an issue with pattern similarity.   I think reduce the pattern similarity and change the captured pattern to be a bit smaller.  It isn't necessary to pick up the entire menu button.
