### ISSUE TITLE
Deal with the crash reporter dialog, if it appears

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#34]
Firefox can crash during an Iris test. I have seen this already.  It didn't interfere with the remainder of the test run. But we should implement a helper that deals with the crash reporter dialog. Either dismissing it or send the report with a message that the crash occurred during an Iris test run.

We could run this check after each test case or only after an entire test run, as part of cleanup.

**Comment by mwobensmith** [comment]
Maybe we do a check that gets fired once per test case to see if the dialog is present, and deal with it then.

**Comment by tracywalker** [comment]
For now, we'll do a simple brief check to detect the crash dialog.  tarcked in issue #579.  This issue will track issuing a more elegant solution involving waitAppears()  (or whatever it is called when such a feature is implemented in Iris)

**Comment by mwobensmith** [comment]
The work here could be to report to the log when the crash reporter has appeared, so that we have an idea of what test might have triggered it. We should also consider failing the previous test if we can determine that it caused the crash.

**Comment by mwobensmith** [comment]
The code that deals with the crash reporter should also call `get_current_module` from `core_helper`, and print that to the log. We should also create a list in Iris to store this data, which would then be written to the run log JSON file.

**Comment by tracywalker** [comment]
We still need Linux crash dialog image and enable this on Linux.    I recently learned about:crashparent will force Fx crash.

**Comment by tracywalker** [comment]
If I am reading the DEBUG output correctly, it doesn't look like this code is being called anymore.  As such, a crash dialog that is present isn't being addressed.  The confirm_firefox_quit should be called from test_runner via close_firefox(), in general.py, after each test case. At some point this was removed. mozrunner is not dealing with the crash dialog.  Our confirm_firefox_quit code should be used.

(by the way, someone already put the Linux crash_sorry.png in place)

**Comment by mwobensmith** [comment]
Obsolete due to mozrunner usage.
