### ISSUE TITLE
preferences={} in @pytest.mark.details() doesn't work

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#357]
```
    @pytest.mark.details(
         ...
        preferences={'extensions.formautofill.available': 'on',
                     'extensions.formautofill.creditCards.available': True}
    )
```

**preferences={}** doesn't change `about:config` preference.
Noticed today, worked well yesterday. Perhaps the reason is todays Firefox beta. 

`change_preference() `works as before.

**Comment by mariusandreifilip** [comment]
fixed in branch issue_ 357 and merged to dev

**Comment by pavelciapa** [comment]
didn't work for me in  _test_case_id='101676',_ 
`        preferences={'privacy.resistFingerprinting': 'true'}`

Used ` change_preference('privacy.resistFingerprinting', 'true') ` instead

**Comment by tracywalker** [comment]
https://github.com/mozilla/iris_firefox/issues/3318
