### ISSUE TITLE
PEP-8 compliance

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#36]
We haven't been strict about this yet, but at some point, we need to run a PEP-8 check on every file and correct all infractions.

**Comment by palash25** [comment]
I would like to give this a try. Can I be assigned to it?

**Comment by mwobensmith** [comment]
Hi @palash25 , we have already completed this task in a branch that will be checked in soon. Thank you for your offer, and perhaps we will have something for you to do in the near future.
