### ISSUE TITLE
Log errors when unsupported Settings methods are called

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#363]
While we will be creating a Settings class and some methods, we will not support the items below. Log an error and raise an exception when they are used.

```
ActionLogs
DebugLogs
InfoLogs
getSikuliVersion()
```

**Comment by silviuFlorin** [comment]
Implemented this in branch [issue_363_380]. Logging an error in each method/attribute is unnecessary as it is caught in test_runner and logged automatically

**Comment by mwobensmith** [comment]
We want to raise a special error message when we see use of an unsupported API. Therefore, it is not enough to catch this error in the `test_runner`. We need to list each API by name and log the message there.

**Comment by mwobensmith** [comment]
Wait a second.. I just looked at your code and you did indeed call out each API and raised the new exception. That's perfect. 👍

**Comment by silviuFlorin** [comment]
Code merged. Closing issue
