### ISSUE TITLE
Refactor the minimize_window() function from keyboard_shortcuts.py for OSX

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#372]
Current implementation:
def minimize_window():
    """Minimize the browser window to the application launch bar"""
    if get_os() == Platform.MAC:
        type(text='m', modifier=Key.CMD)
    else:
        type(text=Key.DOWN, modifier=KeyModifier.WIN)

Function has to be updated for OSX. 
Key.CMD has to be changed with KeyModifier.CMD

**Comment by mwobensmith** [comment]
Ioana, just curious, but does the above work? I would imagine that `Key.CMD` is equal to `KeyModifier.CMD` for this purpose, and that it should be OK. 

Or is it something you think should be changed so that it looks more consistent?

**Comment by icrisan** [comment]
Function does not work with key.CMD so I had to change it to KeyModifier.CMD.

**Comment by icrisan** [comment]
issue merged with branch "issue_401_402".
