### ISSUE TITLE
Better log report

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#40]
Ideally, our log should contain more than just messages from the logger. It should also contain detailed, helpful information about the run itself.

* Specific Firefox build details
* Platform details
* Total run time
* Number of tests passed, failed, skipped, total
* Details about failed tests

Other data TBD.

**Comment by mwobensmith** [comment]
We have better logging now but we could still add meta data w/r/t Fx build and platform into the final report.

**Comment by mwobensmith** [comment]
As per our discussion, we want a few basic details to put in the log file about the Firefox build we used. Right now, this is easy when the tester downloads the build of Firefox, because we can parse a directory using the `FirefoxApp` class. See line 68 in `__main__.py`.

However, if we use a local build of Firefox, we currently don't get a `FirefoxApp` object. One way we might do this is pass each path to an instance of `FirefoxApp`, which parses a directory and its package files to get us this information. 

Above line 67, add something like this:
```
fx_app = None
```
On line 68, change the current code to this:
```
fx_app = self.get_test_candidate(self.args.firefox)
```

Then, on lines 73, 76, and 78, replace all assignments of `self.fx_path` to `FirefoxApp` objects, e.g.:
```
fx_app = FirefoxApp('/Applications/Firefox.app/Contents/MacOS/firefox')
```
Keep in mind that **I haven't tested this**. It's possible that this path above (on Mac, for example) needs to be `'/Applications/Firefox.app/'` and not the full path. Please try both to see if the `FirefoxApp` class can extract the package file from this.

Once you have all of that done, on line 81, add the lines of code below. Make sure they are indented to match line 67, so that they get assigned no matter what platform we are on.

```
self.fx_path = fx_app.exe
self.fx_version = fx_app.version
self.fx_release = fx_app.release
```
Try this and see if it works. If not, plan B. 😁

**Comment by silviuFlorin** [comment]
Finished working on this issue. Please review branch issue_40.

**Comment by mwobensmith** [comment]
Looks good, but breaks when we download a build of Firefox.

`iris -t tabs -f nightly`

Error:
```
Traceback (most recent call last):
  File "/Users/mwobensmith/PycharmProjects/iris/bin/iris", line 11, in <module>
    load_entry_point('iris', 'console_scripts', 'iris')()
  File "/Users/mwobensmith/PycharmProjects/iris/iris/__main__.py", line 37, in main
    Iris()
  File "/Users/mwobensmith/PycharmProjects/iris/iris/__main__.py", line 49, in __init__
    self.main()
  File "/Users/mwobensmith/PycharmProjects/iris/iris/__main__.py", line 68, in main
    self.fx_app = self.get_test_candidate(self.args.firefox)
  File "/Users/mwobensmith/PycharmProjects/iris/iris/__main__.py", line 172, in get_test_candidate
    candidate_app = fe.extract(build_archive_file, get_os(), self.args.workdir, cache_timeout=1 * 60 * 60)
  File "/Users/mwobensmith/PycharmProjects/iris/iris/firefox/extractor.py", line 67, in extract
    app = FirefoxApp(cache_dir, platform, True)
  File "/Users/mwobensmith/PycharmProjects/iris/iris/firefox/app.py", line 62, in __init__
    raise Exception('Unsupported application package format (missing files)')
Exception: Unsupported application package format (missing files)
```

We should be able to run Firefox in four ways:
* Default local installation
* Local directory with valid Firefox app
* Local archive file
* Downloaded from the web

I have not inspected your code thoroughly, but I think the third case is the problem here. Try again and we'll test against the above scenarios to make sure we get it right.

**Comment by silviuFlorin** [comment]
Fixed the issue.

**Comment by silviuFlorin** [comment]
Code merged. Closing issue
