### ISSUE TITLE
refactor the toolbars_window_controls/confirm_close_multiple_tabs_controls.py test

### ISSUE THREAD

**Issue by psilaghi** [mozilla/iris#402]

**Comment by mwobensmith** [comment]
Although I merged this into "prototype" already, this seems to be failing for me on Linux. The maximized dialog is shown, and it fails on line 49:

`assert_true(self, expected_4, 'Close multiple tabs warning was maximized successfully')`

Can you take a look?

**Comment by psilaghi** [comment]
This fails because the dialog controls are no longer visible on maximize due to the auto-hide menu feature on Linux. The feature was disabled on my machine by the time I tested.
Anyway, I added an extra "hover" in the top browser area that makes the controls visible again.
[issue_401_402] branch updated and sent again.
Thanks Matt.

**Comment by tracywalker** [comment]
Paul please submit a Pull Request. Thank you.

**Comment by psilaghi** [comment]
done

**Comment by psilaghi** [comment]
Code merged. Closing
