### ISSUE TITLE
refactor the toolbars_window_controls/library_controls.py test

### ISSUE THREAD

**Issue by psilaghi** [mozilla/iris#404]

**Comment by mwobensmith** [comment]
This fails on Mac with this line:

`assert_true(self, expected_5, 'The library was restored successfully')  `

**Comment by psilaghi** [comment]
Works fine for me - probably a Retina issue? Will test again on a non-retina Mac and get back with the results.

**Comment by psilaghi** [comment]
Works fine on the non-retina macbook too.
Can you try again?

**Comment by psilaghi** [comment]
Merged, closing.
