### ISSUE TITLE
update the toolbars_window_controls/"browser_controls_upper_corner.py" test case 

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#405]

**Comment by mwobensmith** [comment]
This looks great. I made a few small changes.

* I updated calls to `getOS()` with `Platform.getOS()` and also, `Platform.LINUX` etc.

* I changed two places where you would raise an exception if something wasn't found. In general, it is better to handle this failure with an assert. At the very least, one assert can handle both the positive and negative outcome of a test. 

If you raise exceptions, the test harness will still catch them, but the asserts were designed for this purpose.

Please run this and tell me if it works correctly. I already merged @echim's work, so yours should be ready to land.

**Comment by mwobensmith** [comment]
Merged in #436
