### ISSUE TITLE
Disable web compat tests that require login

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#410]
This means Gmail and Yahoo Messenger. 

Since we can't reliably do authenticated testing of live sites across locales, we will turn these off by default via `self.exclude = Platform.ALL` .

**Comment by palash25** [comment]
So this issue is about adding `self.exclude = Platform.ALL` to the `__init__` methods of the aforementioned tests?
If yes then I would like to be assigned to this.

**Comment by mwobensmith** [comment]
Hi @palash25, thank you for your interest. This issue already has a fix waiting to be merged. Would you like to do something a bit more technical? We have other issues that could use some work, or could give you a test case to write, as a way to get introduced to Iris.

**Comment by palash25** [comment]
Just a little suggestion can you please add a label like `has-PR` to the issues that are about to get merged.

That would make it easier for future contributors to filter out issues to work on.

**Comment by tracywalker** [comment]
Hi Palash,

We think the easiest way to get involved is to try writing a test case. 
If that sounds like something you would be interested in. Let me know 
and I'll pick out a test case for you.

Thanks

Tracy Walker

**Comment by palash25** [comment]
Yep, @tracywalker I would like to get involved.

I have always wanted to contribute to Mozilla so I would really like an issue to solve.

**Comment by mwobensmith** [comment]
@palash25, Tracy will work with you to get you a good test case to work on.

> Just a little suggestion can you please add a label like has-PR to the issues that have already been solved and are about to get merged.

This project is still pre-1.0 so we don't have a process for dealing with contributors and open issues just yet. Have patience and with time, we'll make it easier. Thanks.
