### ISSUE TITLE
Refactor web_developer_menu.py test to use asserts

### ISSUE THREAD

**Issue by mariusandreifilip** [mozilla/iris#419]

**Comment by tracywalker** [comment]
This test case doesn't work for me on Mac unless I remove line #27:
 left_corner_screen_region = Region(screen.getX(), screen.getH() / 2, screen.getW() / 2, screen.getH() / 3)

please check if that is the case for you. thank you.

**Comment by mariusandreifilip** [comment]
The problem here is that I run the tests on a 13'' Mac Pro and the browser by default is full screen.Iris is minimizing the browser and the region is modified.I Updated the branch to work for full screen for both web_developer_menu and browser_control_console.I also tested the fix on a 15'' Mac and it runs

**Comment by tracywalker** [comment]
fixed by issue #460
