### ISSUE TITLE
Clean up ocr.py test case

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#426]
* Line 14 - either remove commented line or exclude platforms that do not work right now.
* LIne 17 - use `get_asset_path` method, as specified in #101.

**Comment by mwobensmith** [comment]
Test has been turned off, can be cleaned up at a later date.

**Comment by echim** [comment]
Hi @silviuFlorin , please review the changes here: https://github.com/mozilla/iris/tree/issue_426

**Comment by silviuFlorin** [comment]
Code approved
