### ISSUE TITLE
Various Linux issues

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#43]
These issues can be intermittent, and/or present on Linux hardware only (vs VM). 

* Test cases do not maximize browser window. I found the correct keyboard shortcut, and while it works if you do it manually, it fails programmatically on Linux hardware. It succeeds on Linux VM. I'm stuck here until someone else gets a Linux box to confirm.

* Test cases sometimes start and never navigate. I thought this might be an issue with keyboard shortcuts not being recognized too soon after Fx launch, but adding wait time did not help. This is an intermittent problem but very annoying. I can repro on both Linux hardware and VM, but not other platforms.

* Text recognition doesn't always work well. It causes intermittent errors in deactivate_activity_stream because "TOP SITES" is sometimes read as "TOP srres". Either we allow that alternate text string or find another way to automate. I used text recognition here because the pattern for the "TOP SITES" image seemed to differ even among machines of the same OS. We'll continue to see this in the future, I believe.

**Comment by tracywalker** [comment]
about bullet 1)  I have always had issues in regular use of VM with regards to keyboard shortcuts.  I think this maybe be an issue with VMware and how integrates with the os.  Will be certain when we can check on hardware.

about bullet 2)  I wonder if this has something to do with moving the mouse to (0, 0)  maybe the mouse puts focus somewhere else if it is moved off screen like that.  maybe override that in a test case and instead mouseMove(5, 5)?

**Comment by mwobensmith** [comment]
RE: item 1. The VM actually works correctly. It's my hardware that fails, and I don't know why.

RE: item 2. Good idea. We should try this. It would sure be nice to be able to get it to happen more frequently. Right now it's about 30% of the time when running a test case via -t, and about 5% of the time when running the whole suite.

**Comment by mwobensmith** [comment]
Should be fixed since migration to pyautogui, etc. The issue with better OCR is being dealt with separately.
