### ISSUE TITLE
Test runs log is not informative

### ISSUE THREAD

**Issue by spronoza** [mozilla/iris#438]
There is not possible to analyze the reason of the test failures because of not informative log.
Logging need to be improved at least like in the Iris 1.0

**Comment by mwobensmith** [comment]
Even with `-i DEBUG` turned on?

**Comment by spronoza** [comment]
We want to see all that was in Iris 1.0

**Comment by mwobensmith** [comment]
@spronoza List the things you want, in order of importance, and I will see what I can do for you.

**Comment by mwobensmith** [comment]
We have moved away from the log file and now support the `run.json` file as the best way to get data from an Iris run. Closing issue.
