### ISSUE TITLE
Iris operates with patterns **faster** than pattern is created.

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#448]
Iris operates with patterns **faster** than pattern appear.

_example case:_
We uncheck checkbox, and expect NO MATTER unchecked or checked pattern - **assert True**

```
        click(checkbox_checked_pattern, 1)

        checkbox_is_unchecked = exists(CHECKED_BOX, 10, checkbox_region)
```

If uncheck checkbox, and we expect **checked pattern**, we also have **assert True**, unless we use timeout. 

```
        click(checkbox_checked_pattern, 1)

        time.sleep(FirefoxSettings.TINY_FIREFOX_TIMEOUT)
        checkbox_is_unchecked = exists(AboutPreferences.UNCHECKED_BOX, 10, checkbox_region)
```

timeout before exist makes Iris to catch pattern that appears after click on checkbox, not before, as without timeout. 

We need to add timeout to exists() or in some other way to make ourselves sure that action go a little after pattern creation

**Comment by tracywalker** [comment]
Don't mess around with exists by adding a timeout.  The type of situation you mentioned should be addressed directly in tests that are affected by it. You can use a timeout or wait_vanish()
