### ISSUE TITLE
Create command line parameter to force disabled tests to run

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#449]
Right now, if a test case is marked as disabled via `self.exclude`, it will be skipped. There should be an optional flag that can be used to force these tests to run, if desired. 

Flag name and value TBD.

**Comment by mwobensmith** [comment]
One way we could do this is to add a flag that we'll call `override`, to override a test case's logic to be disabled.

```
    parser.add_argument("-o", "--override",
                        help="Override disabled tests",
                        action="store_true")
```

Then, in `test_runner.py`, change the logic that decides if it wants to run the test case or not in line 36:

```
    if Settings.getOS() not in current.exclude or app.override:
```

**Comment by silviuFlorin** [comment]
Created branch issue_449_450
