### ISSUE TITLE
Create command line parameter to control mouse animation

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#450]
There is a default mouse move speed in Iris. It would be nice to be able to start Iris, and either a) change the numeric value of that speed, or b) enable/disable mouse movement completely. 

Flag name and value TBD.

**Comment by mwobensmith** [comment]
`Settings.MoveMouseDelay`

> Control the time taken for mouse movement to a target location by setting this value to a decimal value (default 0.5). The unit is seconds. Setting it to 0 will switch off any animation (the mouse will “jump” to the target location).

So, perhaps something like:

`iris -m 0` # turns off animation
`iris -m 0.5` # equivalent to what we have now
`iris -m 1` # slower mouse movement

**Comment by mwobensmith** [comment]
Tests can change this property at will, so we will likely want to set `Settings.MouseMoveDelay` at various times:
* When app is initialized
* Before each test is run (similar to how we reset mouse in line 41 of `test_runner.py`)

It is possible that there are times where the value could be changed, or is not what we expect. I think it's OK as long as we control the speed most of the time, and especially the times where it is most noticeable, such as starting up a test. Turning this off will make Iris faster. Increasing the value will make it slower but easier to demo and/or debug.

**Comment by silviuFlorin** [comment]
Created branch issue_449_450
