### ISSUE TITLE
Enhance debug image to add more data, usability

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#451]
TBD with mockup, but general idea:

* Add footer with icon indicating found/not found.
* Footer contains:
  * Name of pattern
  * Pattern dimensions
  * Similarity used for match
  * Pattern file name
  * Some type of progress/duration based on pattern timestamp
  * Region dimensions

**Comment by tracywalker** [comment]
Let's add moving the pattern out of the screen/region so no information is obscured by the pattern and its info.

**Comment by tracywalker** [comment]
- Data about the system under test.  
- Build id of Firefox

**Comment by mwobensmith** [comment]
Now that Iris is being run in Mozilla's taskcluster/treeherder, it is likely that debug images will be used to file bugs. In that case, the images should contain even more contextual information that will help developers fix the bug, without knowing anything about Iris.
