### ISSUE TITLE
Create mechanism to run test on select versions of Firefox

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#451]
Right now, we can access the Firefox build and version information in a test case via its `Iris` app object.  So, a test case can check that to decide if it wants to run logic based on Fx version. It may do so to work around a bug, or to run only when the feature hits a certain release.

It would be nice to build something permanent into the base test class so that tests don't have to do this.

For example, one simple idea would be to allow tests to specify `self.fx_version = 62` in their `__init__` method, and have the test runner only run it for Firefox 62 and above. However, we probably want a mechanism that is a little more robust and can turn things on or off if less than, equal to, or greater than a release number, or even a numeric range.

**Comment by mwobensmith** [comment]
The logic to decide if a test case can run, in `test_runner.py`, line 36, will need to be updated to take this into account. Also, the `-o` flag (`override`) can force this test to run.

**Comment by silviuFlorin** [comment]
Created branch issue_451_462

Besides the syntax you suggested I also added:
`self.fx_version = '!=60'`

**Comment by SEVNOHHH5** [comment]
I have no issue responding in person the source. its most likely tomorrow I
will no longer need any electronic devices anyways

**Comment by SEVNOHHH5** [comment]
hello.
