### ISSUE TITLE
Image handling for normal and high-definition screens

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#454]
We currently have a few issues around screens and images.

* No way to know by inspecting an image if it was captured on a normal or high-definition screen.
* No rules around which configuration - normal or hi-def - the image should be captured on.

We can detect playback on either type of screen, and we can resize images to match. However, we have not settled on what we handle automatically in Iris, and what we require test case authors to do. 

One proposal is to add "2x" to an image name when it is a hi-definition image. Then, Iris can handle the downsizing automatically. Conversely, if Iris loads an image without "2x" in its name, it can assume that it does not require downsizing and use as-is. If we go with this solution, test case authors are only required to capture images on one screen for this config, as long as it's named correctly.

**Comment by mwobensmith** [comment]
Note: Using Mac OS native image capture (CMD-SHIFT-4) will yield an image equal to the resolution of the screen it's on (normal or hi-def), whereas using Sikuli will always produce the normal, lower-resolution image, no matter what config.

**Comment by echim** [comment]
Hi @mwobensmith ,
Can you please review this branch: https://github.com/mozilla/iris/tree/issue_454
I have also removed some of the duplicated patterns.

Have a nice weekend !

**Comment by silviuFlorin** [comment]
Reviewed the code. I suggested some small changes that were addressed in the last 3 commits of this branch. Code approved.
