### ISSUE TITLE
Allow test cases to pre-modify pref(s) before launching the browser

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#46]
Test cases will need to modify about:config. It would be great to be able to do so before launching the browser, thus avoiding the need to restart in order to enable the pref.  This will be very helpful to test pref'd off features, like stylo and just any test the requires a pref to be altered.

**Comment by mwobensmith** [comment]
Great idea. So do you think must be something that we do before the browser launches? 

I ask because it would be pretty easy, with code we have today, to launch browser, set pref, and restart before we call run(). 

In either case, certainly possible and desirable.

**Comment by tracywalker** [comment]
Whatever it takes to make the pref change stick.. Some don't need a restart, but many do require browser restart.

**Comment by mwobensmith** [comment]
A test case can do this today if it overrides the `setup` method of the base test case. In this scenario, the test then must call, in its own `setup` method:
```
profile_name = self._create_unique_profile_name()
launch_firefox(path=self.app.fx_path, profile=profile_name, url="about:blank")
confirm_firefox_launch()
change_preference(...)
quit_firefox()
confirm_firefox_quit()
launch_firefox(path=self.app.fx_path, profile=profile_name, url="about:blank")
```

If that is too complex or error prone, we can consider wrapping all of this in one or two helper methods. The tricky part is making sure the test starts with a Fx instance that has the right profile. This might require the test writer to know what they are doing, as above.

**Comment by tracywalker** [comment]
more recent into in issue #559
