### ISSUE TITLE
Expand -t parameter to accept a path to a file containing a custom list of tests

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#462]
Right now, this runs one test:

```
iris -t tabs
iris -t tabs.py
```

What would also be nice is to be able to pass in a path to a file containing a list of tests, and have that custom set be run. It would be ideal to reuse the same code as much as possible. Perhaps we can use `os.path.exists` on the `-t` argument to determine if we need to load and parse the file.

`iris -t /Users/jsmith/Desktop/custom_tests.txt`

The file's format itself could be a simple line-delimited list. Later on we could get fancy, but it can always be improved.

**Comment by silviuFlorin** [comment]
Created branch issue_462
