### ISSUE TITLE
Use hh:mm:ss.ms format for testrun duration in command line report

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#465]
Currently when running a testrun for Iris the total duration is reported in seconds. For testruns lasting multiple minutes or even hours this presents a usability issue. I have a patch upcoming that converts the total seconds to hours:minutes:seconds.milliseconds format as follows.

Instead of
```
----------------------------------
     Total Duration: 23768.945678s
```
We will display
```
----------------------------------
      Total Duration: 06:36:08.946
```

**Comment by mwobensmith** [comment]
Fixed
