### ISSUE TITLE
Fix test run report sending to email

### ISSUE THREAD

**Issue by paulprokhorovmoz** [mozilla/iris#477]
Email report couldn't be sent because the PathManager.get_git_details() function call throws an exception, because our working dir at the moment of execution doesn't contain any git repo. As a quick'n'dirty solution we could just change working dir to the repo root using os.chdir().

**Comment by mwobensmith** [comment]
Hi @paulprokhorovmoz , I have another idea. You can test it on your local repo to see if it solves the problem.

In `path_manager.py`, line 266, replace the line with this:
```
        repo = git.Repo(PathManager.get_module_dir())
```

Then try the email report to see if it works. If it looks good, let me know and I'll check in a change. Thank you.

**Comment by paulprokhorovmoz** [comment]
Your solution works well, please add it the iris_firefox.
