### ISSUE TITLE
Expose more OS info to Iris

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#478]
More than just platform name, it would be nice to have OS version available in Iris.

Mac: OS 10.x.x
Windows: Win 7 vs 10 
Ubuntu Linux: 14.x.x vs 16.x.x

Additionally, if there is a build number or date associated with the last OS update, we'd like that also.

**Comment by mwobensmith** [comment]
This should be added to the `Platform` class as a static constant named `VERSION`.

**Comment by tracywalker** [comment]
code approved.
