### ISSUE TITLE
Runs with -d run entire test suite

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#483]
I tried 
`iris firefox -n -d awesomebar`
instead of running just the tests in the awesomebar group,  Iris queued up all 536 tests from the Firefox target.

**Comment by mwobensmith** [comment]
Looks like we did not port the `-d` flag. 

However, a workaround would be this:
`iris firefox -t /awesomebar/`

Or:
`iris firefox -t '/awesomebar/'`

That should work on Mac/Linux. On Win, you might need to use double backslash instead of single forward slash.

Give it a try.

**Comment by mwobensmith** [comment]
Fixed.

If `-d` is used, then `-t` will further filter tests from that directory.
