### ISSUE TITLE
Failing runs fail to complete when git repo is on a detached HEAD

### ISSUE THREAD

**Issue by KWierso** [mozilla/iris#485]
When a run is nearly completed, create_run_log() attempts to gather as much metadata about the run as it can. Part of that metadata is the branch name of the git repo, `repo.active_branch.name`.

Normally that works, but if you're on a detached HEAD (if you `git checkout origin/dev` instead of `git checkout dev`, you'll wind up on a detached HEAD), `repo.active_branch` is undefined, and that throws an exception that crashes the run. 

The obvious answer is "don't run on a detached HEAD", but we can paper over the issue by catching the exception and just calling the branch name "detached" or something.

**Comment by m8ttyB** [comment]
In my defense, running against a detached HEAD is a pattern that I and many other engineering I've worked with use when reviewing and running other peoples code. I appreciate the fix \o/
