### ISSUE TITLE
Possibility to run a test list from txt file

### ISSUE THREAD

**Issue by pavelciapa** [mozilla/iris#488]
Add a possibility to run a test list from a txt file, when there is a big quantity of failed tests, for example >10 failed tests.

Use case: create txt file, paste ~100 failed test, run command (example):
iris firefox -tests /Users/tests.txt

**Comment by mwobensmith** [comment]
Added this to the code. 

1. The path to the text file must be the full path. It can, however,  contain the shortcut for the home directory, i.e.:

`iris firefox -t ~/Desktop/tests.txt`

2. The text file itself must contain the full paths of tests. Each file path must have a line break. Pretty simple.

This is in the `dev` branch, which will go to `master` tomorrow. Then it will be merged into `iris_firefox` `dev` and `master` repo afterwards. If you want to see how it works now, you can try it here. Or you can wait until next week in the `iris_firefox` repo post-merge.

**Comment by mwobensmith** [comment]
Another thing... after every run, we automatically create a list of failed tests. If you want to re-run only the failed tests from the last run, all you have to do is this:

`iris firefox -a`

**Comment by mwobensmith** [comment]
Merged to master.
