### ISSUE TITLE
Uncaught exception flagged as failure and not error

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#501]
If a test runs without encountering any false asserts, it is considered "PASS."

If a test has a failed assert, we will consider the test "FAILED." 

If the test causes an uncaught exception via an API, we consider it "ERROR."

However, if a test directly causes an uncaught exception, we currently consider it "FAILED." 

I think the last case should be handled as "ERROR."

@tracywalker Do you agree?

**Comment by tracywalker** [comment]
Yes, I agree.
