### ISSUE TITLE
Remove iris_firefox-specific files from repo

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#506]
* Remove `/tools/run_update_suite.sh`

* Remove last line of `.gitignore` that mentions the Download tests for Firefox.

**Comment by Patil2099** [comment]
Can I work on this ? @mwobensmith

**Comment by pavelciapa** [comment]
> 
> 
> Can I work on this ? @mwobensmith

Cover this issue in correspondent branch, then create pull request and put Matt as reviewer
