### ISSUE TITLE
Better Fx profile handling

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#507]
Right now, we start each test case with `Profile.DEFAULT`, which currently provides a brand-new, uninitialized profile. This is fine, but can present problems.

If a test case calls `restart_firefox`, on relaunch Firefox may display a modal dialog asking the user to make a choice of default browser. This will kill the test and Iris. A test case could be written to expect this, but this behavior seems to change with Firefox version. 

In addition, when using a new profile, there are often first-run tours and other things that cause unintended tooltips and other UI that might interfere with Iris' pattern matching.

We may want to standardize on a set of `Profile` constants that guarantee certain behaviors.

`Profile.BRAND_NEW `- generates a completely new profile from scratch.
`Profile.LIKE_NEW` - use a profile that has had minimal configuration, but would be set up to avoid things like the default browser dialog (`browser.shell.checkDefaultBrowser;false`) and possibly first-run tour items.
`Profile.TEN_BOOKMARKS` - already present, is identical to `LIKE_NEW` but has had the activity of bookmarking ten sites.

We can keep the `BaseTest` class the same, which uses `Profile.DEFAULT`. The question that this poses - what should `Profile.DEFAULT` be equal to, from the above list?

**Comment by tracywalker** [comment]
I believe we should default to Profile.LIKE_NEW.  Most test cases will want to use a profile that won't encounter those first time user experiences.  I believe, most custom profiles, like TEN_BOOKMARKS, should be based on LIKE_NEW to avoid any new user experiences. The amount of test cases that would need BRAND_NEW is relatively small. As such, BRAND_NEW would be a special profile that is sparingly used.

**Comment by SEVNOHHH5** [comment]
there is no more handling the705 profiles you fucking hackyards. I plan on
a more personal approach with the knowledge gained from your lack of
respect for others personal boundaries and information. thank you for
simply reaffirmiming what I already knew.

**Comment by mwobensmith** [comment]
We now default to Profile.LIKE_NEW.
