### ISSUE TITLE
Submit run.log report to Iris Hub after tests execution

### ISSUE THREAD

**Issue by dbakaev** [mozilla/iris#508]
The process of reports delivery to Iris Hub should be automated. Method pytest_sessionfinish of target.py has to be extended by adding HTTP post request to Iris Hub server with the report.

**Comment by mwobensmith** [comment]
@dbakaev I imagine that the URL for the HTTP post should go in the `config.ini` file. Do you have some sample code that would make this work for you? 

Also I'm assuming that we don't need authentication for this URL. How else should this feature work? Does it need to be turned on with a flag? Or should the presence of the URL in the `config.ini` file automatically make it work?

**Comment by dbakaev** [comment]
Yes, basically, we need to send a simple HTTP POST request with run.json file to http://irishub.info. I'll ask @PaulProkhorov to create a PR with a code

**Comment by paulprokhorovmoz** [comment]
@mwobensmith May I use the requests library to implement this?

**Comment by mwobensmith** [comment]
@PaulProkhorov Let's discuss in our next meeting.

**Comment by mwobensmith** [comment]
I have added this to `iris_firefox` instead, so I'm going to close it here.

Follow the [thread](https://github.com/mozilla/iris_firefox/issues/3647) over there.
