### ISSUE TITLE
Test count on Iris page doesn't account for skipped tests

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#509]
I noticed this running the bookmarks test group in iris_firefox on OSX.  There are quite a few tests on OSX in this test group that are blocked_by or excluded from being run. During the test run, the total test count reflects all of the tests in the bookmarks directory.  However, as the tests run, the count for the number of tests done is not incremented when a test is skipped. As such by the end of the test run,  the count hasn't come close to the total on display.

Either the count should increment when a test is skipped or the total should represent only the number of tests that will be executed.

Is a low priority, polish issue.

**Comment by mwobensmith** [comment]
This is a bug in the Firefox target, easy fix, will do it there.
