### ISSUE TITLE
Use shutil.get_terminal_size() instead of os.get_terminal_size() to avoid an OSError when running on taskcluster

### ISSUE THREAD

**Issue by KWierso** [mozilla/iris#515]
When running via taskcluster (on Windows, at least), os.get_terminal_size() throws `OSError: [WinError 6] The handle is invalid`.

shutil.get_terminal_size() is a higher-level wrapper to it, which falls back to some usually-sane defaults when it fails to find a terminal size, which works around the OSError.

**Comment by mwobensmith** [comment]
Fixed in PR #516
