### ISSUE TITLE
Add a way to print Treeherder-readable error messages

### ISSUE THREAD

**Issue by KWierso** [mozilla/iris#518]
As part of getting Iris running in Taskcluster against CI builds, it would be helpful if Iris could print a list of failing tests in a format that Treeherder knows how to display in its failure summary panel.

Rather than fundamentally reworking Iris's logger to use something like the MozLog python package, we can get something Good Enough™ by just looping through the list of failed tests at the end of the run and printing out each failing test on its own line.

Lines prefixed with `TEST-UNEXPECTED-` will automatically be displayed by Treeherder.

So if we could print a line like `TEST-UNEXPECTED-{result} | {section-name} - [{optional-subsection-name} -] {test-name} | {error-message}` for every failure, that would be enough for our first pass at running Iris in CI.

Matt mentioned we could probably add a runtime flag like -ci to indicate we're running in CI, and only do these treeherder-friendly prints when that flag is passed in. I have no strong opinion on if these Treeherder prints should replace the end of run report that Iris already does, or if they should just be an additional step.

**Comment by KWierso** [comment]
Alternatively, instead of looping through the failed tests at the end of the run, maybe it'd be better to print out the treeherder-friendly failure lines right after each failure occurs?

**Comment by m8ttyB** [comment]
What amount of work would it be to use mozlog? This could offer us some future proofing.

**Comment by kimberlythegeek** [comment]
Will treeherder automatically pick up the results from pytest assertions? I could be mistaken.

To get a working solution in the meantime, I propose an alternative route that does not depend on modifying iris-core. currently I'm thinking about writing a python script that is run after iris in our kind.yml file. this script could fetch the json file, then parse and output in a treeherder friendly format

**Comment by m8ttyB** [comment]
@KWierso is there documentation for Treeherder on the data types (and formats) it accepts?

**Comment by mwobensmith** [comment]
@KWierso I created branch [issue_518](https://github.com/mozilla/iris/tree/issue_518). Give it a try. Make sure to pass in `-ci` on startup.

Also, if you are testing with the default sample test cases, experiment with failures vs errors to make sure the logic works correctly between the two. If no error message is given, we default to printing the bad assert statement itself.

**Comment by KWierso** [comment]
This works great, thanks for that! I'll have use for the `-ci` flag in an issue I'll be filing later today, too.

**Comment by mwobensmith** [comment]
https://github.com/mozilla/iris_firefox/pull/3632
