### ISSUE TITLE
Iris can't set booleans in preferences from

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#524]
I think this has been a long standing issue. The SV team worked around it by just setting needed boolean valued prefs, in the browser, during test run. 

For example, the first pref, a string, correctly gets set. However, the second pref, a boolean, does not get set:

`preferences={'browser.search.region': 'RU', 'browser.search.widget.inNavBar: True}`

The latter pref should enable/show the search field, in the navigation bar, to the right of the url field.

**Comment by mwobensmith** [comment]
Migrating to iris_firefox since it's an issue with that code and not core.
