### ISSUE TITLE
Test 'history_sidebar' is currently failing

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#524]
Mac/Win/Linux

**Comment by psilaghi** [comment]
After the recent changes, Iris seems to no longer run on a new Firefox profile and this breaks my 'History' tests.
Due to this, the 'first run pages' no longer show up and in the History sidebar a new entry is displayed - "last 7 days".
@mwobensmith , what do you think?

**Comment by mwobensmith** [comment]
Add this between `__init__` and `run` in your test case and tell me if it works for you:

```
    def setup(self):
        """ Test case setup
        This overrides the setup method in the BaseTest class,
        so that it can use a profile that already has bookmarks.
        """
        self.profile = Profile.BRAND_NEW
        launch_firefox(path=self.app.fx_path, profile=self.profile, url='about:blank')
        return
```

**Comment by tracywalker** [comment]
looks good on all platforms, let's get it merged.
