### ISSUE TITLE
Test 'bing' is currently failing

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#527]
Linux for sure, with intermittent failures on Mac/Win

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_527.

Thanks

**Comment by tracywalker** [comment]
Ran fine on Mac.
Consistently failed on Linux and Windows

Windows fails in lines
79            expected_4 = exists(search_field, 10)
80            assert_true(self, expected_4, 'Search field exists')

Linux fails in lines 
 93           expected_5 = exists(language, 10)
 94           assert_true(self, expected_5, 'Language can be changed')

**Comment by tracywalker** [comment]
For the windows failure, if I remove the 2 second sleep you added at line 39 and increase the time to look for search_field to 20 that part of the test works. There is no reason to use time.sleep directly prior to a wait() or exists() call.

However, Windows then fails in the same place as Linux. I am fairly certain I know why the language change isn't working here. At this part of the test, you use tabbing through content.  We should not do this, as web sites will serve up different content based on the location they detect. This explains why the test passes for all of you at your location, but fails here. 

Please update the test to use a pattern match and click on it instead.  Do this for all three platforms.  Even though Mac works, now.  it will likely fail at some point in the future, when then page content changes.

**Comment by IonutBudeanu** [comment]
Fixed in branch issue_527 -> https://github.com/mozilla/iris/tree/issue_527

**Comment by silviuFlorin** [comment]
added some minor changes to bing test and handled some intermittent fails due to pop-ups appearing on page

**Comment by silviuFlorin** [comment]
Code approved
