### ISSUE TITLE
`pipenv install` fails to install mozlog

### ISSUE THREAD

**Issue by KWierso** [mozilla/iris#530]
I'm not sure what changed to cause this since it looks like all of the dependencies are pinned to specific versions, but starting today for me (locally on mac, remotely in CI on windows), `pipenv install` has started failing to install the mozlog package because of incompatible version requirements. 

Our Pipfile requires exactly version 4.0, but it looks like some of our other dependencies are requiring exactly version 4.2.0.

As far as I can tell, we don't actually use mozlog anywhere in iris (there's two lines mentioning it that are currently commented out), so we could maybe just drop mozlog from the Pipfile and let things work without it for now.

Or we could bump the version requirement in Pipfile to "==4.2.0", which seems to get rid of the pipenv errors I'm seeing.

**Comment by mwobensmith** [comment]
Fixed in PR #531
