### ISSUE TITLE
Test 'browser_controls_upper_corner' intermittently failing

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#535]
Windows and Linux.

**Comment by tracywalker** [comment]
looks good with multiple runs on all three platforms.  merging to dev now.

**Comment by mariusandreifilip** [comment]
Still reproducing on OSX
[browser_controls_upper_corner.txt](https://github.com/mozilla/iris/files/2101588/browser_controls_upper_corner.txt)

**Comment by icrisan** [comment]
This issue is fixed in #1111. Closing bug.
