### ISSUE TITLE
Test 'custom_profile' intermittently fails

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#536]
@mariusandreifilip I created the test, but you saw an error on Windows. Can you copy/paste the error here? 

If you can't reproduce the error, talk to @icrisan or @silviuFlorin, who also had the same failure.

**Comment by mwobensmith** [comment]
For me, what happens is that the mouse moves towards the library icon and then just stops, for no reason. Then the test dies.

I have a theory that there is a timing issue in Iris, between the time we call `maximize_window` and then `run`. Locally, when I put a one second delay at the end of `maximize_window` it fixes the problem. It could fix other timing issues as well, and as a fix, is pretty harmless.

**Comment by mariusandreifilip** [comment]
On my side the test is failing on the last assert and I noticed the the amazon banner is not well recognized especially on Linux.I also runned the test on Ioana's pc and Paul's and I noticed the same issue with the 2nd pattern.I created a branch named andrei/issue_536 and on this branch I removed the banner from the second pattern and I shrink ed the search region.We runned this test individually and also as a suite and it passed for at least 5 runs but maybe is a coincidence.

**Comment by mwobensmith** [comment]
> the amazon banner is not well recognized

Not sure what you mean. It's either recognized or not. 

> I removed the banner from the second pattern

If the image is completely wrong, then we can replace it, but I don't want to crop the image just to make it pass. Also, I'm not sure what you mean by "banner" - do you mean icon?

I have noticed an intermittent issue where the bookmark is displayed, but the icon has not loaded yet. If this is what you are referring to, then we can look at other ways of ensuring that we give the icon time to load before searching for it.

**Comment by mwobensmith** [comment]
Checked in #553 so we'll see if this has any impact on the failure.

**Comment by tracywalker** [comment]
reopen if we see this in next weeks stability check.
