### ISSUE TITLE
Move image loading for Patterns out of constuctor and into find code

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#541]
When one creates a `Pattern` via its constructor, we immediately look for the image in a number of reserved locations to establish the correct file path. This is good for enforcing error-checking in code, but has the side effect of a large startup time when you have lots of code that creates new `Patterns`, e.g. the Firefox target.

I'd like to explore a different approach where we don't do the image lookup until a `find`-related method has been called. The advantage is that we spread the wait time over the entire run and have an instant startup. One disadvantage might be that any attempts to query a `Pattern`'s properties before this `find` call would result in some type of error. That might not be an issue, but we can find out by trying.

**Comment by mwobensmith** [comment]
See also #174

**Comment by tracywalker** [comment]
Perhaps put into place yet another flag?   A flag that can allow you to turn on/off pattern error finding at startup.

**Comment by mwobensmith** [comment]
@tracywalker That is a consideration. I guess the first thing to do is see if it's even practical. Not sure if it's something localized - and easy to put behind a flag - or something that will require deeper code changes that would result in an all-or-nothing solution.

**Comment by mwobensmith** [comment]
Fixed and merged with package work.
