### ISSUE TITLE
Enhanced test case setup method

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#542]
Right now, a test case can override `BaseTest`'s `setup` method to control what profile is launched in its Firefox instance. Generally, one just copies/pastes the `setup` code into their test case and alters it. This can be improved. 

* Every test needs to launch Firefox, so this doesn't need to be called in a test case. The call to `launch_firefox` could be moved out of the base test case and into the test runner.
* Choosing a profile to work with should be made simple. A default is set in the `BaseTest`, but you should be able to override it here by a simple assignment.
* There are many other things we can expose here as properties, which will have default values in `BaseTest`. This makes customizing a Firefox instance easy and powerful. 

Proposed list of properties to be available in `setup`:
  * `self.profile` (already exists)
  * `self.url` (defaults to 'about:blank')
  * `self.private_browsing` (defaults to `False`)
  * `self.private_window` (defaults to `False`)
  * `self.maximize_window` (defaults to `True`)
  * `self.window_size` (default `None`, but if not `None`, sets `self.maximize_window` to `False`)
  * `self.profile_manager` (defaults to `False`)
  * `self.set_default_browser` (defaults to `False`)
  * `self.import_wizard` (defaults to `False`)
  * `self.search` (defaults to `None`; if not `None`, open search window with argument)
  * `self.preferences` (defaults to `False`)
  * `self.devtools` (defaults to `False`)
  * `self.js_debugger` (defaults to `False`)
  * `self.js_console` (defaults to `False`)
  * `self.safe_mode` (defaults to `False`)

This work would require modification of `test_case.py`, `test_runner.py`, `core.py`, `general.py` as well as any test cases that have previously overridden `setup`. 

Here's what a sample test case might look like if it wanted to exercise a few of the above options.
```

from iris.test_case import *


class Test(BaseTest):

    def __init__(self, app):
        BaseTest.__init__(self, app)
        self.meta = 'This is my new test case.'

    def setup(self):
        BaseTest.setup(self)
        self.profile = Profile.TEN_BOOKMARKS
        self.private_window = True
        self.url = 'https://www.test-me.com'
        self.maximize_window = False
        self.window_size = '800x600'
        self.devtools = True

    def run(self):
        """
        Firefox starts with a pre-populated profile containing ten bookmarks.
        It starts in a private browsing window.
        The window is not maximized and is displayed at 800x600.
        The window is opened to the desired URL.
        The devtools are open.
        """

```

**Comment by mwobensmith** [comment]
@tracywalker @silviuFlorin  I'd like your feedback, thanks.

**Comment by tracywalker** [comment]
I think this is the right way to go.  It is much clearer on how to make adjustments to the setup of the browser for a test this way.

**Comment by silviuFlorin** [comment]
Very useful enhancement. We should definitely implement it
