### ISSUE TITLE
Alphabetize the function defs in api/helper/general.py

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#551]
This file is getting large enough now that alphabetizing the function helpers here would be ideal. PEP8 compliant too.

**Comment by kriskristin** [comment]
I'd like to work on this. I'll send in a PR.

**Comment by tracywalker** [comment]
kriskristin,  thank you for volunteering to address this issue.  I will review your patch later today. However,  regarding the PR, we don't take code directly into mozilla:iris/master.  Instead, all work goes into mozilla:iris/dev first. Then on Friday each week we do a single merge of dev to master.

As such, please close the current PR for this issue. Then create a new pull request from your branch to iris/dev.  Thank you.

**Comment by kriskristin** [comment]
oops! let me change the base branch in the PR.

**Comment by mwobensmith** [comment]
@kriskristin Thanks for the submission! For future reference, here's how we [manage code in Iris](https://github.com/mozilla/iris/wiki/Developer-workflow).

**Comment by kriskristin** [comment]
> As such, please close the current PR for this issue. Then create a new pull request from your branch to iris/dev.

@tracywalker I edited the PR to point to the dev branch instead of master. Should be good to go now.

**Comment by tracywalker** [comment]
Excellent.  Code approved.
