### ISSUE TITLE
Bookmark icon not always loaded when accessed via menu

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#553]
Sometimes when a bookmark is created, and Iris attempts to search for it in a menu, the entry is there but the icon is displayed as a generic placeholder. The site's favicon has not been loaded here yet. This causes some tests to fail.

An easy way to try to solve this is to introduce a short wait right after the bookmark has been created, in `bookmark_page`. Two seconds should be enough, but we can always change this value.

**Comment by tracywalker** [comment]
fied by https://github.com/mozilla/iris/pull/554
