### ISSUE TITLE
Decouple iris core and package into pypi

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/iris#556]
- [ ] Decouple the iris core functionality from its test harness and control center. Should be able to function as completely separate entities. 

- [ ] Create a pip package and upload to pypi
- [ ] Update documentation to reflect these changes

**Comment by mwobensmith** [comment]
The goal here is to decouple `iris` core from projects that use it, such as `iris_firefox`.

The `iris` core project includes the test API, test harness (built around `pytest`), utility functions, main scripts to invoke the project, and Control Center. 

Inside the package, these elements are discrete, which enables people to import just the parts they want, such as the API, for example. However, we are not breaking any of this out into separate repos or packages.

**Comment by mwobensmith** [comment]
Merged.
