### ISSUE TITLE
Refactor API from camel case to lowercase/underscores

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#568]
When we began Iris, we built it on top of Sikuli. Supporting the Sikuli API is a fundamental part of the project. 

However, one aspect of supporting this API is its use of camel case, which likely exists because that project is based in Java. Since we are a Python project, we'd prefer to use lowercase and underscores. 

We can support this API in principle, while presenting it in a Python syntax. Therefore, before we launch a 1.0 project, we will refactor the API as lowercase/underscores. This will be the preferred API in Iris. However, we will retain the previous camel case API as a legacy layer that calls into the same code. When a test case calls the legacy API, it will work as expected, but will log a warning [1] that the API is deprecated.

This will require a project-wide refactor, and while that might seem significant, it is a simple find and replace. Any old API calls will be easy to isolate and fix, and won't affect the stability of the project.

Example:

```
def key_up(key)
    # implementation here

def keyUp(key):
    logger.warning('Use of deprecated method \'keyUp\'. Use \'key_up\' instead.')
    key_up(key)

```

[1] TBD: logging a warning vs. raising an exception.

**Comment by mwobensmith** [comment]
Another option is just to remove all camel case instances and move to Python syntax 100%, once and for all. When we are in a post-1.0 state, this kind of decision will be far more painful, and it would be nice to get it right now.

**Comment by silviuFlorin** [comment]
We decided to move to a 100% Python syntax. I will mark this issue as duplicate for #810 and close it. Changes already done and merged
