### ISSUE TITLE
Increase 'exists' timeout for the History tests

### ISSUE THREAD

**Issue by psilaghi** [mozilla/iris#570]
My 'History' tests are intermittently failing because sometimes the test pages aren't loading with 'exists' timeout=5s.
I'm increasing the timeout to 10s, as it is used in the most of the tests.

**Comment by mwobensmith** [comment]
See also #524

**Comment by psilaghi** [comment]
Closing this as merged.
Filed #588 to include the fix from #524 in the 'history_menu' test.
