### ISSUE TITLE
Test 'library_controls' intermittently failing on Mac

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#572]
Work with @silviuFlorin to see why this fails for him.

For me, it seems to fail on line 74, when it checks for the restored window. On Mac, we currently don't have a good way, in general, to restore minimized auxiliary windows. 

If test fails on line 74 for you, it's likely because the logic from lines 63-68 are fragile. Replace these with a call to `open_library()` and see if this solves the problem.

**Comment by psilaghi** [comment]
Both Silviu and I could no longer reproduce the problem.
Anyway, it seems that calling open_library() again restore the library window from the taskbar on Mac, so I updated the test with this change. Thanks for the tip.
Branch [issue_572] ready to review.

**Comment by tracywalker** [comment]
yes, looks good, merging to dev now.
