### ISSUE TITLE
When the --treeherder flag is used, add a specially formatted line giving a summary of the test run.

### ISSUE THREAD

**Issue by KWierso** [mozilla/iris#577]
If you select a mochitest job like this [one in Treeherder](https://treeherder.allizom.org/#/jobs?repo=mozilla-central&group_state=expanded&searchStr=5cc23f2d4ceccc34e6efcdf236d7ed911dc21a71&revision=eba9b9f96abca90a38545e532afd154f19ff733f&selectedJob=266229521), one of the items in the job's Job Details panel is the line `mochitest-mochitest-plain-chunked: 857/0/0`

That line shows the job type, followed by a summary of the pass/fail/exception counts for all of the tests that ran in this job. I feel like this would be a useful thing to add to Iris's output when the --treeherder flag is being used.

To get a line like this parsed out of the log, it needs to begin with the string `TinderboxPrint: ` followed by the string you want bolded, followed immediately by a `<br/>`, followed by the rest of the line.

An easy way to do this would probably be creating a new string set to something like `TinderboxPrint: Iris Summary<br/>` if the --treeherder flag is set (empty string if not set), and then add a line after [this line](https://github.com/mozilla/iris/blob/e814c1b5d1b8a8c8c314626892f15dedd180bed7/src/core/util/run_report.py#L45) to be `test_results_str = this_new_string + test_results_str`.

**Comment by KWierso** [comment]
(Or I guess just adding this_new_string at the beginning of that line would be better)

**Comment by KWierso** [comment]
Oh, hrm, `--treeherder` is an iris_firefox thing, isn't it?

**Comment by mwobensmith** [comment]
@KWierso Yes, it is an `iris_firefox` thing, so ultimately we'll make the change over there. However, just give me an idea of how this should look. Can you write sample output so I can fully grasp how to create it? 

I think you want it to start with:
`TinderboxPrint: Iris Summary<br/>`

What comes next?

**Comment by KWierso** [comment]
So at the moment, [Iris prints out](https://treeherder.allizom.org/logviewer.html#/jobs?job_id=266216406&repo=try&lineNumber=10429-10467) the Test Report section like

```
[task 2019-09-14T10:01:53.176Z] ----------------------------------Test Report-----------------------------------
[task 2019-09-14T10:01:53.176Z] Application: Firefox, Platform: linux, fx_version: 71.0a1, fx_build_id: 20190914092153, channel: nightly
[task 2019-09-14T10:01:53.176Z] Passed: 0, Failed: 8, Skipped: 1, Errors 1  -- Total: 10Total time: 00:19:09.645
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] The following tests did not pass:
[task 2019-09-14T10:01:53.176Z] cc_data_not_saved.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] delete_cookies_when_closing.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] form_inputs_not_saved.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] no_browsing_download_history.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] no_cookies_from_visited.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] no_search_form_history.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] no_third_party_cookies.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] private_browsing_autofill.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] saved_cc_available_in_private_session.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] --------------------------------------------------------------------------------
```

I would say there's two ways to do this. Either change the Test Report section to print out
```
[task 2019-09-14T10:01:53.176Z] ----------------------------------Test Report-----------------------------------
[task 2019-09-14T10:01:53.176Z] Application: Firefox, Platform: linux, fx_version: 71.0a1, fx_build_id: 20190914092153, channel: nightly
[task 2019-09-14T10:01:53.176Z] Tinderboxprint: Iris Summary<br/>Passed: 0, Failed: 8, Skipped: 1, Errors 1  -- Total: 10Total time: 00:19:09.645
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] The following tests did not pass:
[task 2019-09-14T10:01:53.176Z] cc_data_not_saved.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] delete_cookies_when_closing.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] form_inputs_not_saved.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] no_browsing_download_history.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] no_cookies_from_visited.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] no_search_form_history.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] no_third_party_cookies.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] private_browsing_autofill.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] saved_cc_available_in_private_session.py
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] 
[task 2019-09-14T10:01:53.176Z] --------------------------------------------------------------------------------
```

Or we could re-create that line in the CI Test Results section:
```
[task 2019-09-14T10:01:53.216Z] CI Test results:
[task 2019-09-14T10:01:53.216Z] Tinderboxprint: Iris Summary<br/>Passed: 0, Failed: 8, Skipped: 1, Errors 1  -- Total: 10Total time: 00:19:09.645
[task 2019-09-14T10:01:53.216Z] TEST-UNEXPECTED-FAIL | anti_tracking | cc_data_not_saved.py | Test page is opened in a new private window.
[task 2019-09-14T10:01:53.216Z] TEST-UNEXPECTED-FAIL | anti_tracking | delete_cookies_when_closing.py | The Preferences > Privacy page is successfully displayed
[task 2019-09-14T10:01:53.216Z] TEST-UNEXPECTED-FAIL | anti_tracking | form_inputs_not_saved.py | Test page is opened in a new private window.
[task 2019-09-14T10:01:53.217Z] TEST-UNEXPECTED-FAIL | anti_tracking | no_browsing_download_history.py | The "about:preferences#privacy" page is successfully displayed
[task 2019-09-14T10:01:53.217Z] TEST-UNEXPECTED-FAIL | anti_tracking | no_cookies_from_visited.py | The "about:preferences#privacy" page is successfully displayed.
[task 2019-09-14T10:01:53.217Z] TEST-UNEXPECTED-FAIL | anti_tracking | no_search_form_history.py | The page is successfully displayed.
[task 2019-09-14T10:01:53.217Z] TEST-UNEXPECTED-FAIL | anti_tracking | no_third_party_cookies.py | The privacy preferences page is successfully displayed.
[task 2019-09-14T10:01:53.217Z] TEST-UNEXPECTED-ERROR | anti_tracking | private_browsing_autofill.py | Unable to find pattern name_field.png
[task 2019-09-14T10:01:53.217Z] TEST-UNEXPECTED-FAIL | anti_tracking | saved_cc_available_in_private_session.py | Preferences page is opened
[task 2019-09-14T10:01:53.217Z] 
```

**Comment by mwobensmith** [comment]
Ah, OK, very helpful.

I see a run-on line there - is this intended? No line break between `Total: 10` and `Total time:`.

**Comment by KWierso** [comment]
The total time string seems to be generated by this line https://github.com/mozilla/iris_firefox/blob/17cc93f88147f4af7314595e9fb8ec1d75e6347d/src/core/util/run_report.py#L51

When that gets put together with the rest of the test results in https://github.com/mozilla/iris_firefox/blob/17cc93f88147f4af7314595e9fb8ec1d75e6347d/src/core/util/run_report.py#L53-L55 it doesn't seem to be adding any spaces.

I'd suggest tweaking line 51 to begin with a single space to pad it out. Or move the total_time string generation up above the line where test_results_str is created so total_time_str can be part of it from the beginning, properly spaced.

**Comment by KWierso** [comment]
I'd say that spacing issue should be fixed regardless of whether we're in --treeherder mode, to be honest.

**Comment by mwobensmith** [comment]
OK, you got it. I will close this issue and open one in `iris_firefox`. When do you need this by?

**Comment by KWierso** [comment]
No rush. This is just a nice-to-have, rather than an important feature.

**Comment by mwobensmith** [comment]
Closing, migrated to `iris_firefox` repo [here](https://github.com/mozilla/iris_firefox/issues/3840).
