### ISSUE TITLE
Test 'create_region.py' fails on Windows

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#586]
Error encountered in test, outcome: >>> ERROR <<<

--------------------------------------------------------------------------------
» Traceback (most recent call last):                                           «
»   File "c:\iris\iris\test_runner.py", line 59, in run                        «
»     current.run()                                                            «
»   File "c:\iris\iris\tests\experiments\create_region.py", line 22, in run    «
»     r = create_region_from_patterns(left='home.png', right='library.png')    «
»   File "c:\iris\iris\api\core.py", line 1520, in create_region_from_patterns «
»     p2.x = current_pattern.x + w                                             «
»   File "c:\iris\iris\api\core.py", line 705, in setX                         «
»     raise ValueError(INVALID_NUMERIC_INPUT)                                  «
» ValueError: Expected numeric value                                           «
--------------------------------------------------------------------------------

**Comment by mwobensmith** [comment]
@icrisan I have turned off the test, and added some debug info. 

Can you run it on the 'dev' branch, like this, and tell me what appears in the console?

`iris -t create_region -o -i DEBUG`

There should be debug output following this:

> Debugging create_region for pattern home.png:

And possibly this:

> Debugging create_region for pattern library.png:

Copy/paste it here. Thank you!

**Comment by mwobensmith** [comment]
Thanks for the tip, @icrisan. I made the change as you suggested. I hope that works.
