### ISSUE TITLE
Prevent Iris from running if certain keys are locked

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#592]
If `Key.NUM_LOCK` is on, Iris does not reliably receive certain key input and cannot function correctly. Similarly, if `Key.CAPS_LOCK` is on, that likely affects what we see via `type`, so we don't want that engaged either.

Now that we are getting `Key.isLockOn` via #301, we can use it to detect this state and prevent Iris from running. We'll display a meaningful message, such as `"Key.CAPS_LOCK is currently on. Please turn it off in order to run Iris."` This goes for `Key.NUM_LOCK` and `Key.SCROLL_LOCK` as well.

**Comment by mwobensmith** [comment]
Hi @silviuFlorin can you review this? If it works, and you are happy with it, approve it and have @icrisan land it. If you don't like it, feel free to change it as you see fit and get it landed. I trust your judgment.

**Comment by silviuFlorin** [comment]
@mwobensmith i made the check_keyboard_state() method static and rebased with dev branch. Code approved.
