### ISSUE TITLE
Better recovery when runtime errors are found in tests during collection phase

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#593]
If tests in the project have runtime errors, Iris will shut down with little indication of the problem. If you turn on `-i DEBUG` you'll see the errors, but there should be a better recovery and/or reporting of the problem so that it's not a mystery. Currently you will just see Iris going through its setup process, only to exit with zero tests run. We can do better.

**Comment by KWierso** [comment]
At a minimum, running zero tests should probably be considered a failure case, exiting with some non-zero value. This would let things like the CI scripts see that something's gone wrong and can report the run as a failure. Right now it just shows it as a passing run.

**Comment by mwobensmith** [comment]
Already filed as #440 but I'll close that one and keep this one.
