### ISSUE TITLE
Fix the auxiliary window control button helper functions.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#597]
These functions are currently not robust at all on Mac, because of the color and/or hover state of the controls.  I have seen close_auxiliary_button() click the minimize button. I have seen the functions just fail because they are looking for an un-hovered state, but the mouse is hovering the controls.

I will repair the functions related to the auxiliary control buttons to be consistent and more robust such that they always work correctly.

I think this is mostly a Mac issue.  However, while I am working on these functions, I will make sure everything is solid on Windows and Linux as well.

**Comment by tracywalker** [comment]
two options here.  hover the three buttons then get captures of those hovered buttons.
or
use a three button capture and setup offsets for each button off center.

**Comment by mariusandreifilip** [comment]
created branch issue_597 for review
- updated the auxiliary control patterns for osx and added new one for the auxiliary controls bar
-updated  close auxiliary method and created a method for minimize
-full_screen in Osx needed to be treated differently and created a new method and added patterns
