### ISSUE TITLE
create a docker image to build and run iris

### ISSUE THREAD

**Issue by kimberlythegeek** [mozilla/iris#610]
- [x] write a Dockerfile to build iris-core
- [ ] use the docker image for running linting and tests in Travis
- [ ] update all documentation and usage instructions
- [ ] verify integration with [iris_firefox](https://github.com/mozilla/iris_firefox) and update usage documentation

**Comment by mwobensmith** [comment]
Got it to run once we put in the missing step:

```
Xvfb :99 -screen 0 1920x1080x24+32 +extension GLX +extension RANDR > /dev/null 2>&1 &
```

Now what we have are some warnings/errors:
```
Xlib.xauth: warning, no xauthority details available
Xlib.xauth: warning, no xauthority details available
Xlib.xauth: warning, no xauthority details available
Xlib.xauth: warning, no xauthority details available
/bin/sh: 1: xset: not found
Cannot run Iris because CAPSLOCK is on. Please turn it off to continue.
Failed platform check, closing Iris.
```

The `xset` program is required to be able to query the locked keys on the keyboard. We need to find out why it's not available. There is the workaround of passing `-n` for now but we'll have to fix this somehow.
