### ISSUE TITLE
Improve debug image creation

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#615]
The message for pattern not found can cover up much of the region or screen making it difficult to determine of the pattern is actually on screen or not.

The message 
[pattern] <<< Pattern not found
has a long white tail from left of debug image across the screen to the right of the image.  This white space is the height of the actual [pattern]. If the pattern is large, it obscures much of the screen.  If the pattern is not so tall, but is being searched for in a restricted region, the white space ion this case can also obscure displaying most of the region under search.

Can all the excess white space of the 'tail' be removed?

**Comment by mwobensmith** [comment]
@tracywalker Please confirm that this is what you want.


Old:
![old](https://user-images.githubusercontent.com/3019057/66516708-8a6e7700-ea96-11e9-8280-75d14c1e6780.jpg)

New:
![new](https://user-images.githubusercontent.com/3019057/66516712-8fcbc180-ea96-11e9-84c4-aeda5bd355e7.jpg)

**Comment by tracywalker** [comment]
confirmed this is fixed in package version 0.7
