### ISSUE TITLE
Optimize number of debug images created

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#620]
Iris scans a region to look for a pattern. It scans a certain amount of times per second, based on `Settings.wait_scan_rate` - current default of 3. It scans for a certain amount of seconds, either set by the user per API or taken from `Settings.auto_wait_timeout`, current default of 3. 

So, in the above base case, an image that is not found will be searched 9 times, and the same amount of debug images will be written to disk. If you have the default `-m` (max_tries) value of 3 for your run, this failing test will be run 3 times and create 27 images. 

This is far too many images, as they look the same and take up more disk space than desired.

There are ways to optimize this, but it seems at a minimum that we should only generate one image per second in the "not found" case. This would decrease the above quantity by 67%. Seems like a good first step.

**Comment by tracywalker** [comment]
This looks like it has been reduced some. We're down from ~15 per second to 5 or 6 per second.  Definitely not yet capturing/saving about 1 image per second.

**Comment by tracywalker** [comment]
My bad,  i hadn't correctly picked up the fix. This is correctly working by capturing debug image about every 1 second.
