### ISSUE TITLE
History tests are still intermittently failing

### ISSUE THREAD

**Issue by psilaghi** [mozilla/iris#627]
It seems that #570 didn't completely solve the problem.
Youtube.com sometimes is not loading properly.

**Comment by IonutBudeanu** [comment]
History tests are currently failing on MAC.

Here's the Traceback for the following tests:

- history_menu

- history_sidebar

- history_sidebar_sorting

» Traceback (most recent call last):                                                                                   
»   File "/Users/ionutbudeanu/mozilla/iris/venv/bin/iris", line 11, in <module>                                        
»     load_entry_point('iris', 'console_scripts', 'iris')()                                                            
»   File "/Users/ionutbudeanu/mozilla/iris/iris/__main__.py", line 37, in main                                         
»     Iris()                                                                                                           
»   File "/Users/ionutbudeanu/mozilla/iris/iris/__main__.py", line 51, in __init__                                     
»     test_runner.run(self)                                                                                            
»   File "/Users/ionutbudeanu/mozilla/iris/iris/test_runner.py", line 59, in run                                       
»     current.run()                                                                                                    
»   **File "/Users/ionutbudeanu/mozilla/iris/iris/tests/history/history_menu.py", line 35, in run                        «
»     assert_true(self, expected_1, 'Page loaded successfully.')**                                                       
»   File "/Users/ionutbudeanu/mozilla/iris/iris/asserts.py", line 31, in assert_true                                   
»     assert_equal(test_case, actual, True, message)                                                                   
»   File "/Users/ionutbudeanu/mozilla/iris/iris/asserts.py", line 26, in assert_equal                                  «
»     test_case.add_results('FAILED', message, actual, expected, print_error(format_stack(traceback.extract_stack()))) «

**Comment by psilaghi** [comment]
Fixed by #732.
