### ISSUE TITLE
Scoop package is not getting installed despite multiple restart - Windows 7

### ISSUE THREAD

**Issue by ranjit-exalt** [mozilla/iris#629]
When I am running bootstrap.sh in windows 7, It is asking to restart terminal twice to use scoop. I restarted terminal multiple times, it doesn't work and showing the same message whenever I run "bootstrap.sh". I even restarted my windows a couple of times, but no luck. 

Its working fine for other OS (Win 10, Mac and Linux)

![Windows bootstrap issue](https://user-images.githubusercontent.com/54833244/67581764-389c4100-f766-11e9-9ca6-e6992d0e6211.PNG)

**Comment by mwobensmith** [comment]
@ranjit-exalt How do we know that Scoop is not installed? The message above indicates success. Have you tried to run Iris after running the bootstrap script?

**Comment by ranjit-exalt** [comment]
@mwobensmith There is no scoop folder present in windows 7. So I understood no scoop installed. For my Windows 10 machine, I can see scoop folder here C:\Users\user_name\scoop. 

I am unable to activate the virtual environment so iris won't run. Attaching screenshot for your reference:

![Windows bootstrap issue_2](https://user-images.githubusercontent.com/54833244/67709670-6abad680-f9e4-11e9-916d-8e61466f1e48.PNG)
:

**Comment by ranjit-exalt** [comment]
@mwobensmith : I tried to run lines 19 and 20 manually but no luck. So as suggested, I followed steps given at scoop.sh website. It worked. After scoop creation, I repeated "sh bootstrap.sh". It installed everything other than pip3.7. I was getting this error: 

![image](https://user-images.githubusercontent.com/54833244/67761954-4efa1380-fa6a-11e9-8710-b3470d6be960.png)

There is an open ticket ( #626 ) for the same issue so I followed the solution given there. This suggests modifying bootstrap/win_bootstrap.sh as python 3.8 was getting installed with the command  "scoop install python" hence pip3.7 wasn't working. So after modifying changes as per (#628 ) pull request, I reinstalled scoop (uninstall -> install again). Python 3.7.5 got installed but pip issue was still there with a new error message: 

![image](https://user-images.githubusercontent.com/54833244/67762531-aa78d100-fa6b-11e9-8226-7b0e1442f021.png) 

I removed everything (scoop and iris_firefox) and repeated the process but no luck. Please help.

**Comment by mwobensmith** [comment]
@ranjit-exalt What version of Windows 7 are you on? Have you upgraded to SP1? Can you perform a Windows Update to make sure that you're on the latest versions of all system software?

What version of Powershell are you running? You can find out by typing this:
`powershell -Command "(Get-Host).Version"`

**Comment by mwobensmith** [comment]
More things to try:
`python --version`
`python3 --version`
`python37 --version`
`pip --version`
