### ISSUE TITLE
Research use of threads in Iris

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#630]
Issue #624 seems to point to a threading issue that causes unnecessary blocking in test execution. This requires us to investigate use of threads in Iris. 

@echim and @silviuFlorin , please research what this means to solve #624 and how this can help us in general in Iris. When you have done some research, please post your findings in this Git issue so we can decide what to do next.

**Comment by silviuFlorin** [comment]
A small explanation of what is happening in #624:

With our current implementation we have a setting for the rate an image search is done every second (currently 3 searches per second). At the beginning of an exists we calculate the total number of searches based on the max time passed as parameter and the DEFAULT_WAIT_SCAN_RATE setting. Until we reach the number of searches calculated above we are executing an image search with a time sleep of 0.33 (1 second / DEFAULT_WAIT_SCAN_RATE) between each call. With this implementation we will exceed the desired time with the duration of each executed search. 

To fix this issue we will have to use multithreading or multiproccesing. Both are supported by python built in packages

**Comment by silviuFlorin** [comment]
Multiprocessing
Pros

    Separate memory space
    Code is usually straightforward
    Takes advantage of multiple CPUs & cores
    Avoids GIL limitations for cPython
    Eliminates most needs for synchronization primitives unless if you use shared memory (instead, it's more of a communication model for IPC)
    Child processes are interruptible/killable
    Python multiprocessing module includes useful abstractions with an interface much like threading.Thread
    A must with cPython for CPU-bound processing

Cons

    IPC a little more complicated with more overhead (communication model vs. shared memory/objects)
    Larger memory footprint

Threading
Pros

    Lightweight - low memory footprint
    Shared memory - makes access to state from another context easier
    Allows you to easily make responsive UIs
    cPython C extension modules that properly release the GIL will run in parallel
    Great option for I/O-bound applications

Cons

    cPython - subject to the GIL
    Not interruptible/killable
    If not following a command queue/message pump model (using the Queue module), then manual use of synchronization primitives become a necessity (decisions are needed for the granularity of locking)
    Code is usually harder to understand and to get right - the potential for race conditions increases dramatically

**Comment by silviuFlorin** [comment]
Based on the above pros and cons I suggest using multiprocessing as it is more fit for Iris needs

**Comment by silviuFlorin** [comment]
Python multiprocessing documentation: https://docs.python.org/2/library/multiprocessing.html

**Comment by mwobensmith** [comment]
Thanks for the replies, @silviuFlorin . My next question is what, in Iris, requires multiprocessing? Should our image searches be done concurrently? Anything else?

I would like to understand the engineering impact - amount of code we will touch, time estimates, risk and reward, etc.

**Comment by silviuFlorin** [comment]
@mwobensmith We could use multiprocessing for image search or observers for starters. I've implemented multiprocessing image search in branch issue_624_multiprocessing that is done and ready for review. 

I had to optimize a lot of code to fully benefit from multiprocessing. Of course, we could have just touched some small parts of code but the performance gain would have been minimal.

**Comment by mwobensmith** [comment]
This was already addressed in our multiprocessing work in #624, so closing.
