### ISSUE TITLE
Create debug script to help users who can't get Iris to run

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#632]
It would be nice to provide a Python (or other) script that does some environment investigation in the event that a user can't run iris. 

This could:
* debug Python, virtualenv, and others
* Perform simple pattern search
* Report on installed Python libraries
* List important environment factors - OS, screen resolution, etc.

Other features TBD.

This could be a standalone script, a mode of Iris, or set of instructions. Just recording the concept here, so we can discuss implementation details.

**Comment by mwobensmith** [comment]
More thoughts: 

I think the user should go through the steps to install Iris, and if it fails, use this script to debug. Therefore, they should at least have run the bootstrap script and followed instructions. At that point, they can be instructed to run this script in the current environment. 

My vision is that we go through each check, print out details of what we find, and if we get a failure, we stop and explain why Iris can't run on this configuration. Bonus: suggest what they can do to fix it.

- Check Python version (2.7.14)
- Check pip, virtualenv, other Python dependencies
- Check 7zip, Tesseract
	- If Mac, check xquartz
- Check Firefox local install
- Check Git
- Check screen resolution
	- Must be greater than 1280x800
- Check platform 
	- We currently support Mac OSX 10.13, Ubuntu Linux 16.04, Windows 10 (Win 7 planned)
- Perform a pattern search
- Test one or more keyboard modifiers

**Comment by AndreiH** [comment]
@mwobensmith , the bash script is now ready for review on branch `issue_632`

**Comment by AndreiH** [comment]
@mwobensmith , the Python script is ready for review. Branch: `issue_632`
We currently check for:
```Testing Libraries imports
Testing Mozdownload
Testing Mozrunner
Testing OpenCV
Testing PyAutoGui
Testing MSS
Testing Pytesseract```
Of course we can add more coverage as we go, based on user experience.
