### ISSUE TITLE
Implement fallback logic if mss screenshot fails

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#635]
We used to have logic that utilized either `pyautogui` or `mss` to take screenshots, depending on platform. That's because we ran into intermittent issues with both failing at various intervals. Seems that someone took out the fallback logic that we used to have (but left the logging message intact...) so I will reinstate the original code.

**Comment by tracywalker** [comment]
From our weekly meeting, this didn't seem to help on Linux.
