### ISSUE TITLE
Create a function in general.py which creates a region starting from the hamburger menu image

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#638]
Right now we have duplicate code in each zoom_indicator test regarding this region.
To remove the duplicate code I will create a function in general.py.

**Comment by icrisan** [comment]
Created branch issue_638. Please review.

**Comment by silviuFlorin** [comment]
Code approved

**Comment by tracywalker** [comment]
create_region_for_url_bar() should do so without having to pass in a coordinate from test case then hard coding define the area.  Instead, have create_region_for_url_bar() call create_region_from_patterns() (in core.py) by passing to create_region_from_patterns() two images, say one for the home button and one for the hamburger button.

**Comment by icrisan** [comment]
Updated branch issue_638. Please review.

**Comment by silviuFlorin** [comment]
Helped @icrisan with updating create_region_from_patterns() to accept padding parameters in case we want to extend the region and creating create_region_for_url_bar() and create_region_for_hamburger_menu() methods.

Code approved
