### ISSUE TITLE
Support Wayland on Linux

### ISSUE THREAD

**Issue by ashughes1** [mozilla/iris#638]
Most if not all of the mainstream Linux distributions have switched over to Wayland by default instead of X11. This presents issues related to grabbing the screen such as issue #621. For now we need to default to X11 to work around this issue (I can update the docs to reflect this) but we should really add support for Wayland if at all possible.

**Comment by mwobensmith** [comment]
We currently use X11 for virtual keyboard support. Can you explain how we add support for Wayland and what effect that has on our use of `mss` and `pyautogui`, our current solutions for screen capture? Are we replacing our screen capture libraries with something else?
