### ISSUE TITLE
Investigate click duration

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#643]
I noticed if I set a click duration (the time it takes to move the mouse for the current location to the click location) that it seems to click twice.  I set duration = 1 as a parameter of click(pattern, duration = 1) when clicking the hamburger menu (pattern = NavBar.HAMBURGER_MENU).

The menu is opened then closed immediately (like the menu was clicked twice).  If I remove the duration, the menu remains open as expected from a single click.

**Comment by mwobensmith** [comment]
@tracywalker I'm not seeing this with my own basic tests. Can you give me a more precise example? Is there a test case I can alter to see this?

**Comment by tracywalker** [comment]
hmmm, maybe restore_firefox_focus first.  also I saw this in mac non-retina with nightly target.

**Comment by mwobensmith** [comment]
I experimented with this helper method, and tried some test cases that used it. Was not able to see any change in behavior. Closing for now, reopen if you get more information.
