### ISSUE TITLE
Create classes to reference commonly-used Iris images

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#647]
We use strings to reference images all over the project - in core code as well as test cases. We currently look those up, in a global scope, via file name. The global nature of image loading will change with #590 and it seems that people should be using a central class with static properties to access commonly-used images, rather than string file names.

We need some sort of core class(es) such as `FirefoxUI`, under which we could have properties like `HOME_BUTTON`, `HAMBURGER_MENU`, etc. These would be `Pattern` objects and could be passed to typical functions like `exists`, `wait`, etc. 

Also, when we land the local web server, tests should be able to access the page content via class static constants instead of having to know a given file name. This might be something like `LocalWeb.FIREFOX_LOGO` or `LocalWeb.MOZILLA_BOOKMARK`, for example. 

We could even consider a class to handle third-party images, such as the Google search button, which is used across tests. This is less of a priority, as we move away from using these sites and towards our own local web content.

This work is to follow #590.

**Comment by silviuFlorin** [comment]
Small changes should be made in image_search functions as well. We are currently checking if image is instance of str. This will be replaced with the name of the new class

**Comment by mwobensmith** [comment]
The more I look at the UI assets in the Firefox source tree, the more I realize that this directory is *not* organized into a logical Firefox UI object model. They don't break out assets into subcategories, like "bookmarks", "window", etc. I think we should use the [Firefox Puppeteer API](http://firefox-puppeteer.readthedocs.io/en/master/)'s object model.


From a technical perspective, here's what I would do now.

* Go through the Iris project and identify all images of Firefox UI that we are actually using. There are probably less than 10.

* Identify where these patterns belong in our object model. This is the most difficult part, because we will need to classify our patterns and map them to the right APIs. Again, we should use the existing Firefox Puppeteer API. For starters, the `"home.png"` pattern belongs inside module `toolbars`, class `NavBar`. 

* Create the Iris Firefox UI modules that will expose these UI assets to the project.
e.g:
/iris/api/core/firefox_ui
/iris/api/core/firefox_ui/toolbars.py

* Move those images to the correct "images" directories.
e.g:
/iris/api/core/firefox_ui/toolbars/images/common
/iris/api/core/firefox_ui/toolbars/images/osx
/iris/api/core/firefox_ui/toolbars/images/win
/iris/api/core/firefox_ui/toolbars/images/linux

* In the modules within `firefox_ui`, create the classes and constants for the images that we use today. 

Inside `toolbars.py`:

```
class NavBar():
    HOME = Pattern('home.png')
```

* Everywhere in our code that references these patterns, replace with the new constants:

```
from iris.api.core.firefox_ui.toolbars import NavBar

    # goes inside a test case method
    result = exists(NavBar.HOME, 5)
    # etc.
```

**Comment by silviuFlorin** [comment]
@mwobensmith Until now I identified 5 Firefox UI image from NavBar:

```
class NavBar(object):
    HOME_BUTTON = Pattern('home_button.png')
    BACK_BUTTON = Pattern('back_button.png')
    FORWARD_BUTTON = Pattern('forward_button.png')
    HAMBURGER_MENU = Pattern('hamburger_menu.png')
    LIBRARY_MENU = Pattern('library_menu.png')
```

I moved these files to /iris/api/core/firefox_ui/toolbars/images/ ... and updated all helpers and tests with the new references. 
I also cleaned up a few unused images. 

Please review branch issue_647_1

**Comment by mwobensmith** [comment]
Great! What's left?

**Comment by mwobensmith** [comment]
@silviuFlorin This is good, I agree. 

As far as dev tools, I don't see anything in the [Firefox Puppeteer API index](http://firefox-puppeteer.readthedocs.io/en/master/genindex.html), so I guess we should make a module for it as a child of `firefox_ui`.

**Comment by silviuFlorin** [comment]
@mwobensmith please review branch issue_647_952

For this issue I am left with dev tools
