### ISSUE TITLE
Remove xquartz requirement

### ISSUE THREAD

**Issue by m8ttyB** [mozilla/iris#651]
Experiment, can xquartz be removed as a requirement. Linking to [bug 1598660](https://bugzilla.mozilla.org/show_bug.cgi?id=1598660) for continuity.

**Comment by m8ttyB** [comment]
Per the above bug, we'll go the route of remove the `xquartz` dependency from the taskcluster work.

**Comment by mwobensmith** [comment]
@m8ttyB If you start Iris with `-n` then Iris doesn't rely on Xquartz. We wouldn't have to do any code work to support that. Does that suffice?

**Comment by m8ttyB** [comment]
Sounds excellent. The builds on taskcluster are already configured to use the `-n` flag so we should be good to go.
