### ISSUE TITLE
Make dragDrop() use image center as target

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#665]
It appears to me the the upper left corner is being used as targets from grab and drop images.   In particular, If the image isn't crafted in such a way that the upper left corner occupies part of the draggable target element,  dragDrop() will not pick up what it is supposed; it just clicks and drags nothing to its destination.  If we ensure dragDrop() uses center coordinates of the drag_from parameter image, we're more likely to pick up the intended image.

**Comment by silviuFlorin** [comment]
@mwobensmith Created branch issue_665. Please review
