### ISSUE TITLE
Dependabot PRs are failing to update setup.py

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#670]
I noticed that Dependabot PRs are failing Travis CI builds, and it appears to be because they only update the `Pipfile`. They leave `setup.py` unchanged, and when the build happens, there is a version mismatch.

Is this something to be configured on the Dependabot side?

**Comment by kimberlythegeek** [comment]
Honestly I’m unsure if dependabot handles `setup.py` files. As far as I know it looks for the requirements files of various languages, i.e. `requirements.txt` or `Pipfile` for python requirements, `package.json` for npm requirements, etc. 

I will look into this.
