### ISSUE TITLE
Split the 'history_menu.py' test in smaller pieces

### ISSUE THREAD

**Issue by psilaghi** [mozilla/iris#671]
'history_menu.py' covers the following tests:
[History menu](https://testrail.stage.mozaws.net/index.php?/cases/view/118799)
[Open a website in the current tab](https://testrail.stage.mozaws.net/index.php?/cases/view/118800)
[Open a website in a new tab](https://testrail.stage.mozaws.net/index.php?/cases/view/118802)
[Open a website in a new window](https://testrail.stage.mozaws.net/index.php?/cases/view/118805)
[Open a website in a private window](https://testrail.stage.mozaws.net/index.php?/cases/view/118806)
[Open websites from the History tab via menu button](https://testrail.stage.mozaws.net/index.php?/cases/view/118807)
[Open websites from the History tab via menu button from a Private window](https://testrail.stage.mozaws.net/index.php?/cases/view/118808)

We need one Iris test for each test in TestRail.

**Comment by silviuFlorin** [comment]
Code approved for History menu test

**Comment by silviuFlorin** [comment]
Code approved for Open a website in the current tab test

**Comment by silviuFlorin** [comment]
Code approved for Open a website in a private window test

**Comment by silviuFlorin** [comment]
Code approved for ﻿﻿Open a website in a private window

**Comment by silviuFlorin** [comment]
Reviewed code for Open websites from the History tab via menu button test. Updated the way top right corner of the screen is taken. Code approved

**Comment by silviuFlorin** [comment]
Reviewed code for Open websites from the History tab via menu button from a Private window test. Updated the way top right corner of the screen is taken. Code approved
