### ISSUE TITLE
Split the 'history_sidebar.py' test in smaller pieces

### ISSUE THREAD

**Issue by psilaghi** [mozilla/iris#672]
'history_sidebar.py' covers the following tests:

[History sidebar](https://testrail.stage.mozaws.net/index.php?/cases/view/118811)
[Search in History sidebar for an available website](https://testrail.stage.mozaws.net/index.php?/cases/view/119440)
[Search in History sidebar for an unavailable website](https://testrail.stage.mozaws.net/index.php?/cases/view/119441)
[Dismiss the search from the History sidebar](https://testrail.stage.mozaws.net/index.php?/cases/view/119442)

We need one Iris test for each test in TestRail.

**Comment by silviuFlorin** [comment]
Code approved for History sidebar test - branch issue_672_1

**Comment by silviuFlorin** [comment]
Removed unnecessary time.sleep call. Code approved for Search in History sidebar for an available website test - branch issue_672_2

**Comment by silviuFlorin** [comment]
Removed unnecessary time.sleep call. Code approved for Search in History sidebar for an unavailable website - branch issue_672_3

**Comment by silviuFlorin** [comment]
Removed unnecessary time.sleep calls. Code approved Dismiss the search from the History sidebar test - branch issue_672_4
