### ISSUE TITLE
Add support for window control keyboard shorts cuts for Fluxbox on Linux

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#673]
The Iris Firefox tests use keyboard shortcuts to maximize the screen.  The Fluxbox environment is not responding to those keyboard shortcuts. File this to track work to get this working correctly.

**Comment by kimberlythegeek** [comment]
What is the shortcut Iris currently uses to maximize the window?

**Comment by tracywalker** [comment]
> What is the shortcut Iris currently uses to maximize the window?

On Linux it is ctrl+meta+down
