### ISSUE TITLE
Split the 'history_sidebar_sorting.py' test in smaller pieces

### ISSUE THREAD

**Issue by psilaghi** [mozilla/iris#673]
'history_sidebar_sorting.py' covers the following tests:

[Sorting options from the sidebar](https://testrail.stage.mozaws.net/index.php?/cases/view/119443)
[Sorting options from the sidebar - By Date and Site](https://testrail.stage.mozaws.net/index.php?/cases/view/119444)
[Sorting options from the sidebar - By Site](https://testrail.stage.mozaws.net/index.php?/cases/view/119445)
[Sorting options from the sidebar - By Date](https://testrail.stage.mozaws.net/index.php?/cases/view/119446)
[Sorting options from the sidebar - By Most Visited](https://testrail.stage.mozaws.net/index.php?/cases/view/119447)
[Sorting options from the sidebar - By Last Visited](https://testrail.stage.mozaws.net/index.php?/cases/view/119448)

We need one Iris test for each test in TestRail.

**Comment by silviuFlorin** [comment]
Reviewed branch issue_673_1. Code approved for Sorting options from the sidebar test

**Comment by silviuFlorin** [comment]
Reviewed branch issue_673_2. Code approved for Sorting options from the sidebar - By Date and Site test

**Comment by silviuFlorin** [comment]
Reviewed branch issue_673_4. Code approved for Sorting options from the sidebar - By Date test

**Comment by silviuFlorin** [comment]
﻿﻿Reviewed branch issue_673_5. Code approved for Sorting options from the sidebar - By Most Visited test

**Comment by silviuFlorin** [comment]
﻿Reviewed branch issue_673_6. Code approved for Sorting options from the sidebar - By Last Visited test
