### ISSUE TITLE
Split the 'add_open_delete_bookmarks.py' in smaller tests

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#681]
'add_open_delete_bookmarks' covers the following test cases:

- [Websites can be bookmarked via star-shaped button.](https://github.com/mozilla/iris/issues/139)

- [Websites can be bookmarked via keyboard shortcut](https://github.com/mozilla/iris/issues/140)

- [Bookmarks can be opened from the Bookmarks Sidebar.](https://github.com/mozilla/iris/issues/146)

- [Bookmarks can be opened from the Library](https://github.com/mozilla/iris/issues/148)

- [Bookmarks can be removed from the Bookmarks Sidebar](https://github.com/mozilla/iris/issues/150)

- [Bookmarks can be removed from the Library](https://github.com/mozilla/iris/issues/151)

We need to split up the tests due to TestRail integration.

**Comment by IonutBudeanu** [comment]
Fixed in -> https://github.com/mozilla/iris/tree/issue_681

Please review.

Thank You

**Comment by silviuFlorin** [comment]
Code approved
