### ISSUE TITLE
Split the 'bookmark_via_url.py' in smaller tests

### ISSUE THREAD

**Issue by IonutBudeanu** [mozilla/iris#682]
'bookmark_via_url.py' covers the following test cases:

- [Websites can be bookmarked via URL drag & drop onto the Bookmarks Toolbar](https://github.com/mozilla/iris/issues/142)

- [Websites can be bookmarked via URL drag & drop onto the Bookmarks Sidebar](https://github.com/mozilla/iris/issues/144)

We need to split up the tests due to TestRail integration.

**Comment by IonutBudeanu** [comment]
Fixed  in -> https://github.com/mozilla/iris/tree/issue_682

Please review.

Thank You

**Comment by silviuFlorin** [comment]
Removed unnecessary time.sleep calls and lowered the dragDrop duration. Code approved
