### ISSUE TITLE
Remove last uses of close_auxiliary_window()

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#692]
click_auxiliary_window_control(button) is what we want to use going forward.  There are some test case that are trying to use the removed close_auxiliary_window() function:
add_open_delete_bookmark.py
save_image_controls.py
confirm_close_multiple_tabs_controls.py

just swap out the call to close_auxiliary_window() with click_auxiliary_window_control('close') in usage.

**Comment by silviuFlorin** [comment]
@tracywalker I found an occurrence of close_auxiliary_window() that you forgot to update in address_crash_reporter(). Fixed it in branch issue_624_multiprocessing
