### ISSUE TITLE
Split core.py into multiple files

### ISSUE THREAD

**Issue by silviuFlorin** [mozilla/iris#704]
Currently core.py has reached a considerable size, becoming harder to maintain. I suggest splitting it into multiple files based on classes that we currently support (Region, Pattern, Settings, etc.). Each class should reside in it's own file. All files should be located under iris/iris/api/core directory. 

To minimize the risks we should do the split progressively, each class at a time
@mwobensmith please provide feedback

**Comment by mwobensmith** [comment]
I am kind of hoping that we keep the core APIs - those that we support from Sikuli - in one file, unless you think that is too big. I guess it's just a matter of opinion.

If we do end up breaking these into files for `Region`, `Pattern`, `Settings`, etc. then I hope we can keep those organized in another subdirectory under "core". We could also consider putting unsupported API classes in there as well, under yet another subdirectory ("unsupported"?) but again, up for debate. 

Also, what should we do with a) code that lives outside methods, and b) methods that begin with underscores that are only intended to be used internally? Should all of this be put in a top-level module on its own?

**Comment by silviuFlorin** [comment]
@mwobensmith This is the current structure of the api package after my latest changes:
```
api
    - core
        - settings
        - platform_iris
        - environment
        - location
        - region
        - screen
    - helpers
        - core_helpers
        - errors
        - general
        - image_remove_noise
        - image_search
        - keyboard_shortcuts
        - ocr_search
        - parse_args
        - save_debug_image
        - version_parser
```

As we discussed, I removed completely the unsupported methods and classes.
Additionally, I did some small code updates for PEP 8 compliance and import optimizations,

**Comment by silviuFlorin** [comment]
Please review branch issue_704

**Comment by mwobensmith** [comment]
After making some changes and reviewing with @silviuFlorin, this is approved for landing as soon as he says so.

**Comment by mwobensmith** [comment]
There may be some PEP-8 stuff I missed. Feel free to correct any errors I may have introduced. 😕

**Comment by silviuFlorin** [comment]
We will merge this branch in it's current state as it needed to unblock other core tasks. Any additional PEP-8 related stuff or code updates will be treated in separate git issues
