### ISSUE TITLE
Store only one occurence of any particular DEBUG image

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#713]
Currently debug images are created and stored for each time Iris attempts to find an image. This can lead to several if not dozens of duplicate images in the output folder.

It would be nice if Iris could store just one copy of a failed debug image for any given operation.

**Comment by mwobensmith** [comment]
I think what we can do is be smarter about when we save an image. Multiple images are OK, especially if they show different stages of activity. However, we shouldn't save many images that don't differ.

We could do something where we compare the current image to write with the previously written one, and if it's the same or slightly different, don't save it. Just a thought.

Also, this tends only to apply to things like `waitVanish`, so we can also be smarter at the API level.

**Comment by mwobensmith** [comment]
This is something we can address in control center redesign.  Maybe we use a photo viewer that has a track that can be clicked on.,

**Comment by mwobensmith** [comment]
We will solve this problem another way, another time, but it's OK for now.
