### ISSUE TITLE
Split the 'zoom_controls_on_location_bar.py' test in smaller pieces

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#718]
'zoom_controls_on_location_bar.py' covers the following tests:
[Location Bar & No Zoom Indicator](https://testrail.stage.mozaws.net/index.php?/cases/view/7444)
[Location Bar Displays Zoom Indicator](https://testrail.stage.mozaws.net/index.php?/cases/view/7445)
[Zoom Indicator Animation](https://testrail.stage.mozaws.net/index.php?/cases/view/7446)
[Zoom Indicator Hides](https://testrail.stage.mozaws.net/index.php?/cases/view/7447)

We need one Iris test for each test in TestRail.

**Comment by icrisan** [comment]
added branch issue_718_1 for the first test case. please review.

**Comment by silviuFlorin** [comment]
Reviewed branch issue_718_1. Fixed a typo. Code approved

**Comment by icrisan** [comment]
added branch issue_718_2 for the second test case. please review

**Comment by icrisan** [comment]
added branch issue_718_3 for the third test case. please review

**Comment by silviuFlorin** [comment]
Code approved for Location Bar Displays Zoom Indicator test

**Comment by silviuFlorin** [comment]
Reviewed code for Zoom Indicator Animation test. Removed unused local variable. Code approved

**Comment by icrisan** [comment]
added branch issue_718_4 for the last test case. please review

**Comment by silviuFlorin** [comment]
Code approved for Zoom Indicator Hides test
