### ISSUE TITLE
OCR: Implement better text recognition for high definition screens

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#73]
Right now, on hi-def screens such as Mac Retina, the OCR APIs such as `Region.text()` are not very accurate. We can fix this by detecting when we are on a hi-definition screen and use a different image size and/or resolution for text extraction.

**Comment by mwobensmith** [comment]
Use the API that @silviuFlorin created in #74

**Comment by silviuFlorin** [comment]
Code looks good. Tests passed on all platforms. Bellow i attached the results for future reference. 
<img width="849" alt="mac_results" src="https://user-images.githubusercontent.com/28757652/41765133-dca15c14-760b-11e8-9e0e-065d79a23eaa.png">
![ubuntu_results](https://user-images.githubusercontent.com/28757652/41765134-dcc6bebe-760b-11e8-9db5-117d4bb7766a.png)
![windows_results](https://user-images.githubusercontent.com/28757652/41765136-dcf2e46c-760b-11e8-98c6-f82c4658b63c.png)

**Comment by silviuFlorin** [comment]
Code approved

**Comment by mwobensmith** [comment]
This is fine to land, but I wasn't able to review before we merged to master. As a result, it might be out of sync and need to be rebased before creating a PR.
