### ISSUE TITLE
Split the 'zoom_level_multiple_tabs.py' test in smaller pieces

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#733]
'zoom_level_multiple_tabs.py' covers the following tests:
[Zoom Level + Multi Tabs/Sites](https://testrail.stage.mozaws.net/index.php?/cases/view/7448)
[Zoom Level + Window State ](https://testrail.stage.mozaws.net/index.php?/cases/view/7449)

We need one Iris test for each test in TestRail.

**Comment by silviuFlorin** [comment]
Code approved for Zoom Level + Multi Tabs/Sites test

**Comment by icrisan** [comment]
added branch issue_733_2 for test case 2. please review

**Comment by silviuFlorin** [comment]
Code approved for Zoom Level + Window State test
