### ISSUE TITLE
Split the 'zoom_level_with_mouse_wheel.py' test in smaller pieces 

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#736]
'zoom_level_with_mouse_wheel.py' covers the following tests:
[Location Bar Displays Zoom Indicator](https://testrail.stage.mozaws.net/index.php?/cases/view/7450)
[Zoom Indicator Animation ](https://testrail.stage.mozaws.net/index.php?/cases/view/7451)
[Zoom Indicator Hides ](https://testrail.stage.mozaws.net/index.php?/cases/view/7452)

We need one Iris test for each test in TestRail.

**Comment by icrisan** [comment]
added branch issue_736_1 , issue_736_2 and issue_736_3 for first, second and third test case. please review.

**Comment by tracywalker** [comment]
looks good,  merge them.
