### ISSUE TITLE
Implement Platform.HIDEF property to detect high resolution screens

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#74]
In cases where we have a high definition screen, such as Mac Retina and Win 4k, the `pyautogui.size()` API does not return the correct screen coordinates. However, `pyautogui.screenshot().size` is correct, and returns values twice as large as `pyautogui.size()`. 

By comparing these two, we know when we are on a high-definition screen.

A property such as `Platform.HIDEF` could be created, and it could be `True`/`False` based on the above. This property can then be used in other parts of Iris where we need to adjust our image logic.

**Comment by silviuFlorin** [comment]
I created branch [issue_74] for this issue. Please review

**Comment by mwobensmith** [comment]
Looks great! Merged into master.
