### ISSUE TITLE
Match test case __init__ to Testrail info once that integration lands.

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#750]
We'll have to add an ID that matches the TestRail test case ID to the __init__ of each test case. Something like following (we'll know exactly once Testrail support lands
self.ID = XXXXX

While we're touching each test case to add the ID, I'd like us to standardize a
self.summary = *The TestRail test case summary*

That or use self.meta for the summary instead of a "This is a test case that blah...." test case description.

**Comment by silviuFlorin** [comment]
Reviewed branch issue_750. Code approved
