### ISSUE TITLE
Fix zoom_controls_on_toolbar.py on Windows

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#756]
This test case relies on Drag and Drop, which changed slightly in issue #665.  This test case looks for an image just after the zoom controls have been drag and dropped to the toolbar.  The image has a tool tip in it.  Now the tool tip isn't triggered because the drop location has changed slightly, to the center of the drop target image. As such, the pattern match fails.  Please update the image to not include the tooltip.

**Comment by tracywalker** [comment]
Maybe even reset_mouse() just after the DnD to ensure a consitent state.  You'll have to check what happens, in that case, on Mac and Linux too.

**Comment by icrisan** [comment]
Changed the picture on windows and reset the mouse after drag and drop.
Created branch issue_756. Please review.

**Comment by silviuFlorin** [comment]
Code approved.
