### ISSUE TITLE
Make better favicons for local web sites

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#764]
Currently favicons are generic dots of different colors. It might be nice to make them unique shapes as well.

**Comment by GriffinAustin** [comment]
What exactly were you thinking?

**Comment by mwobensmith** [comment]
Not sure. One issue is that our pattern searching currently is done inside a greyscale image, and doesn't pick up on color. Therefore, all of these favicons would be considered the same because they only differ in color. At the same time, tests rarely just look for the favicon, and we will probably implement an image search that allows one to request a level of precision that forces us to do a color image search.

**Comment by mwobensmith** [comment]
We should probably just make SVG icons of the corresponding logos of each product's page.

**Comment by mwobensmith** [comment]
Probably no good reason to change what we have.
