### ISSUE TITLE
Split the 'zoom_level_multiple_tabs_with_mouse_wheel.py' test in smaller pieces

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#766]
'zoom_level_multiple_tabs_with_mouse_wheel.py' covers the following tests:
[Zoom Level + Multi Tabs/Sites](https://testrail.stage.mozaws.net/index.php?/cases/view/7453)
[Zoom Level + Window State](https://testrail.stage.mozaws.net/index.php?/cases/view/7454)

We need one Iris test for each test in TestRail.

**Comment by icrisan** [comment]
please review branch "issue_766_2" created for test case 2

**Comment by tracywalker** [comment]
code approved

**Comment by icrisan** [comment]
Please don't close this until I will update the first test case pointed in this issue.

**Comment by icrisan** [comment]
added branch issue_766_1 for the first test case. I also updated test "zoom_level_multiple_tabs_with_mouse_wheel.py" test to use 2 different local origins. please review.

**Comment by silviuFlorin** [comment]
Fixed rebase conflicts. Code approved.
