### ISSUE TITLE
Higher precision than default is needed in order to catch "FAIL PASS" results

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#777]
Please take as reference the branch "issue_766_2". Now, please observe the following lines of code:

       # zoom in ONE time.
        zoom_with_mouse_wheel(1, ZoomType.IN)

        if Settings.getOS() == Platform.MAC:
            if is_retina is False:
                expected = exists(search_bar_wikipedia_110_zoom_level, 10, 0.91)
                assert_true(self, expected, 'Zoom level successfully increased, zoom controls found in the url bar.')
            else:
                expected = exists(search_bar_wikipedia_110_zoom_level, 10, 0.94)
                assert_true(self, expected, 'Zoom level successfully increased, zoom controls found in the url bar.')
        else:
            expected = exists(search_bar_wikipedia_110_zoom_level, 10, 0.98)
            assert_true(self, expected, 'Zoom level successfully increased, zoom controls found in the url bar.')

As you can notice I have used different precision for the almost all the OSes(for Linux and Windows I used the same precision) in order to assert the same thing. 

Why did I do that? Because otherwise the asserts wouldn't catch a possible failure. 

How did I found that? I zoomed in the browser twice and expected the assert to fail but it didn't failed.

Why do I used different precision for almost all the OSes? Because if I use the same precision for all the OSes the assert won't catch a possible failure(if the precision is smaller than the expected) giving us a "FAIL PASS" result or the assert will simply NOT PASS when it should if the precision is too big.

I tried with much smaller images and I managed to catch the "FAIL PASS" results using the default precision(0.8) on MAC with retina and on WINDOWS but I couldn't manage to give up on a higher precision on LINUX.

Please let me know your thoughts about what approach should we take here.

**Comment by silviuFlorin** [comment]
This is somehow expected considering every OS has different fonts for zoom indicator and the percentage of the text in regards to the total image size is sometimes under 1% (in this case a similarity of .98 or .99 will return a correct result). There is not a standard approach for this cases. Just have a big similarity at the beginning and lower it progressively until it fails.

**Comment by mwobensmith** [comment]
@silviuFlorin : So, are you proposing that there should be one similarity value that will work for all configurations? 

Or should we change the patterns to exclude the text?

Whatever we do, we don't want a test case to have to use different logic for each OS.

**Comment by silviuFlorin** [comment]
We could use the same similarity for each OS. But what should we do is to crop the searched patterns to contain just the text. We will do an experiment tomorrow and see how it goes

**Comment by icrisan** [comment]
I tried with much smaller images and it works if the pictures contains just text for example "100". Though it did't work on all the platforms with pictures that contain "100%" text.
P.S: I've tested on WINDOWS, LINUX and MAC with retina.

**Comment by mwobensmith** [comment]
All of the zoom indicator images used in this test should be added to the `firefox_ui.toolbar `package, to the `LocationBar` class. Then, all of the test cases that use them should use these central UI assets. 

If we continue to have issues with similarity, we can tweak them in the `LocationBar` class itself.

**Comment by AndreiH** [comment]
@mwobensmith , this is now ready for review on branch `issue_777`. Thanks !
