### ISSUE TITLE
Parse Firefox metadata from about:support page

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#790]
The `about:support` page provides much data about Firefox and its host environment. We should build a helper function that opens this page, copies test to clipboard, then parses the values into an object available to Iris tests and the app itself.

The page has a button that will place nicely-formatted data on the clipboard. Or, we can just do a select-all on the page and then copy. Either way, we'll have data to parse.

This can be used in update testing. It provides one way to verify the current, active version of Firefox.

**Comment by mwobensmith** [comment]
Create a function called `get_support_info` and put it at the bottom of `api/helpers/general.py`.

This API will:
- Open a new tab
- Navigate to "about:support"
- Click on the web page
- Select all
- `copy_to_clipboard`
- Close tab
- Parse clipboard contents into four properties:
1. `version` ("Version")
2. `build_id` ("Build ID")
3. `channel` ("Update Channel")
4. `locale` (available in "Default Locale" at bottom of page)
- Return an object with these four properties.


Update the unit test to make sure these values are correct.

- See `tests/unit_tests/firefox_build_apis.py`
- There are currently four asserts here, using APIs that I just added.
- Create four more, using the API created above.

**Comment by AndreiH** [comment]
API method added in branch "issue_790". Ready for review.

**Comment by AndreiH** [comment]
Actually, I have second thoughts using 'mozversion' module library.
The information given by the library is not all the information from "about:support" page.
This is the output that "mozversion" library offers:
```mozversion INFO | application_buildid: 20180807170231
mozversion INFO | application_changeset: 975058795980dfbba1daedfe5fc82d1abcb5638b
mozversion INFO | application_display_name: Firefox
mozversion INFO | application_id: {ec8030f7-c20a-464f-9b0e-13a3a9e97384}
mozversion INFO | application_name: Firefox
mozversion INFO | application_remotingname: firefox
mozversion INFO | application_repository: https://hg.mozilla.org/releases/mozilla-release
mozversion INFO | application_vendor: Mozilla
mozversion INFO | application_version: 61.0.2
mozversion INFO | platform_buildid: 20180807170231
mozversion INFO | platform_changeset: 975058795980dfbba1daedfe5fc82d1abcb5638b
mozversion INFO | platform_repository: https://hg.mozilla.org/releases/mozilla-release
mozversion INFO | platform_version: 61.0.2```

For example we do not have information on Locale.

**Comment by AndreiH** [comment]
@tracywalker this is now ready for review.
The mozversion module has been also added. 
Thanks !

**Comment by tracywalker** [comment]
Matt, assigning you this one for review.
