### ISSUE TITLE
Disable multiprocessing for Windows

### ISSUE THREAD

**Issue by silviuFlorin** [mozilla/iris#799]
While Linux and Mac supports the fork(2) system call that creates a child processes already in possession of exactly the same resources as its parent, every Windows process must spin up independently of the parent process that created it

This is why performance on Windows is much slower than Linux or Mac when using multiprocessing. 
We should update the is_multiprocessing_enabled() function to:

```
def is_multiprocessing_enabled():
    return multiprocessing.cpu_count() >= MIN_CPU_FOR_MULTIPROCESSING and get_os() != 'win'
```

Windows will use in this case the old single-threaded implementation for image search

**Comment by mwobensmith** [comment]
Thanks @silviuFlorin I had been meaning to file this.

**Comment by silviuFlorin** [comment]
@mwobensmith Please review branch issue_799_810
