### ISSUE TITLE
Intermittent errors in open_library_menu

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#815]
It seems that we have a regression from #814 that could be related to turning off multiprocessing on Windows. I see 6 or 7 test cases that all raise an `APIHelperError` - "Can't find the library menu in the page, aborting test."

**Comment by silviuFlorin** [comment]
@mwobensmith Please review branch issue_815.

**Comment by mwobensmith** [comment]
This looks good. I was not able to confirm that this was fixed because my Iris run was stopped by several camelCase uses that we had not fixed. Those are now fixed in the dev branch, but you would have to rebase this with dev to get those changes.

If you can do a full pass on Windows with your branch, and see no new errors, consider this an approval and ask @icrisan to land it. Thanks.

**Comment by silviuFlorin** [comment]
@mwobensmith I did a full pass on Windows and no new errors observed
