### ISSUE TITLE
Investigate which values in Iris should be treated and named as constants

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#820]
We have inconsistency w/r/t some values that we use in Iris, specifically the `Settings` class. We have many values that have default declarations:

```
DEFAULT_OBSERVE_SCAN_RATE = 3
DEFAULT_AUTO_WAIT_TIMEOUT = 3
DEFAULT_DELAY_BEFORE_MOUSE_DOWN = 0.3
```

We then expose most of them as quasi-static properties of the `Settings` class. 

```
    @property
    def observe_scan_rate(self):
        return self._observe_scan_rate

    @observe_scan_rate.setter
    def observe_scan_rate(self, value):
        self._observe_scan_rate = value
```

All of these values could be set at the beginning of an Iris run to override their defaults. However, at runtime, some of them should remain constant and not changeable by tests. 

We need to go through the APIs exposed by the `Settings` class, and if it is truly a constant, give it a name in all caps. Similarly, if it is a constant, it should not have a setter function.

```
    @property
    def FX_DELAY(self):
        return self._fx_delay

    # this setter should probably go away
    @FX_DELAY.setter
    def FX_DELAY(self, value):
        self._fx_delay = value
```

**Comment by silviuFlorin** [comment]
The following are definitely constants:
```
FX_DELAY
UI_DELAY
UI_DELAY_LONG
SYSTEM_DELAY
```
They don't need setters or getters and could be declared as:
```
class _IrisSettings(object):
    FX_DELAY = 0.5
    ...
```
The rest are properties that can be retrieved or updated any time during runtime.  The main reason why we declared those constants at the top of the settings.py is for visibility and to easily update their default values.

We could as well remove them and do something like this:
```
class _IrisSettings(object):
    ...
    def __init__(self):
        self._wait_scan_rate = 3
        ...
```
 @mwobensmith What do you think?

**Comment by mwobensmith** [comment]
Well, even the values `FX_DELAY` and such could be modified if we put in logic to do so. In the case of `FX_DELAY` and similar values, we might create some kind of runtime adjustment to compensate for the speed of the environment. 

However, I guess it's the "spirit" of what a constant means that is what I'm trying to define. To me, a constant in Iris:

* Stays the same for the duration of the run (though might be changed from its default at the start)
* Should not be changed by a test

 I guess it follows that other Iris code should not be able to change constants, but depending on what that code is, we could break that rule.

**Comment by mwobensmith** [comment]
I definitely agree, though, that constants - as you listed above - should be declared as static members of `_IrisSettings`, and therefore `Settings`. They don't require getter functions.

**Comment by silviuFlorin** [comment]
If I think about it, DEFAULT_OBSERVE_SCAN_RATE, etc. should remain as constants in case we want to reset a setting to it's default value
