### ISSUE TITLE
Improve image search debug messages

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#821]
On non-multiprocessing platforms, line 277 in `image_search.py` gets invoked:

`        logger.debug("Searching for image %s" % pattern)`

This outputs the string equivalent of the `Pattern` object, which is not very human-readable. I thought we used to have something better before. Perhaps we changed it recently? In any case, I'd expect to see a pattern name or (better) path on disk.

Also, for multiprocessing platforms, we don't hit this code, so we don't have a similar debug message. We should add one.

**Comment by silviuFlorin** [comment]
@mwobensmith I also came across this issue and already fixed it in branch issue_815
