### ISSUE TITLE
Update existing zoom indicator tests to use local sites and update images where needed to avoid false PASS results

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#823]
Tests that need to be updated are the following:
1. default_zoom_level.py
2. zoom_level_window_state.py
3. location_bar_no_zoom_indicator.py
4. location_bar_displays_zoom_indicator.py
5. location_bar_displays_zoom_indicator_mouse_wheel.py
6. location_bar_zoom_indicator_hides.py
7. location_bar_zoom_indicator_hides_mouse_wheel.py
8. location_bar_zoom_indicator_animation.py
9. location_bar_zoom_indicator_animation_mouse_wheel.py
10. zoom_controls_on_toolbar.py
11. zoom_in_menu_bar.py

**Comment by icrisan** [comment]
created branch issue_823_2 for test case 2. please review

**Comment by icrisan** [comment]
created branch "issue_823_3" for test case 3, 4 and 5. please review

**Comment by icrisan** [comment]
created branch "issue_823_1" for test case 1. please review

**Comment by tracywalker** [comment]
issue_823_1 isn't ready yet.  The final check, exists(edit_buttons_below_zoom_buttons), fails for me on Mac-retina. If I lower the precision to .25, it works. 

Also, I am getting conflicts in __main__.py in your branch. 

Ioana, please try out my solution, if it works correctly for you across platform, go ahead and land it after addressing that __main__.py issue.

**Comment by tracywalker** [comment]
branch issue_823_2 code approved.

**Comment by tracywalker** [comment]
branch issue_823_3 code approved.

**Comment by icrisan** [comment]
created branch "issue_823_4" for test case 6 and 7. please review

**Comment by tracywalker** [comment]
branch issue_823_4 code approved.

**Comment by icrisan** [comment]
created branch "issue_823_5" for test case 8 and 9. please review

**Comment by silviuFlorin** [comment]
Code approved for branch issue_823_5

**Comment by icrisan** [comment]
created branch "issue_823_6" for test case 10 and 11. please review.
