### ISSUE TITLE
Provide a way to declare variables that can be shared across tests

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#845]
@psilaghi asked for a way to share variable declarations across multiple tests, so that one doesn't have to do it over and over. There are several approaches, but I think I found one that works well.

In each directory, there is a reserved file called `__init__.py`. For our project, they have remained empty, but we have the potential to put code in there that is shared by other modules.

Here is a suggestion. If you are trying to do this with tests that live in `bookmark_tests`, add the following code to the file at `bookmark_tests/__init__.py`:

```
# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this file,
# You can obtain one at http://mozilla.org/MPL/2.0/.

def declare_patterns(self):
        self.history_dropdown = 'history_dropdown_button.png'
        self.privacy_page = 'privacy_page.png'
        self.restart_browser = 'restart_browser.png'
        self.never_remember_history = 'never_remember_history.png'
        self.amazon_home = 'amazon.png'
        self.star_button = 'bookmark_star.png'
```

Then, in `bookmark_from_private_browsing.py`, add this to your imports at the top:

```
from iris.tests.bookmark_tests import declare_patterns
```

Add this code to your `run` method, to replace your variable declarations:
```
    declare_patterns(self)
```

Now all of the above should be available to your test. Remember that you will need to reference these variables via `self`, so you will need to update your code to reflect this. However, I'm hoping that this solution works for you. 

Please try this and let me know.

**Comment by psilaghi** [comment]
Hi Matt,
Thank you very much for your research.
Although the above is a valid solution, it has some disadvantages:
- you need to reference the variables via 'self'
- you need to run 'declare_patterns(self)'
- not sure if this supports to use images across components (eg: in 'History' tests I use several images from 'Bookmarks')
Anyway, let me show you my suggestions:
1. This is the easiest method.
variables.py - in the root of Iris (or anywhere) which will contain:
# History images:
search_history_box = 'search_history_box.png'
expand_button_history_sidebar = 'expand_button_history_sidebar.png'
history_sidebar_default = 'history_sidebar_default.png'

# Bookmarks images:
toolbar_bookmark = 'toolbar_dragged_bookmark.png'
close_sidebar_search = 'close_sidebar_search.png'
bookmarks_sidebar_menu = 'bookmarks_sidebar_menu.png'

Then, in any test I'm currently working on, I just need to do the import:
from iris.variables import *
and the simply use any variables I want:
expected_1 = exists(history_sidebar_default, 10)
expected_2 = exists(toolbar_bookmark, 10)

This is similar with the config.ini file we use for credentials, except that we don't need a ConfigParser().

2. Using OOP
variables.py:
class Image(object):
      class History(object):
            search_history_box = ''search_history_box.png'
            expand_button_history_sidebar = 'expand_button_history_sidebar.png'
            history_sidebar_default = 'history_sidebar_default.png'

      class Bookmarks(object):
            toolbar_bookmark = 'toolbar_dragged_bookmark.png'
            close_sidebar_search = 'close_sidebar_search.png'
            bookmarks_sidebar_menu = 'bookmarks_sidebar_menu.png'

In mytest.py I will use:
from iris.variables import Image
expected_1 = exists(Image.History.history_sidebar_default, 10)
expected_2 = exists(Image.Bookmarks.toolbar_bookmark, 10)

My point was also to have all the images from the project(or the most of them) in one file.
In this way, we can search for existing images more quickly and also reduce the duplicates by just taking a look at the related components I'm working on.

Please let me know your thoughts.

**Comment by silviuFlorin** [comment]
@mwobensmith @psilaghi I would also go for the second proposal. It's a more elegant and organized way to store images names

**Comment by mwobensmith** [comment]
I think we are in agreement. Now we need to know what it will look like. I suggest we continue the conversation in #647.

**Comment by psilaghi** [comment]
Agreed. Thanks all.
