### ISSUE TITLE
Review Sikuli API and make a list of missing items

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#85]
Examine the document [here](http://sikulix-2014.readthedocs.io/en/latest/genindex.html) and make a list of APIs that Iris does not support yet. Add the list as a comment to this issue. Pay special attention to APIs that we may currently support, but might be missing additional parameters or functionality.

**Comment by silviuFlorin** [comment]
[Here](https://docs.google.com/spreadsheets/d/1so1FREvCUKczJJ_fmASwaTIJsjduRLv3ZsTBMPL8KEQ/edit#gid=0) you can find a document with our current progress in covering Sikuli APIs
