### ISSUE TITLE
Fix errors in linux bootstrap script

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#865]
* The `libpng12-dev` package was renamed to `libpng-dev`, so `sudo apt install` fails; 

* `sudo mv * /usr/local/share/tessdata/` does not work when the destination directory doesn't exist, so there should be a `sudo mkdir -p /usr/local/share/tessdata/` before that.

**Comment by mwobensmith** [comment]
Someone needs to keystroke this on a fresh Linux install and see if it's still happening. If not, close.

**Comment by AndreiH** [comment]
This is now ready for review on branch "issue_865".
I also added some nice enhancements with coloured output, to be easier to understand which step failed, if a library installation fails
