### ISSUE TITLE
Develop test case: Custom sections selected in 'Clear Recent History' window

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#885]
https://testrail.stage.mozaws.net/index.php?/cases/view/172047

**Comment by tracywalker** [comment]
Roxana,  the scroll in page doesn't always work for me on Windows and OSX.  Sometimes it doesn't scroll far enough.  When you need to scroll, do so in small(ish) increments until you find the image the test needs to interact with.  When doing the above incremental scrolling,  ensure there is a way out of the loop.

Also, is the assert_false in line 133 supposed to be false?  The test calls for checking that the history is all cleared? You've checked all the boxes in the customize section....so everything should be gone after "Clear Now".  This step is failing.

**Comment by rrobotin** [comment]
Refactored the scroll in page code in issue_885 branch
@tracywalker  Please review
Thanks

**Comment by tracywalker** [comment]
Roxana. I really like the incremental scroll check.  Thank you.

code approved
