### ISSUE TITLE
Develop test case: Open all the history from a history time range

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#889]
https://testrail.stage.mozaws.net/index.php?/cases/view/174033

**Comment by icrisan** [comment]
coverage added in branch "issue_889". @tracywalker please review.

**Comment by tracywalker** [comment]
code approved

**Comment by tracywalker** [comment]
Fixing this is turning out to be a bit more complex than expected.  In addition to the confirming that the history items are opened as expected, we must also check that function occurs in the current window.    It seems we can't count on the order of the tabs being loaded. As such, the final history items in tab check should be made to check for the tab favicon of the local mozilla page, not the logo in page content. We should also add a check that the original tab (in this case a new tab page) is still present by also checking for its tab favicon.  Can you take care of these changes, Ioana?

**Comment by icrisan** [comment]
I updated the "mozilla_logo_tab.png" on MAC. The pattern was totally different from the other OSes. After that I made sure that my test and the other 2 tests that used that pattern still work. I also added a tab check for the new tab page. @tracywalker please review. Thank you!!!

**Comment by tracywalker** [comment]
Thank you, Ioana.  code approved.
