### ISSUE TITLE
Develop test case: Verify if the deleted page from History is retained in auto-complete

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#904]
https://testrail.stage.mozaws.net/index.php?/cases/view/174049

**Comment by tracywalker** [comment]
Alin, I have two concerns with this test case.  First has nothing to do with Iris; this testrail test case is incorrect. If you delete a page visit, that page should NOT show up in the url bar. Try the test with a clean profile, visit any site.  Check that typing the page again does autocomplete.  Then do the test steps 2-5;  notice the page is no longer auto-completed. This is what I expect to be correct, (it's a privacy thing).   The expected results in this test case should read "The name of the page is not auto-completed."

Second, the Iris test is passing the incorrect TestRail test because it's only looking for a partial bit of the local address.  127.0.0 is part of other urls in the history of that profile. If you want to continue to use the local page, you have to type out far enough to get to the unique portion of the url under test.  Then you'll find that the test fails.

I have corrected the TestRail test case. Please adjust your test to match. Thank you.

**Comment by alinrus** [comment]
Hi Tracy,
From what I've noticed running also other tests, and also by manually testing, if only we Forget a page from History we won't expect the page to show up in url bar after, if we Delete a page we expect the name of the page to be auto-completed in the url bar. Event it's a little bit confusing, this is the behavior I've observed, also looking in the following testrails test cases:
Delete a page -> Expected results: The name of the page is auto-completed.
- https://testrail.stage.mozaws.net/index.php?/cases/view/120131
automated test: history_sidebar_delete_site_verify_if_remembered

Forget a page - > The name of the page is NOT auto-completed.
- https://testrail.stage.mozaws.net/index.php?/cases/view/120133
automated test: history_sidebar_forget_site_verify_if_remembered
- https://testrail.stage.mozaws.net/index.php?/cases/view/174051

Please take a look on the above tests and take in consideration that, this is how right now actually working. If we need to correct also them, for sure we need to adjust the tests we have already, let me know for further actions, thank you Tracy.

**Comment by tracywalker** [comment]
I reverted the TestRail test case until we can sort this out.  What I am seeing is actually the opposite of what those tests are expecting.  'Delete Page' removes the page from history and removes autocomplete in url bar.  'Forget About This Site' removes all page visits to the site from history but does not remove autocomplete in url bar.  The latter has to be a bug in Firefox. Also, for some reason autocomplete doesn't work with every url.  For example. visiting nytimes.com will generate the ability autocomplete. Where as visiting yahoo.com does not. 

Alin please work with the test case author and/or feature owner/devolper to find out what is going on.  Are the test cases accurate and Firefox bugged? Or has the expected behavior of Firefox changed?

**Comment by tracywalker** [comment]
Ok, so another scenario:  Delete Page visit of page from multiple page visits at a single site should not remove the autocomplete for that 'site.'  This is what you have replicated in the test for this issue.  The testrail test here is unclear whether the page deleted is among other pages at a site or not.  This has to be defined, because it does make a difference as to what is expected.

**Comment by alinrus** [comment]
> Ok, so another scenario: Delete Page visit of page from multiple page visits at a single site should not remove the autocomplete for that 'site.' This is what you have replicated in the test for this issue. The testrail test here is unclear whether the page deleted is among other pages visited at a site or not. This has to be defined, because it does make a difference as to what is expected.
> 
> There should be test cases for both scenarios of Delete Page: One test for a single page visited at a site, then that page deleted and another test for multiple pages visited at a site and one of them deleted.

Yes, the tests it's not very clear and generates confusion. We have to specify that we are expecting to see auto-filled other pages than the one deleted before from the same domain. Agree with you, we should have two test cases here. 

If we have only the main page, and nothing else in auto-filled related to this page, we should not expect to see auto-filled after delete.

**Comment by alinrus** [comment]
After doing some reasearch, the actual algorithm behind autocomplete/auto-fill is as following:

Every page has a frecency and an origin (like www.google.com/index.html, www.google.com is the origin), origin has a frecency that is the sum of all the frecencies of all the pages in it. The threshold is the average of all the origins frecencies.
if an origin is over the threshold it gets auto-filled, otherwise not.

These is working on a clean profile (all bookmarks are removed) 

Using a dirty profile doesn't guaranty that the origin will be auto completed, it's really depending on the precondition.

**Comment by tracywalker** [comment]
wow, ok.  We really need to narrow down what is expected in each test case and make sure our test(s) are functioning under the correct state, such that we can get reliable results.  

Thanks for do this research, Alin.

**Comment by alinrus** [comment]
Also in the automated test, I've used TEN_BOOKMARKS profile, which has already ten bookmarks, including Mozilla, it was also disturbing.

**Comment by alinrus** [comment]
Tracy, can you please make an update at step 5, Expected results and also at the Preconditions, I don't have rights for edit in TestRail. 
https://testrail.stage.mozaws.net/index.php?/cases/view/174049

Supposing that this is applied when multiple pages visited from the same domain and just one of them deleted, would be nice to have a test like you said for the scenario when only the domain page is visited and deleted, where we won't expect auto-fill to be displayed for Delete Page action.

**Comment by alinrus** [comment]
Coverage updates done in branch 'issue_904'. @tracywalker please review. Thank you!

**Comment by tracywalker** [comment]
code approved with minor change to the test case __init__.
