### ISSUE TITLE
Develop test case: Forget all the history from the last 5 minutes

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#907]
https://testrail.stage.mozaws.net/index.php?/cases/view/174072

Note: It isn't mentioned in the manual test, but prerequisite of this test is that the Forget button has to be added to the toolbar via customize.

**Comment by icrisan** [comment]
coverage added in branch "issue_907". @tracywalker please review.
P.S: I also removed the unnecessary setup from multiple tests cases.

**Comment by tracywalker** [comment]
code approved
