### ISSUE TITLE
Develop test case: Page visits show in Bookshelf > History > Recent History

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#908]
https://testrail.stage.mozaws.net/index.php?/cases/view/178345

**Comment by alinrus** [comment]
Coverage added in branch 'issue_908'. @tracywalker please review.

**Comment by tracywalker** [comment]
Alin, please rebase the branch issue_908.

**Comment by alinrus** [comment]
Hi Tracy,
Rebase done, looking forward.

Thanks,
Alin

**Comment by tracywalker** [comment]
code approved with tiny punctuation fix.
