### ISSUE TITLE
Develop test case: Delete history from Library context menu

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#909]
https://testrail.stage.mozaws.net/index.php?/cases/view/178346

**Comment by tracywalker** [comment]
Alin, this is fine on Mac.  However, on my Linux machine, the final wait_vanish is failing.  Iris is matching the iris logo page entry in the library list.  I increased the similarity to 0.9 to make this work without false matching.

code approved

**Comment by alinrus** [comment]
Sounds great, I will take in consideration for next time to check on
multiple Linux machines as well.

Thank you Tracy!
