### ISSUE TITLE
Use localized builds of Firefox

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#944]
We have support for downloading different locales of Firefox, but we have never tested it. We should try it and run a full pass to see if it actually works, or if there are bugs.

**Comment by mwobensmith** [comment]
Note: Locales are case-sensitive. Hence, `en-GB` yes, but `en-gb` no.

**Comment by mwobensmith** [comment]
It works, but already found an issue: on Mac, unzipped builds of Firefox are cached, so the correct build is not used. Will file another issue for that.

**Comment by AndreiH** [comment]
Just putting it here to have a link between the found Bugs: https://github.com/mozilla/iris/issues/1001

**Comment by mwobensmith** [comment]
This should work. Let's run a full pass once we stabilize the project a bit, and if we get no unexpected failures, we can close this issue.
