### ISSUE TITLE
The 'double_click()' method does not work on MAC OS

### ISSUE THREAD

**Issue by icrisan** [mozilla/iris#950]
Single click is performed when calling the double_click() method on MAC OS.

**Comment by tracywalker** [comment]
This is reproducible in awesomebar testcase disable_web_search_awesomebar, currently in branch issue_200.  We'll check-in issue 200 with the test case disabled on Mac. Please re-enable that test along side the fix for this issue.

**Comment by tracywalker** [comment]
Also, turn off the exclude in the test case in issue 203 once this is fixed.

**Comment by tracywalker** [comment]
Andrei, Ioana and I have both failed to find a solution for this.  Please take a look. thanks.

**Comment by AndreiH** [comment]
@tracywalker I will gladly take a look over this, i am almost finished with issue_790

**Comment by tracywalker** [comment]
code approved for branch issue_950.  note: please 'pip install pynput' to make Iris work on dev.
