### ISSUE TITLE
Use Pattern() for all images in Iris test groups

### ISSUE THREAD

**Issue by tracywalker** [mozilla/iris#952]
Do to changes in how Iris handles images and their locations, it is critical that all usage of pattern matching be done by explicitly making the images patterns.

for instance:
image_foo = 'foo.png'
should be converted to:
image_foo = Pattern('foo.png')

This issue will track work done in all of existing test cases. In any new test cases please use Pattern()

**Comment by tracywalker** [comment]
Silviu volunteered to fix all the test cases in one pass.   Adjusting this to track that.

**Comment by silviuFlorin** [comment]
@mwobensmith please review branch issue_647_952
