### ISSUE TITLE
Create helper function to restore focus to Firefox

### ISSUE THREAD

**Issue by mwobensmith** [mozilla/iris#978]
There are times when Firefox loses focus, and while it might appear to be the active application or window, it does not seem to accept keyboard input. For instance, on Mac, when the Clear Recent History dialog is open, and the Enter key is pressed, the dialog disappears but the browser is in this state. Iris then sends all key input into the void. This causes a test to hang.

Normal human usage does not encounter this problem because they usually click somewhere next, and focus is regained.

I will make a method called `restore_focus` that clicks on the nav bar to the right of the Home button. It can be used in helper functions or in tests themselves.

**Comment by tracywalker** [comment]
Focus, in the case you gave, goes to the page content.  If there isn't an element for text entry in content, then keyboard input goes to nothing.  However,  if you do something like, cmd/ctr + L.  focus is then set to the location bar.
